FROM python:3.10-slim-buster
ENV PYTHONUNBUFFERED 1
RUN mkdir /code
RUN mkdir /code/faustians
WORKDIR /code/faustians
RUN pip3 install poetry
COPY . /code/faustians

ENV PYTHONDONTWRITEBYTECODE=1

RUN poetry install

ENV PYTHONPATH "${PYTHONPATH}:/code"

# CMD poetry run faust -A main:app worker -l info
