FROM python:3.10-slim-buster
ENV PYTHONUNBUFFERED 1
RUN mkdir /code
RUN mkdir /code/payments
WORKDIR /code/payments
RUN pip3 install poetry
COPY . /code/payments

ENV PYTHONDONTWRITEBYTECODE=1

RUN poetry install

ENV PYTHONPATH "${PYTHONPATH}:/code"
