"""Fixed typos_6!

Revision ID: 0176a8b5efb9
Revises: 66c728f83152
Create Date: 2023-11-22 12:49:34.910508

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlalchemy_utils


# revision identifiers, used by Alembic.
revision: str = '0176a8b5efb9'
down_revision: Union[str, None] = '66c728f83152'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('subscribes_doctors', sa.Column('client_subscribe_doctor_id', sa.Integer(), nullable=True, comment='Идентификатор доктра на абонементе в системе клиента'))
    op.drop_column('subscribes_doctors', 'client_suscribe_doctor_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('subscribes_doctors', sa.Column('client_suscribe_doctor_id', sa.INTEGER(), autoincrement=False, nullable=True, comment='Идентификатор доктра на абонементе в системе клиента'))
    op.drop_column('subscribes_doctors', 'client_subscribe_doctor_id')
    # ### end Alembic commands ###
