"""The new table users_default_objects has been added

Revision ID: 02e44fd28f7c
Revises: 488764cb5e97
Create Date: 2024-01-19 14:51:35.559020

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlalchemy_utils


# revision identifiers, used by Alembic.
revision: str = '02e44fd28f7c'
down_revision: Union[str, None] = '488764cb5e97'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users_default_objects',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True, comment='Идентификатор пользователя'),
    sa.Column('default_patient_id', sa.Integer(), nullable=True, comment='Идентификатор пациента по умолчанию'),
    sa.Column('default_medical_center_id', sa.Integer(), nullable=False, comment='Идентификатор медицинского центра по умолчанию'),
    sa.Column('default_doctor_mcenters_id', sa.Integer(), nullable=False, comment='Идентификатор доктора по умолчанию'),
    sa.ForeignKeyConstraint(['default_doctor_mcenters_id'], ['doctors_medical_centers.id'], ),
    sa.ForeignKeyConstraint(['default_medical_center_id'], ['medical_centers.id'], ),
    sa.ForeignKeyConstraint(['default_patient_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    comment='Таблица "Объекты по умолчанию для пользователей"'
    )
    op.create_index(op.f('ix_users_default_objects_id'), 'users_default_objects', ['id'], unique=False)
    op.drop_index('ix_default_objects_id', table_name='default_objects')
    op.drop_table('default_objects')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('default_objects',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.INTEGER(), autoincrement=False, nullable=True, comment='Идентификатор пользователя'),
    sa.Column('default_patient_id', sa.INTEGER(), autoincrement=False, nullable=True, comment='Идентификатор пациента по умолчанию'),
    sa.Column('default_medical_center_id', sa.INTEGER(), autoincrement=False, nullable=False, comment='Идентификатор медицинского центра по умолчанию'),
    sa.Column('default_doctor_mcenters_id', sa.INTEGER(), autoincrement=False, nullable=False, comment='Идентификатор доктора по умолчанию'),
    sa.ForeignKeyConstraint(['default_doctor_mcenters_id'], ['doctors_medical_centers.id'], name='default_objects_default_doctor_mcenters_id_fkey'),
    sa.ForeignKeyConstraint(['default_medical_center_id'], ['medical_centers.id'], name='default_objects_default_medical_center_id_fkey'),
    sa.ForeignKeyConstraint(['default_patient_id'], ['users.id'], name='default_objects_default_patient_id_fkey'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name='default_objects_user_id_fkey'),
    sa.PrimaryKeyConstraint('id', name='default_objects_pkey'),
    comment='Таблица "Объекты по умолчанию"'
    )
    op.create_index('ix_default_objects_id', 'default_objects', ['id'], unique=False)
    op.drop_index(op.f('ix_users_default_objects_id'), table_name='users_default_objects')
    op.drop_table('users_default_objects')
    # ### end Alembic commands ###
