"""typos have been fixed!

Revision ID: 02eaa0d19ec3
Revises: 7ef18c0d7113
Create Date: 2024-04-07 17:31:18.188451

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlalchemy_utils


# revision identifiers, used by Alembic.
revision: str = '02eaa0d19ec3'
down_revision: Union[str, None] = '7ef18c0d7113'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('initpro_payments_receipts', sa.Column('payload_shift_number', sa.String(), nullable=True, comment='Параметр shifr_number в системе Инитпро'))
    op.drop_column('initpro_payments_receipts', 'payload_shifr_number')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('initpro_payments_receipts', sa.Column('payload_shifr_number', sa.VARCHAR(), autoincrement=False, nullable=True, comment='Параметр shifr_number в системе Инитпро'))
    op.drop_column('initpro_payments_receipts', 'payload_shift_number')
    # ### end Alembic commands ###
