"""AddressMisKladrTable has been added_1!

Revision ID: 02f6b7abc0ed
Revises: d5ce15638706
Create Date: 2023-12-04 17:08:20.746686

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlalchemy_utils


# revision identifiers, used by Alembic.
revision: str = '02f6b7abc0ed'
down_revision: Union[str, None] = 'd5ce15638706'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('users', 'first_name',
               existing_type=sa.VARCHAR(length=100),
               nullable=False,
               existing_comment='Имя пользователя')
    op.alter_column('users', 'last_name',
               existing_type=sa.VARCHAR(length=100),
               nullable=False,
               existing_comment='Фамилия пользователя')
    op.alter_column('users', 'email',
               existing_type=sa.VARCHAR(length=200),
               nullable=False,
               existing_comment='Электронная почта пользователя')
    op.alter_column('users', 'default_medical_center_id',
               existing_type=sa.INTEGER(),
               nullable=True,
               existing_comment='Идентификатор медицинского центра, выбранного по умолчанию')
    op.alter_column('users', 'info_way_id',
               existing_type=sa.INTEGER(),
               nullable=True,
               existing_comment='Канал поступления к пользователю информации о клинике')
    op.alter_column('users', 'pref_notification_contact_id',
               existing_type=sa.INTEGER(),
               nullable=True,
               existing_comment='Идентификатор пользователя, контакт которого будет использован при информировании')
    op.drop_constraint('users_phone_number_key', 'users', type_='unique')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint('users_phone_number_key', 'users', ['phone_number'])
    op.alter_column('users', 'pref_notification_contact_id',
               existing_type=sa.INTEGER(),
               nullable=False,
               existing_comment='Идентификатор пользователя, контакт которого будет использован при информировании')
    op.alter_column('users', 'info_way_id',
               existing_type=sa.INTEGER(),
               nullable=False,
               existing_comment='Канал поступления к пользователю информации о клинике')
    op.alter_column('users', 'default_medical_center_id',
               existing_type=sa.INTEGER(),
               nullable=False,
               existing_comment='Идентификатор медицинского центра, выбранного по умолчанию')
    op.alter_column('users', 'email',
               existing_type=sa.VARCHAR(length=200),
               nullable=True,
               existing_comment='Электронная почта пользователя')
    op.alter_column('users', 'last_name',
               existing_type=sa.VARCHAR(length=100),
               nullable=True,
               existing_comment='Фамилия пользователя')
    op.alter_column('users', 'first_name',
               existing_type=sa.VARCHAR(length=100),
               nullable=True,
               existing_comment='Имя пользователя')
    # ### end Alembic commands ###
