"""lpus table has been added

Revision ID: 0b06b91ea746
Revises: 2661dad3cb75
Create Date: 2024-02-19 10:28:32.794814

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlalchemy_utils


# revision identifiers, used by Alembic.
revision: str = '0b06b91ea746'
down_revision: Union[str, None] = '2661dad3cb75'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('lpus',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('client_id', sa.BigInteger(), nullable=True, comment='Идентификатор записи в системе клиента'),
    sa.Column('name', sa.String(length=200), nullable=False, comment='Наименование ЛПУ'),
    sa.Column('description', sa.Text(), nullable=True, comment='Описание ЛПУ'),
    sa.Column('start_date', sa.DateTime(), nullable=True, comment='Дата и время начала использования'),
    sa.Column('end_date', sa.DateTime(), nullable=True, comment='Дата и время окончания использования'),
    sa.Column('is_active', sa.Boolean(), nullable=True, comment='Флаг активно/неактивно'),
    sa.PrimaryKeyConstraint('id'),
    comment='Таблица "Лечебныо-профилактические учреждения"'
    )
    op.create_index(op.f('ix_lpus_id'), 'lpus', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_lpus_id'), table_name='lpus')
    op.drop_table('lpus')
    # ### end Alembic commands ###
