"""Service age fields was added

Revision ID: 0cbb40e09730
Revises: eb8f8a1ed501
Create Date: 2023-10-25 13:28:40.290744

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlalchemy_utils


# revision identifiers, used by Alembic.
revision: str = '0cbb40e09730'
down_revision: Union[str, None] = 'eb8f8a1ed501'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('services', sa.Column('minimal_age', sa.Integer(), nullable=False, comment='Минимальный возрас оказания услуги'))
    op.add_column('services', sa.Column('maximal_age', sa.Integer(), nullable=False, comment='Максимальный возрас оказания услуги'))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('services', 'maximal_age')
    op.drop_column('services', 'minimal_age')
    # ### end Alembic commands ###
