"""new field has been added to access_tickets_lists!

Revision ID: 0f9cb5c12c95
Revises: f7fd01e45270
Create Date: 2024-01-31 13:16:50.919449

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlalchemy_utils


# revision identifiers, used by Alembic.
revision: str = '0f9cb5c12c95'
down_revision: Union[str, None] = 'f7fd01e45270'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('access_tickets_lists', sa.Column('user_client_id', sa.BigInteger(), nullable=True, comment='Идентификатор карточки пользователя в системе клиента'))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('access_tickets_lists', 'user_client_id')
    # ### end Alembic commands ###
