"""Removed not needed tables!

Revision ID: 12595e5ad882
Revises: 64cfe853b6aa
Create Date: 2023-11-16 15:05:56.624743

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlalchemy_utils


# revision identifiers, used by Alembic.
revision: str = '12595e5ad882'
down_revision: Union[str, None] = '64cfe853b6aa'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('services_service_direction_id_fkey', 'services', type_='foreignkey')
    op.drop_column('services', 'service_direction_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('services', sa.Column('service_direction_id', sa.INTEGER(), autoincrement=False, nullable=False, comment='Идентификатор направления услуги'))
    op.create_foreign_key('services_service_direction_id_fkey', 'services', 'services_directions', ['service_direction_id'], ['id'])
    # ### end Alembic commands ###
