"""Accounts' tables go to BigInteger for client_id!

Revision ID: 12f3bd25925b
Revises: 4aa319cfa87a
Create Date: 2023-12-21 10:08:13.369679

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlalchemy_utils


# revision identifiers, used by Alembic.
revision: str = '12f3bd25925b'
down_revision: Union[str, None] = '4aa319cfa87a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('address_mis_kladr', 'client_id',
               existing_type=sa.INTEGER(),
               type_=sa.BigInteger(),
               existing_comment='Идентификатор записи в таблице ADDRS в системе клиента',
               existing_nullable=True)
    op.alter_column('address_mis_kladr', 'client_user_id',
               existing_type=sa.INTEGER(),
               type_=sa.BigInteger(),
               existing_comment='Идентификатор пользователя в системе клиента',
               existing_nullable=True)
    op.alter_column('cities', 'client_id',
               existing_type=sa.INTEGER(),
               type_=sa.BigInteger(),
               existing_comment='Идентификатор города в системе клиента',
               existing_nullable=True)
    op.alter_column('information_ways', 'client_id',
               existing_type=sa.INTEGER(),
               type_=sa.BigInteger(),
               existing_comment='Идентификатор канала поступления информации в системе клиента',
               existing_nullable=True)
    op.alter_column('medical_centers', 'client_id',
               existing_type=sa.INTEGER(),
               type_=sa.BigInteger(),
               existing_comment='Идентификатор медицинского центра в системе клиента',
               existing_nullable=True)
    op.alter_column('notifications_ways', 'client_id',
               existing_type=sa.INTEGER(),
               type_=sa.BigInteger(),
               existing_comment='Идентификатор канала рассылки уведомлений в системе клиента',
               existing_nullable=True)
    op.alter_column('relationship_degreeses', 'client_id',
               existing_type=sa.INTEGER(),
               type_=sa.BigInteger(),
               existing_comment='Идентификатор степени родства в системе клиента',
               existing_nullable=True)
    op.alter_column('users_notifications_ways', 'client_id',
               existing_type=sa.INTEGER(),
               type_=sa.BigInteger(),
               existing_comment='Идентификатор канала рассылки уведомлений в системе клиента',
               existing_nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('users_notifications_ways', 'client_id',
               existing_type=sa.BigInteger(),
               type_=sa.INTEGER(),
               existing_comment='Идентификатор канала рассылки уведомлений в системе клиента',
               existing_nullable=True)
    op.alter_column('relationship_degreeses', 'client_id',
               existing_type=sa.BigInteger(),
               type_=sa.INTEGER(),
               existing_comment='Идентификатор степени родства в системе клиента',
               existing_nullable=True)
    op.alter_column('notifications_ways', 'client_id',
               existing_type=sa.BigInteger(),
               type_=sa.INTEGER(),
               existing_comment='Идентификатор канала рассылки уведомлений в системе клиента',
               existing_nullable=True)
    op.alter_column('medical_centers', 'client_id',
               existing_type=sa.BigInteger(),
               type_=sa.INTEGER(),
               existing_comment='Идентификатор медицинского центра в системе клиента',
               existing_nullable=True)
    op.alter_column('information_ways', 'client_id',
               existing_type=sa.BigInteger(),
               type_=sa.INTEGER(),
               existing_comment='Идентификатор канала поступления информации в системе клиента',
               existing_nullable=True)
    op.alter_column('cities', 'client_id',
               existing_type=sa.BigInteger(),
               type_=sa.INTEGER(),
               existing_comment='Идентификатор города в системе клиента',
               existing_nullable=True)
    op.alter_column('address_mis_kladr', 'client_user_id',
               existing_type=sa.BigInteger(),
               type_=sa.INTEGER(),
               existing_comment='Идентификатор пользователя в системе клиента',
               existing_nullable=True)
    op.alter_column('address_mis_kladr', 'client_id',
               existing_type=sa.BigInteger(),
               type_=sa.INTEGER(),
               existing_comment='Идентификатор записи в таблице ADDRS в системе клиента',
               existing_nullable=True)
    # ### end Alembic commands ###
