"""Added unique property to name field

Revision ID: 16c086bffd99
Revises: 90a2aefa0aa0
Create Date: 2023-10-18 18:43:31.648368

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlalchemy_utils


# revision identifiers, used by Alembic.
revision: str = '16c086bffd99'
down_revision: Union[str, None] = '90a2aefa0aa0'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(None, 'cities', ['name'])
    op.create_unique_constraint(None, 'documents_types', ['name'])
    op.create_unique_constraint(None, 'medical_centers', ['name'])
    op.create_unique_constraint(None, 'medical_departments', ['name'])
    op.create_unique_constraint(None, 'medical_specialities', ['name'])
    op.create_unique_constraint(None, 'payments_systems', ['name'])
    op.create_unique_constraint(None, 'services', ['name'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'services', type_='unique')
    op.drop_constraint(None, 'payments_systems', type_='unique')
    op.drop_constraint(None, 'medical_specialities', type_='unique')
    op.drop_constraint(None, 'medical_departments', type_='unique')
    op.drop_constraint(None, 'medical_centers', type_='unique')
    op.drop_constraint(None, 'documents_types', type_='unique')
    op.drop_constraint(None, 'cities', type_='unique')
    # ### end Alembic commands ###
