"""ltree to string nas been done!

Revision ID: 16da279b3897
Revises: d8b3e4766513
Create Date: 2023-11-11 22:20:35.830190

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlalchemy_utils


# revision identifiers, used by Alembic.
revision: str = '16da279b3897'
down_revision: Union[str, None] = 'd8b3e4766513'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_nodes_path', table_name='nodes', postgresql_using='gist')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index('ix_nodes_path', 'nodes', ['path'], unique=False, postgresql_using='gist')
    # ### end Alembic commands ###
