"""First admin table has been added

Revision ID: 19a318f52ccf
Revises: fbe7656ef925
Create Date: 2023-12-13 16:18:31.780027

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlalchemy_utils


# revision identifiers, used by Alembic.
revision: str = '19a318f52ccf'
down_revision: Union[str, None] = 'fbe7656ef925'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users_admin',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('client_id', sa.Integer(), nullable=True, comment='Идентификатор записи в таблице администрирования в системе клиента'),
    sa.Column('user_id', sa.Integer(), nullable=True, comment='Идентификатор пользователя'),
    sa.Column('registration_visible_fields', sa.String(), nullable=True, comment='Строка, содержащая через "," наименование отображаемых полей'),
    sa.Column('registration_required_fields', sa.String(), nullable=True, comment='Строка, содержащая через "," наименование обязательных полей'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id'),
    comment='Таблица администрирования таблицы users'
    )
    op.create_index(op.f('ix_users_admin_id'), 'users_admin', ['id'], unique=False)
    op.alter_column('admin_users', 'password',
               existing_type=sa.VARCHAR(length=50),
               type_=sa.String(length=200),
               existing_nullable=False)
    op.create_unique_constraint(None, 'admin_users', ['mobile'])
    op.alter_column('users', 'first_name',
               existing_type=sa.VARCHAR(length=100),
               nullable=True,
               existing_comment='Имя пользователя')
    op.alter_column('users', 'last_name',
               existing_type=sa.VARCHAR(length=100),
               nullable=True,
               existing_comment='Фамилия пользователя')
    op.alter_column('users', 'email',
               existing_type=sa.VARCHAR(length=200),
               nullable=True,
               existing_comment='Электронная почта пользователя')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('users', 'email',
               existing_type=sa.VARCHAR(length=200),
               nullable=False,
               existing_comment='Электронная почта пользователя')
    op.alter_column('users', 'last_name',
               existing_type=sa.VARCHAR(length=100),
               nullable=False,
               existing_comment='Фамилия пользователя')
    op.alter_column('users', 'first_name',
               existing_type=sa.VARCHAR(length=100),
               nullable=False,
               existing_comment='Имя пользователя')
    op.drop_constraint(None, 'admin_users', type_='unique')
    op.alter_column('admin_users', 'password',
               existing_type=sa.String(length=200),
               type_=sa.VARCHAR(length=50),
               existing_nullable=False)
    op.drop_index(op.f('ix_users_admin_id'), table_name='users_admin')
    op.drop_table('users_admin')
    # ### end Alembic commands ###
