"""shifrs_discounts has been changed

Revision ID: 1b141fcd362b
Revises: b1f7fd81416f
Create Date: 2024-01-22 10:09:49.093477

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlalchemy_utils


# revision identifiers, used by Alembic.
revision: str = '1b141fcd362b'
down_revision: Union[str, None] = 'b1f7fd81416f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('shifrs_discounts', 'service_group_id',
               existing_type=sa.INTEGER(),
               nullable=True,
               existing_comment='Идентификатор группы прейскуранта, если тэг = 2')
    op.alter_column('shifrs_discounts', 'service_id',
               existing_type=sa.INTEGER(),
               nullable=True,
               existing_comment='Идентификатор услуги, если тэг = 1')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('shifrs_discounts', 'service_id',
               existing_type=sa.INTEGER(),
               nullable=False,
               existing_comment='Идентификатор услуги, если тэг = 1')
    op.alter_column('shifrs_discounts', 'service_group_id',
               existing_type=sa.INTEGER(),
               nullable=False,
               existing_comment='Идентификатор группы прейскуранта, если тэг = 2')
    # ### end Alembic commands ###
