"""Removed unique parameter from service name field

Revision ID: 1d245c2a8f98
Revises: 0cbb40e09730
Create Date: 2023-10-25 15:30:23.804418

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlalchemy_utils


# revision identifiers, used by Alembic.
revision: str = '1d245c2a8f98'
down_revision: Union[str, None] = '0cbb40e09730'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('services_name_key', 'services', type_='unique')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint('services_name_key', 'services', ['name'])
    # ### end Alembic commands ###
