"""suscribe tables have been changed


Revision ID: 20687b537ec3
Revises: 675b40d61baa
Create Date: 2024-02-08 10:03:14.397116

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlalchemy_utils


# revision identifiers, used by Alembic.
revision: str = '20687b537ec3'
down_revision: Union[str, None] = '675b40d61baa'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('subscribes_services_packs', 'pack_type_id',
               existing_type=sa.INTEGER(),
               nullable=True,
               existing_comment='Идентификатор типа пакета услуг абонементов (на  дому или в МЦ)')
    op.alter_column('subscribes_spacks_records', 'service_id',
               existing_type=sa.INTEGER(),
               nullable=True,
               existing_comment='Идентификатор услуги')
    op.alter_column('subscribes_spacks_records', 'service_group_id',
               existing_type=sa.INTEGER(),
               nullable=True,
               existing_comment='Идентификатор группы прейскуранта')
    op.drop_column('subscribes_spacks_records', 'status')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('subscribes_spacks_records', sa.Column('status', sa.INTEGER(), autoincrement=False, nullable=False, comment='Статус'))
    op.alter_column('subscribes_spacks_records', 'service_group_id',
               existing_type=sa.INTEGER(),
               nullable=False,
               existing_comment='Идентификатор группы прейскуранта')
    op.alter_column('subscribes_spacks_records', 'service_id',
               existing_type=sa.INTEGER(),
               nullable=False,
               existing_comment='Идентификатор услуги')
    op.alter_column('subscribes_services_packs', 'pack_type_id',
               existing_type=sa.INTEGER(),
               nullable=False,
               existing_comment='Идентификатор типа пакета услуг абонементов (на  дому или в МЦ)')
    # ### end Alembic commands ###
