"""ltree to string has been done_5!

Revision ID: 21c502e8121a
Revises: 3ed6ccf58301
Create Date: 2023-11-11 23:14:11.375323

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlalchemy_utils


# revision identifiers, used by Alembic.
revision: str = '21c502e8121a'
down_revision: Union[str, None] = '3ed6ccf58301'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('nodes', sa.Column('path', sa.String(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('nodes', 'path')
    # ### end Alembic commands ###
