"""users_documents_requests has been added_4!

Revision ID: 23f2caba2395
Revises: c1558005e4a3
Create Date: 2024-04-13 21:46:24.509444

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlalchemy_utils


# revision identifiers, used by Alembic.
revision: str = '23f2caba2395'
down_revision: Union[str, None] = 'c1558005e4a3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users_documents_requests', sa.Column('payment_id', sa.Integer(), nullable=True, comment='Идентификатор платежа для платной услуги'))
    op.add_column('users_documents_requests', sa.Column('is_paid', sa.Boolean(), nullable=True, comment='Флаг оплачен/неоплачен для платной услуги'))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users_documents_requests', 'is_paid')
    op.drop_column('users_documents_requests', 'payment_id')
    # ### end Alembic commands ###
