"""The ServiceMspecialityTable has been added

Revision ID: 259fbb622a53
Revises: 9ed36975a9cf
Create Date: 2023-10-27 14:33:50.569287

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlalchemy_utils


# revision identifiers, used by Alembic.
revision: str = '259fbb622a53'
down_revision: Union[str, None] = '9ed36975a9cf'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('services_mspecialities',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('service_id', sa.Integer(), nullable=False, comment='Идентификатор услуги'),
    sa.Column('mspeciality_id', sa.Integer(), nullable=False, comment='Идентификатор медицинской специальности'),
    sa.Column('is_active', sa.Boolean(), nullable=True, comment='Флаг активна/не активна'),
    sa.ForeignKeyConstraint(['mspeciality_id'], ['medical_specialities.id'], ),
    sa.ForeignKeyConstraint(['service_id'], ['services.id'], ),
    sa.PrimaryKeyConstraint('id'),
    comment='Таблица связи услуг с медицинскими специальностями'
    )
    op.create_index(op.f('ix_services_mspecialities_id'), 'services_mspecialities', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_services_mspecialities_id'), table_name='services_mspecialities')
    op.drop_table('services_mspecialities')
    # ### end Alembic commands ###
