"""For department_id - nullable=True

Revision ID: 25f2d676599b
Revises: 1d245c2a8f98
Create Date: 2023-10-25 19:03:24.527290

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlalchemy_utils


# revision identifiers, used by Alembic.
revision: str = '25f2d676599b'
down_revision: Union[str, None] = '1d245c2a8f98'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table_comment(
        'docrors_mspecialities',
        'Таблица-справочник "Врачи со специальностями"',
        existing_comment='Таблица-справочник "Специальности врачей"',
        schema=None
    )
    op.alter_column('doctors', 'medical_department_id',
               existing_type=sa.INTEGER(),
               nullable=True,
               existing_comment='Идентификатор медицинского департемента')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('doctors', 'medical_department_id',
               existing_type=sa.INTEGER(),
               nullable=False,
               existing_comment='Идентификатор медицинского департемента')
    op.create_table_comment(
        'docrors_mspecialities',
        'Таблица-справочник "Специальности врачей"',
        existing_comment='Таблица-справочник "Врачи со специальностями"',
        schema=None
    )
    # ### end Alembic commands ###
