"""Added users_subscriptions and users_suscriptions_items tables

Revision ID: 2b28e8221cd8
Revises: 091c7927a951
Create Date: 2023-10-09 11:34:00.987917

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlalchemy_utils


# revision identifiers, used by Alembic.
revision: str = '2b28e8221cd8'
down_revision: Union[str, None] = '091c7927a951'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users_subscriptions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('client_subscription_id', sa.Integer(), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('is_paid', sa.Boolean(), nullable=True),
    sa.Column('price', sa.Float(), nullable=False),
    sa.Column('common_discount', sa.Integer(), nullable=True),
    sa.Column('paid_amount', sa.Float(), nullable=False),
    sa.Column('current_amount', sa.Float(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_subscriptions_id'), 'users_subscriptions', ['id'], unique=False)
    op.create_table('users_suscriptions_items',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_subscription_id', sa.Integer(), nullable=False, comment='Идентификатор подписки пользхователя'),
    sa.Column('service_id', sa.Integer(), nullable=False, comment='Идентификатор услуги'),
    sa.Column('price', sa.Float(), nullable=False, comment='Цена услуги'),
    sa.Column('discount', sa.Integer(), nullable=True, comment='Скидка на услугу'),
    sa.Column('amount', sa.Float(), nullable=False, comment='Итоговая сумма стоимости услуги'),
    sa.Column('is_paid', sa.Boolean(), nullable=True, comment='Флаг оплачена/не оплачена'),
    sa.Column('is_got', sa.Boolean(), nullable=True, comment='Флаг получена/не получена'),
    sa.Column('is_active', sa.Boolean(), nullable=True, comment='Флаг активности подписки - активная/не активная'),
    sa.ForeignKeyConstraint(['service_id'], ['services.id'], ),
    sa.ForeignKeyConstraint(['user_subscription_id'], ['users_subscriptions.id'], ),
    sa.PrimaryKeyConstraint('id'),
    comment='Таблица "Услуги в абонементе пользователя (состав абонемента пользователя)"'
    )
    op.create_index(op.f('ix_users_suscriptions_items_id'), 'users_suscriptions_items', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_users_suscriptions_items_id'), table_name='users_suscriptions_items')
    op.drop_table('users_suscriptions_items')
    op.drop_index(op.f('ix_users_subscriptions_id'), table_name='users_subscriptions')
    op.drop_table('users_subscriptions')
    # ### end Alembic commands ###
