"""Fixed typos_1!

Revision ID: 2e9bbfe071c2
Revises: aa0396ed3f9b
Create Date: 2023-11-21 15:05:58.611734

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlalchemy_utils


# revision identifiers, used by Alembic.
revision: str = '2e9bbfe071c2'
down_revision: Union[str, None] = 'aa0396ed3f9b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('financial_types', 'client_shifr_id',
               existing_type=sa.INTEGER(),
               nullable=True,
               existing_comment='Идентификатор финансового типа в системе клиента')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('financial_types', 'client_shifr_id',
               existing_type=sa.INTEGER(),
               nullable=False,
               existing_comment='Идентификатор финансового типа в системе клиента')
    # ### end Alembic commands ###
