"""Changing some parameters has been done!

Revision ID: 2f690ea196ea
Revises: 42becdaaa9ce
Create Date: 2023-12-06 14:55:10.002301

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlalchemy_utils


# revision identifiers, used by Alembic.
revision: str = '2f690ea196ea'
down_revision: Union[str, None] = '42becdaaa9ce'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users_services_carts', sa.Column('shifr_id', sa.Integer(), nullable=True, comment='Идентификатор шифра'))
    op.add_column('users_services_carts', sa.Column('access_ticket_id', sa.Integer(), nullable=True, comment='Идентификатор номерка'))
    op.create_foreign_key(None, 'users_services_carts', 'access_tickets', ['access_ticket_id'], ['id'])
    op.create_foreign_key(None, 'users_services_carts', 'shifrs', ['shifr_id'], ['id'])
    op.add_column('users_services_plans', sa.Column('shifr_id', sa.Integer(), nullable=True, comment='Идентификатор шифра'))
    op.create_foreign_key(None, 'users_services_plans', 'shifrs', ['shifr_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'users_services_plans', type_='foreignkey')
    op.drop_column('users_services_plans', 'shifr_id')
    op.drop_constraint(None, 'users_services_carts', type_='foreignkey')
    op.drop_constraint(None, 'users_services_carts', type_='foreignkey')
    op.drop_column('users_services_carts', 'access_ticket_id')
    op.drop_column('users_services_carts', 'shifr_id')
    # ### end Alembic commands ###
