"""policies table has been changed!

Revision ID: 30b84ff72f9d
Revises: b190fb38d63d
Create Date: 2024-01-29 09:59:06.644832

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlalchemy_utils
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '30b84ff72f9d'
down_revision: Union[str, None] = 'b190fb38d63d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('policies', 'start_date',
               existing_type=postgresql.TIMESTAMP(),
               nullable=True,
               existing_comment='Начальная дата периода действия полиса')
    op.alter_column('policies', 'end_date',
               existing_type=postgresql.TIMESTAMP(),
               nullable=True,
               existing_comment='Конечная дата периода действия полиса')
    op.alter_column('policies', 'contract_date',
               existing_type=postgresql.TIMESTAMP(),
               nullable=True,
               existing_comment='Дата выдачи полиса')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('policies', 'contract_date',
               existing_type=postgresql.TIMESTAMP(),
               nullable=False,
               existing_comment='Дата выдачи полиса')
    op.alter_column('policies', 'end_date',
               existing_type=postgresql.TIMESTAMP(),
               nullable=False,
               existing_comment='Конечная дата периода действия полиса')
    op.alter_column('policies', 'start_date',
               existing_type=postgresql.TIMESTAMP(),
               nullable=False,
               existing_comment='Начальная дата периода действия полиса')
    # ### end Alembic commands ###
