"""Added schedules and comments. IT's ok

Revision ID: 3100c4fa4c9b
Revises: 2b28e8221cd8
Create Date: 2023-10-09 15:32:39.612363

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlalchemy_utils


# revision identifiers, used by Alembic.
revision: str = '3100c4fa4c9b'
down_revision: Union[str, None] = '2b28e8221cd8'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('payments_systems',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False, comment='Наименование платежной системы'),
    sa.Column('description', sa.Text(), nullable=True, comment='Описание платежной системы'),
    sa.Column('is_active', sa.Boolean(), nullable=True, comment='Флаг активан/не активна'),
    sa.PrimaryKeyConstraint('id'),
    comment='Таблица "Платёжные системы"'
    )
    op.create_index(op.f('ix_payments_systems_id'), 'payments_systems', ['id'], unique=False)
    op.create_table('doctors_schedulers',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('doctor_id', sa.Integer(), nullable=False, comment='Идентификатор доктора'),
    sa.Column('plan_visit_time', sa.DateTime(), nullable=True, comment='Плановые дата и время получения услуги'),
    sa.Column('paln_visit_duration', sa.Integer(), nullable=False, comment='Плановая длительность оказания услуги в минутах'),
    sa.Column('description', sa.Text(), nullable=True, comment='Описание платежной системы'),
    sa.Column('is_available', sa.Boolean(), nullable=True, comment='Флаг доступен/недоступен'),
    sa.ForeignKeyConstraint(['doctor_id'], ['doctors.id'], ),
    sa.PrimaryKeyConstraint('id'),
    comment='Таблица "Расписание доктора"'
    )
    op.create_index(op.f('ix_doctors_schedulers_id'), 'doctors_schedulers', ['id'], unique=False)
    op.create_table('users_carts',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False, comment='Идентификатор пользователя'),
    sa.Column('service_id', sa.Integer(), nullable=False, comment='Идентификатор услуги'),
    sa.Column('doctor_id', sa.Integer(), nullable=False),
    sa.Column('price', sa.Float(), nullable=False, comment='Цена услуги'),
    sa.Column('discount', sa.Integer(), nullable=True, comment='Скидка на услугу'),
    sa.Column('amount_to_pay', sa.Float(), nullable=False, comment='Итоговая стоимость услуги к оплате'),
    sa.Column('needed_datetime', sa.DateTime(), nullable=True, comment='Желаемые для пользователя дата и время получения услуги'),
    sa.ForeignKeyConstraint(['doctor_id'], ['doctors.id'], ),
    sa.ForeignKeyConstraint(['service_id'], ['services.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    comment='Таблица "Корзина пользователя"'
    )
    op.create_index(op.f('ix_users_carts_id'), 'users_carts', ['id'], unique=False)
    op.create_table('users_payments',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('payment_system_id', sa.Integer(), nullable=False, comment='Идентификатор платежной системы'),
    sa.Column('user_id', sa.Integer(), nullable=False, comment='Идентификатор пользователя'),
    sa.Column('service_id', sa.Integer(), nullable=False, comment='Идентификатор услуги'),
    sa.Column('doctor_id', sa.Integer(), nullable=False),
    sa.Column('payment_date', sa.DateTime(), nullable=True),
    sa.Column('price', sa.Float(), nullable=False, comment='Цена услуги'),
    sa.Column('discount', sa.Integer(), nullable=True, comment='Скидка на услугу'),
    sa.Column('amount_to_pay', sa.Float(), nullable=False, comment='Итоговая стоимость услуги к оплате'),
    sa.Column('payment_amount', sa.Float(), nullable=False, comment='Оплаченная сумма'),
    sa.Column('payment_status', sa.Integer(), nullable=False, comment='Статус платежа'),
    sa.Column('payment_transaction_id', sa.Integer(), nullable=True, comment='Идентификатор платежя в платежной системе'),
    sa.ForeignKeyConstraint(['doctor_id'], ['doctors.id'], ),
    sa.ForeignKeyConstraint(['payment_system_id'], ['payments_systems.id'], ),
    sa.ForeignKeyConstraint(['service_id'], ['services.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    comment='Таблица "Платежи пользователя"'
    )
    op.create_index(op.f('ix_users_payments_id'), 'users_payments', ['id'], unique=False)
    op.create_table('users_schedules',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('client_rnumb_id', sa.Integer(), nullable=True, comment='Идентификатор выданного пользователю номерка в системе Клиента'),
    sa.Column('plan_visit_time', sa.DateTime(), nullable=True, comment='Плановые дата и время получения услуги'),
    sa.Column('paln_visit_duration', sa.Integer(), nullable=False, comment='Плановая длительность оказания услуги в минутах'),
    sa.Column('user_id', sa.Integer(), nullable=False, comment='Идентификатор пользователя'),
    sa.Column('service_id', sa.Integer(), nullable=False, comment='Идентификатор услуги'),
    sa.Column('doctor_id', sa.Integer(), nullable=False, comment='Идентификатор доктора'),
    sa.Column('payment_id', sa.Integer(), nullable=True, comment='Идентификатор платежя'),
    sa.Column('subscription_id', sa.Integer(), nullable=True, comment='Идентификатор абонемента пользователя'),
    sa.Column('user_comments', sa.Text(), nullable=True, comment='Комментарий пользователя (ремемба)'),
    sa.Column('visit_was_done', sa.Boolean(), nullable=True, comment='Флаг услуги получена/не получена'),
    sa.Column('is_active', sa.Boolean(), nullable=True, comment='Флаг активен/не активен'),
    sa.ForeignKeyConstraint(['doctor_id'], ['doctors.id'], ),
    sa.ForeignKeyConstraint(['payment_id'], ['users_payments.id'], ),
    sa.ForeignKeyConstraint(['service_id'], ['services.id'], ),
    sa.ForeignKeyConstraint(['subscription_id'], ['users_subscriptions.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    comment='Таблица "Расписание посещений пользователя (пациента)"'
    )
    op.create_index(op.f('ix_users_schedules_id'), 'users_schedules', ['id'], unique=False)
    op.alter_column('cities', 'client_city_id',
               existing_type=sa.INTEGER(),
               comment='Идентификатор города в системе клиента',
               existing_nullable=True)
    op.alter_column('cities', 'name',
               existing_type=sa.VARCHAR(length=200),
               comment='Наименование города',
               existing_nullable=False)
    op.alter_column('cities', 'is_active',
               existing_type=sa.BOOLEAN(),
               comment='Флаг активный/не активный',
               existing_nullable=True)
    op.create_table_comment(
        'cities',
        'Таблица-справочник "Города"',
        existing_comment=None,
        schema=None
    )
    op.alter_column('doctors', 'client_doctor_id',
               existing_type=sa.INTEGER(),
               comment='Идентификатор доктора в системе клиента',
               existing_nullable=True)
    op.alter_column('doctors', 'medical_center_id',
               existing_type=sa.INTEGER(),
               comment='Идентификатор медицинского центра',
               existing_nullable=False)
    op.alter_column('doctors', 'medical_department_id',
               existing_type=sa.INTEGER(),
               comment='Идентификатор медицинского департемента',
               existing_nullable=False)
    op.alter_column('doctors', 'fio',
               existing_type=sa.VARCHAR(length=300),
               comment='ФИО доктора',
               existing_nullable=False)
    op.alter_column('doctors', 'description',
               existing_type=sa.TEXT(),
               comment='Описание доктора',
               existing_nullable=True)
    op.alter_column('doctors', 'photo',
               existing_type=sa.VARCHAR(length=100),
               comment='Фотография доктора',
               existing_nullable=True)
    op.alter_column('doctors', 'is_active',
               existing_type=sa.BOOLEAN(),
               comment='Флаг активен/не активен',
               existing_nullable=True)
    op.create_table_comment(
        'doctors',
        'Таблица-справочник "Врачи"',
        existing_comment=None,
        schema=None
    )
    op.alter_column('doctors_services', 'doctor_id',
               existing_type=sa.INTEGER(),
               comment='Идентификатор доктора',
               existing_nullable=False)
    op.alter_column('doctors_services', 'service_id',
               existing_type=sa.INTEGER(),
               comment='Идентификатор услуги',
               existing_nullable=False)
    op.alter_column('doctors_services', 'is_active',
               existing_type=sa.BOOLEAN(),
               comment='Флаг активна/не активна',
               existing_nullable=True)
    op.create_table_comment(
        'doctors_services',
        'Таблица-справочник "Услуги, оказываемые врачами"',
        existing_comment=None,
        schema=None
    )
    op.alter_column('mcenters_mdepartments', 'medical_center_id',
               existing_type=sa.INTEGER(),
               comment='Идентификатор медицинского центра',
               existing_nullable=False)
    op.alter_column('mcenters_mdepartments', 'medical_department_id',
               existing_type=sa.INTEGER(),
               comment='Идентификатор медицинского депртамент',
               existing_nullable=False)
    op.alter_column('mcenters_mdepartments', 'description',
               existing_type=sa.TEXT(),
               comment='Описание конкретного департамента в конкретном медицинском центре',
               existing_nullable=True)
    op.alter_column('mcenters_mdepartments', 'is_active',
               existing_type=sa.BOOLEAN(),
               comment='Флаг активен/не активен',
               existing_nullable=True)
    op.create_table_comment(
        'mcenters_mdepartments',
        'Таблица-справочник "Департаменты медицинских центров"',
        existing_comment=None,
        schema=None
    )
    op.alter_column('medical_centers', 'client_mcenter_id',
               existing_type=sa.INTEGER(),
               comment='Идентификатор медицинского центра в системе клиента',
               existing_nullable=True)
    op.alter_column('medical_centers', 'city_id',
               existing_type=sa.INTEGER(),
               comment='Идентификатор города',
               existing_nullable=False)
    op.alter_column('medical_centers', 'name',
               existing_type=sa.VARCHAR(length=200),
               comment='Наименование медицинского центра',
               existing_nullable=False)
    op.alter_column('medical_centers', 'address',
               existing_type=sa.VARCHAR(length=200),
               comment='Адрес медицинского центра',
               existing_nullable=False)
    op.alter_column('medical_centers', 'longitude',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               comment='Долгота в градусах',
               existing_nullable=True)
    op.alter_column('medical_centers', 'latitude',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               comment='Широта в градусах',
               existing_nullable=True)
    op.alter_column('medical_centers', 'description',
               existing_type=sa.TEXT(),
               comment='Описание медицинского центра',
               existing_nullable=True)
    op.alter_column('medical_centers', 'inn',
               existing_type=sa.VARCHAR(length=20),
               comment='ИНН (индивидуальный номер налогоплательщика)',
               existing_nullable=False)
    op.alter_column('medical_centers', 'bank_bic',
               existing_type=sa.VARCHAR(length=20),
               comment='БИК банка',
               existing_nullable=False)
    op.alter_column('medical_centers', 'settlement_account',
               existing_type=sa.VARCHAR(length=40),
               comment='Расчетный счет медитцинского центра',
               existing_nullable=False)
    op.alter_column('medical_centers', 'correspondent_account',
               existing_type=sa.VARCHAR(length=40),
               comment='Корреспондентский счет медицинского центра',
               existing_nullable=False)
    op.alter_column('medical_centers', 'kpp',
               existing_type=sa.VARCHAR(length=40),
               comment='Код КПП медицинского центра',
               existing_nullable=False)
    op.alter_column('medical_centers', 'is_active',
               existing_type=sa.BOOLEAN(),
               comment='Флаг активен/не активен',
               existing_nullable=True)
    op.create_table_comment(
        'medical_centers',
        'Таблица-справочник "Медицинские центры клиента"',
        existing_comment=None,
        schema=None
    )
    op.alter_column('medical_departments', 'client_department_id',
               existing_type=sa.INTEGER(),
               comment='Идентификатор департамента в системе клиента',
               existing_nullable=True)
    op.alter_column('medical_departments', 'name',
               existing_type=sa.VARCHAR(length=200),
               comment='Наименование департамента',
               existing_nullable=False)
    op.alter_column('medical_departments', 'description',
               existing_type=sa.TEXT(),
               comment='Описание департамента',
               existing_nullable=True)
    op.alter_column('medical_departments', 'is_active',
               existing_type=sa.BOOLEAN(),
               comment='Флаг активен/не активен',
               existing_nullable=True)
    op.create_table_comment(
        'medical_departments',
        'Таблица-справочник "Медицинские департаменты"',
        existing_comment=None,
        schema=None
    )
    op.alter_column('medical_specialities', 'client_doctor_speciality_id',
               existing_type=sa.INTEGER(),
               comment='Идентификатор специальности в системе клиента',
               existing_nullable=True)
    op.alter_column('medical_specialities', 'name',
               existing_type=sa.VARCHAR(length=200),
               comment='Наименование специальности',
               existing_nullable=False)
    op.alter_column('medical_specialities', 'description',
               existing_type=sa.TEXT(),
               comment='Описание специальности',
               existing_nullable=True)
    op.alter_column('medical_specialities', 'is_active',
               existing_type=sa.BOOLEAN(),
               comment='Флаг активна/не активна',
               existing_nullable=True)
    op.create_table_comment(
        'medical_specialities',
        'Таблица-справочник "Специальности врачей"',
        existing_comment=None,
        schema=None
    )
    op.alter_column('prices', 'client_price_id',
               existing_type=sa.INTEGER(),
               comment='Идентификатор записи в прайс-листе в системе Клиента',
               existing_nullable=True)
    op.alter_column('prices', 'service_id',
               existing_type=sa.INTEGER(),
               comment='Идентификатор услуги',
               existing_nullable=False)
    op.alter_column('prices', 'medical_center_id',
               existing_type=sa.INTEGER(),
               comment='Идентификатор медицинского центра',
               existing_nullable=False)
    op.alter_column('prices', 'medical_department_id',
               existing_type=sa.INTEGER(),
               comment='Идентификатор департамента',
               existing_nullable=False)
    op.alter_column('prices', 'price',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               comment='Цена услуги',
               existing_nullable=False)
    op.create_table_comment(
        'prices',
        'Таблица-справочник "Прайс-лист"',
        existing_comment=None,
        schema=None
    )
    op.alter_column('services', 'client_service_id',
               existing_type=sa.INTEGER(),
               comment='Идентификатор услуги в системе Клиента',
               existing_nullable=True)
    op.alter_column('services', 'service_direction_id',
               existing_type=sa.INTEGER(),
               comment='Идентификатор направления услуги',
               existing_nullable=False)
    op.alter_column('services', 'service_type_id',
               existing_type=sa.INTEGER(),
               comment='Идентификатор типа услуги',
               existing_nullable=False)
    op.alter_column('services', 'name',
               existing_type=sa.VARCHAR(length=100),
               comment='Наименование услуги',
               existing_nullable=False)
    op.alter_column('services', 'description',
               existing_type=sa.TEXT(),
               comment='Описание услуги',
               existing_nullable=True)
    op.alter_column('services', 'is_active',
               existing_type=sa.BOOLEAN(),
               comment='Флаг активна/не активна',
               existing_nullable=True)
    op.create_table_comment(
        'services',
        'Таблица-справочник "Услуги"',
        existing_comment=None,
        schema=None
    )
    op.alter_column('services_directions', 'client_sdirection_id',
               existing_type=sa.INTEGER(),
               comment='Идентификатор направления услуг в системе клиента',
               existing_nullable=True)
    op.alter_column('services_directions', 'name',
               existing_type=sa.VARCHAR(length=100),
               comment='Наименование направления услуги',
               existing_nullable=False)
    op.alter_column('services_directions', 'description',
               existing_type=sa.TEXT(),
               comment='Описание направления услуги',
               existing_nullable=True)
    op.alter_column('services_directions', 'is_active',
               existing_type=sa.BOOLEAN(),
               comment='Флаг активно/неактивно',
               existing_nullable=True)
    op.create_table_comment(
        'services_directions',
        'Таблица-спреавочник "Направления услуг"',
        existing_comment=None,
        schema=None
    )
    op.alter_column('services_types', 'client_stype_id',
               existing_type=sa.INTEGER(),
               comment='Идентификатор типа услуги на стороне клиента',
               existing_nullable=True)
    op.alter_column('services_types', 'name',
               existing_type=sa.VARCHAR(length=100),
               comment='Наименование типа услуг',
               existing_nullable=False)
    op.alter_column('services_types', 'description',
               existing_type=sa.TEXT(),
               comment='Описание типа.',
               existing_nullable=True)
    op.alter_column('services_types', 'is_active',
               existing_type=sa.BOOLEAN(),
               comment='Флаг активна/не активна',
               existing_nullable=True)
    op.create_table_comment(
        'services_types',
        'Таблица-справочник "Типы услуг"',
        existing_comment=None,
        schema=None
    )
    op.add_column('users_subscriptions', sa.Column('amount', sa.Float(), nullable=False, comment='Итоговая стоимость абонемента'))
    op.alter_column('users_subscriptions', 'client_subscription_id',
               existing_type=sa.INTEGER(),
               comment='Идентификатор абонемента пользователя в системе Клиента',
               existing_nullable=True)
    op.alter_column('users_subscriptions', 'user_id',
               existing_type=sa.INTEGER(),
               comment='Идентификатор пользователя',
               existing_nullable=False)
    op.alter_column('users_subscriptions', 'description',
               existing_type=sa.TEXT(),
               comment='Описание',
               existing_nullable=True)
    op.alter_column('users_subscriptions', 'is_paid',
               existing_type=sa.BOOLEAN(),
               comment='Флаг оплачен/не оплачен',
               existing_nullable=True)
    op.alter_column('users_subscriptions', 'price',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               comment='Цена абонемента',
               existing_nullable=False)
    op.alter_column('users_subscriptions', 'common_discount',
               existing_type=sa.INTEGER(),
               comment='Общая скидка на абонемент',
               existing_nullable=True)
    op.alter_column('users_subscriptions', 'paid_amount',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               comment='Опламенная сумма абонемента',
               existing_nullable=False)
    op.alter_column('users_subscriptions', 'current_amount',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               comment='Текущая неоплаченная сумма абонемента',
               existing_nullable=False)
    op.alter_column('users_subscriptions', 'is_active',
               existing_type=sa.BOOLEAN(),
               comment='Флаг активности абонемента - активный/не активный',
               existing_nullable=True)
    op.create_table_comment(
        'users_subscriptions',
        'Таблица "Абонементы пользователя"',
        existing_comment=None,
        schema=None
    )
    op.alter_column('users_suscriptions_items', 'user_subscription_id',
               existing_type=sa.INTEGER(),
               comment='Идентификатор подписки пользователя',
               existing_comment='Идентификатор подписки пользхователя',
               existing_nullable=False)
    op.alter_column('users_suscriptions_items', 'amount',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               comment='Итоговая стоимость услуги',
               existing_comment='Итоговая сумма стоимости услуги',
               existing_nullable=False)
    op.alter_column('users_suscriptions_items', 'is_active',
               existing_type=sa.BOOLEAN(),
               comment='Флаг активности услуги - активная/не активная',
               existing_comment='Флаг активности подписки - активная/не активная',
               existing_nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('users_suscriptions_items', 'is_active',
               existing_type=sa.BOOLEAN(),
               comment='Флаг активности подписки - активная/не активная',
               existing_comment='Флаг активности услуги - активная/не активная',
               existing_nullable=True)
    op.alter_column('users_suscriptions_items', 'amount',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               comment='Итоговая сумма стоимости услуги',
               existing_comment='Итоговая стоимость услуги',
               existing_nullable=False)
    op.alter_column('users_suscriptions_items', 'user_subscription_id',
               existing_type=sa.INTEGER(),
               comment='Идентификатор подписки пользхователя',
               existing_comment='Идентификатор подписки пользователя',
               existing_nullable=False)
    op.drop_table_comment(
        'users_subscriptions',
        existing_comment='Таблица "Абонементы пользователя"',
        schema=None
    )
    op.alter_column('users_subscriptions', 'is_active',
               existing_type=sa.BOOLEAN(),
               comment=None,
               existing_comment='Флаг активности абонемента - активный/не активный',
               existing_nullable=True)
    op.alter_column('users_subscriptions', 'current_amount',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               comment=None,
               existing_comment='Текущая неоплаченная сумма абонемента',
               existing_nullable=False)
    op.alter_column('users_subscriptions', 'paid_amount',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               comment=None,
               existing_comment='Опламенная сумма абонемента',
               existing_nullable=False)
    op.alter_column('users_subscriptions', 'common_discount',
               existing_type=sa.INTEGER(),
               comment=None,
               existing_comment='Общая скидка на абонемент',
               existing_nullable=True)
    op.alter_column('users_subscriptions', 'price',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               comment=None,
               existing_comment='Цена абонемента',
               existing_nullable=False)
    op.alter_column('users_subscriptions', 'is_paid',
               existing_type=sa.BOOLEAN(),
               comment=None,
               existing_comment='Флаг оплачен/не оплачен',
               existing_nullable=True)
    op.alter_column('users_subscriptions', 'description',
               existing_type=sa.TEXT(),
               comment=None,
               existing_comment='Описание',
               existing_nullable=True)
    op.alter_column('users_subscriptions', 'user_id',
               existing_type=sa.INTEGER(),
               comment=None,
               existing_comment='Идентификатор пользователя',
               existing_nullable=False)
    op.alter_column('users_subscriptions', 'client_subscription_id',
               existing_type=sa.INTEGER(),
               comment=None,
               existing_comment='Идентификатор абонемента пользователя в системе Клиента',
               existing_nullable=True)
    op.drop_column('users_subscriptions', 'amount')
    op.drop_table_comment(
        'services_types',
        existing_comment='Таблица-справочник "Типы услуг"',
        schema=None
    )
    op.alter_column('services_types', 'is_active',
               existing_type=sa.BOOLEAN(),
               comment=None,
               existing_comment='Флаг активна/не активна',
               existing_nullable=True)
    op.alter_column('services_types', 'description',
               existing_type=sa.TEXT(),
               comment=None,
               existing_comment='Описание типа.',
               existing_nullable=True)
    op.alter_column('services_types', 'name',
               existing_type=sa.VARCHAR(length=100),
               comment=None,
               existing_comment='Наименование типа услуг',
               existing_nullable=False)
    op.alter_column('services_types', 'client_stype_id',
               existing_type=sa.INTEGER(),
               comment=None,
               existing_comment='Идентификатор типа услуги на стороне клиента',
               existing_nullable=True)
    op.drop_table_comment(
        'services_directions',
        existing_comment='Таблица-спреавочник "Направления услуг"',
        schema=None
    )
    op.alter_column('services_directions', 'is_active',
               existing_type=sa.BOOLEAN(),
               comment=None,
               existing_comment='Флаг активно/неактивно',
               existing_nullable=True)
    op.alter_column('services_directions', 'description',
               existing_type=sa.TEXT(),
               comment=None,
               existing_comment='Описание направления услуги',
               existing_nullable=True)
    op.alter_column('services_directions', 'name',
               existing_type=sa.VARCHAR(length=100),
               comment=None,
               existing_comment='Наименование направления услуги',
               existing_nullable=False)
    op.alter_column('services_directions', 'client_sdirection_id',
               existing_type=sa.INTEGER(),
               comment=None,
               existing_comment='Идентификатор направления услуг в системе клиента',
               existing_nullable=True)
    op.drop_table_comment(
        'services',
        existing_comment='Таблица-справочник "Услуги"',
        schema=None
    )
    op.alter_column('services', 'is_active',
               existing_type=sa.BOOLEAN(),
               comment=None,
               existing_comment='Флаг активна/не активна',
               existing_nullable=True)
    op.alter_column('services', 'description',
               existing_type=sa.TEXT(),
               comment=None,
               existing_comment='Описание услуги',
               existing_nullable=True)
    op.alter_column('services', 'name',
               existing_type=sa.VARCHAR(length=100),
               comment=None,
               existing_comment='Наименование услуги',
               existing_nullable=False)
    op.alter_column('services', 'service_type_id',
               existing_type=sa.INTEGER(),
               comment=None,
               existing_comment='Идентификатор типа услуги',
               existing_nullable=False)
    op.alter_column('services', 'service_direction_id',
               existing_type=sa.INTEGER(),
               comment=None,
               existing_comment='Идентификатор направления услуги',
               existing_nullable=False)
    op.alter_column('services', 'client_service_id',
               existing_type=sa.INTEGER(),
               comment=None,
               existing_comment='Идентификатор услуги в системе Клиента',
               existing_nullable=True)
    op.drop_table_comment(
        'prices',
        existing_comment='Таблица-справочник "Прайс-лист"',
        schema=None
    )
    op.alter_column('prices', 'price',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               comment=None,
               existing_comment='Цена услуги',
               existing_nullable=False)
    op.alter_column('prices', 'medical_department_id',
               existing_type=sa.INTEGER(),
               comment=None,
               existing_comment='Идентификатор департамента',
               existing_nullable=False)
    op.alter_column('prices', 'medical_center_id',
               existing_type=sa.INTEGER(),
               comment=None,
               existing_comment='Идентификатор медицинского центра',
               existing_nullable=False)
    op.alter_column('prices', 'service_id',
               existing_type=sa.INTEGER(),
               comment=None,
               existing_comment='Идентификатор услуги',
               existing_nullable=False)
    op.alter_column('prices', 'client_price_id',
               existing_type=sa.INTEGER(),
               comment=None,
               existing_comment='Идентификатор записи в прайс-листе в системе Клиента',
               existing_nullable=True)
    op.drop_table_comment(
        'medical_specialities',
        existing_comment='Таблица-справочник "Специальности врачей"',
        schema=None
    )
    op.alter_column('medical_specialities', 'is_active',
               existing_type=sa.BOOLEAN(),
               comment=None,
               existing_comment='Флаг активна/не активна',
               existing_nullable=True)
    op.alter_column('medical_specialities', 'description',
               existing_type=sa.TEXT(),
               comment=None,
               existing_comment='Описание специальности',
               existing_nullable=True)
    op.alter_column('medical_specialities', 'name',
               existing_type=sa.VARCHAR(length=200),
               comment=None,
               existing_comment='Наименование специальности',
               existing_nullable=False)
    op.alter_column('medical_specialities', 'client_doctor_speciality_id',
               existing_type=sa.INTEGER(),
               comment=None,
               existing_comment='Идентификатор специальности в системе клиента',
               existing_nullable=True)
    op.drop_table_comment(
        'medical_departments',
        existing_comment='Таблица-справочник "Медицинские департаменты"',
        schema=None
    )
    op.alter_column('medical_departments', 'is_active',
               existing_type=sa.BOOLEAN(),
               comment=None,
               existing_comment='Флаг активен/не активен',
               existing_nullable=True)
    op.alter_column('medical_departments', 'description',
               existing_type=sa.TEXT(),
               comment=None,
               existing_comment='Описание департамента',
               existing_nullable=True)
    op.alter_column('medical_departments', 'name',
               existing_type=sa.VARCHAR(length=200),
               comment=None,
               existing_comment='Наименование департамента',
               existing_nullable=False)
    op.alter_column('medical_departments', 'client_department_id',
               existing_type=sa.INTEGER(),
               comment=None,
               existing_comment='Идентификатор департамента в системе клиента',
               existing_nullable=True)
    op.drop_table_comment(
        'medical_centers',
        existing_comment='Таблица-справочник "Медицинские центры клиента"',
        schema=None
    )
    op.alter_column('medical_centers', 'is_active',
               existing_type=sa.BOOLEAN(),
               comment=None,
               existing_comment='Флаг активен/не активен',
               existing_nullable=True)
    op.alter_column('medical_centers', 'kpp',
               existing_type=sa.VARCHAR(length=40),
               comment=None,
               existing_comment='Код КПП медицинского центра',
               existing_nullable=False)
    op.alter_column('medical_centers', 'correspondent_account',
               existing_type=sa.VARCHAR(length=40),
               comment=None,
               existing_comment='Корреспондентский счет медицинского центра',
               existing_nullable=False)
    op.alter_column('medical_centers', 'settlement_account',
               existing_type=sa.VARCHAR(length=40),
               comment=None,
               existing_comment='Расчетный счет медитцинского центра',
               existing_nullable=False)
    op.alter_column('medical_centers', 'bank_bic',
               existing_type=sa.VARCHAR(length=20),
               comment=None,
               existing_comment='БИК банка',
               existing_nullable=False)
    op.alter_column('medical_centers', 'inn',
               existing_type=sa.VARCHAR(length=20),
               comment=None,
               existing_comment='ИНН (индивидуальный номер налогоплательщика)',
               existing_nullable=False)
    op.alter_column('medical_centers', 'description',
               existing_type=sa.TEXT(),
               comment=None,
               existing_comment='Описание медицинского центра',
               existing_nullable=True)
    op.alter_column('medical_centers', 'latitude',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               comment=None,
               existing_comment='Широта в градусах',
               existing_nullable=True)
    op.alter_column('medical_centers', 'longitude',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               comment=None,
               existing_comment='Долгота в градусах',
               existing_nullable=True)
    op.alter_column('medical_centers', 'address',
               existing_type=sa.VARCHAR(length=200),
               comment=None,
               existing_comment='Адрес медицинского центра',
               existing_nullable=False)
    op.alter_column('medical_centers', 'name',
               existing_type=sa.VARCHAR(length=200),
               comment=None,
               existing_comment='Наименование медицинского центра',
               existing_nullable=False)
    op.alter_column('medical_centers', 'city_id',
               existing_type=sa.INTEGER(),
               comment=None,
               existing_comment='Идентификатор города',
               existing_nullable=False)
    op.alter_column('medical_centers', 'client_mcenter_id',
               existing_type=sa.INTEGER(),
               comment=None,
               existing_comment='Идентификатор медицинского центра в системе клиента',
               existing_nullable=True)
    op.drop_table_comment(
        'mcenters_mdepartments',
        existing_comment='Таблица-справочник "Департаменты медицинских центров"',
        schema=None
    )
    op.alter_column('mcenters_mdepartments', 'is_active',
               existing_type=sa.BOOLEAN(),
               comment=None,
               existing_comment='Флаг активен/не активен',
               existing_nullable=True)
    op.alter_column('mcenters_mdepartments', 'description',
               existing_type=sa.TEXT(),
               comment=None,
               existing_comment='Описание конкретного департамента в конкретном медицинском центре',
               existing_nullable=True)
    op.alter_column('mcenters_mdepartments', 'medical_department_id',
               existing_type=sa.INTEGER(),
               comment=None,
               existing_comment='Идентификатор медицинского депртамент',
               existing_nullable=False)
    op.alter_column('mcenters_mdepartments', 'medical_center_id',
               existing_type=sa.INTEGER(),
               comment=None,
               existing_comment='Идентификатор медицинского центра',
               existing_nullable=False)
    op.drop_table_comment(
        'doctors_services',
        existing_comment='Таблица-справочник "Услуги, оказываемые врачами"',
        schema=None
    )
    op.alter_column('doctors_services', 'is_active',
               existing_type=sa.BOOLEAN(),
               comment=None,
               existing_comment='Флаг активна/не активна',
               existing_nullable=True)
    op.alter_column('doctors_services', 'service_id',
               existing_type=sa.INTEGER(),
               comment=None,
               existing_comment='Идентификатор услуги',
               existing_nullable=False)
    op.alter_column('doctors_services', 'doctor_id',
               existing_type=sa.INTEGER(),
               comment=None,
               existing_comment='Идентификатор доктора',
               existing_nullable=False)
    op.drop_table_comment(
        'doctors',
        existing_comment='Таблица-справочник "Врачи"',
        schema=None
    )
    op.alter_column('doctors', 'is_active',
               existing_type=sa.BOOLEAN(),
               comment=None,
               existing_comment='Флаг активен/не активен',
               existing_nullable=True)
    op.alter_column('doctors', 'photo',
               existing_type=sa.VARCHAR(length=100),
               comment=None,
               existing_comment='Фотография доктора',
               existing_nullable=True)
    op.alter_column('doctors', 'description',
               existing_type=sa.TEXT(),
               comment=None,
               existing_comment='Описание доктора',
               existing_nullable=True)
    op.alter_column('doctors', 'fio',
               existing_type=sa.VARCHAR(length=300),
               comment=None,
               existing_comment='ФИО доктора',
               existing_nullable=False)
    op.alter_column('doctors', 'medical_department_id',
               existing_type=sa.INTEGER(),
               comment=None,
               existing_comment='Идентификатор медицинского департемента',
               existing_nullable=False)
    op.alter_column('doctors', 'medical_center_id',
               existing_type=sa.INTEGER(),
               comment=None,
               existing_comment='Идентификатор медицинского центра',
               existing_nullable=False)
    op.alter_column('doctors', 'client_doctor_id',
               existing_type=sa.INTEGER(),
               comment=None,
               existing_comment='Идентификатор доктора в системе клиента',
               existing_nullable=True)
    op.drop_table_comment(
        'cities',
        existing_comment='Таблица-справочник "Города"',
        schema=None
    )
    op.alter_column('cities', 'is_active',
               existing_type=sa.BOOLEAN(),
               comment=None,
               existing_comment='Флаг активный/не активный',
               existing_nullable=True)
    op.alter_column('cities', 'name',
               existing_type=sa.VARCHAR(length=200),
               comment=None,
               existing_comment='Наименование города',
               existing_nullable=False)
    op.alter_column('cities', 'client_city_id',
               existing_type=sa.INTEGER(),
               comment=None,
               existing_comment='Идентификатор города в системе клиента',
               existing_nullable=True)
    op.drop_index(op.f('ix_users_schedules_id'), table_name='users_schedules')
    op.drop_table('users_schedules')
    op.drop_index(op.f('ix_users_payments_id'), table_name='users_payments')
    op.drop_table('users_payments')
    op.drop_index(op.f('ix_users_carts_id'), table_name='users_carts')
    op.drop_table('users_carts')
    op.drop_index(op.f('ix_doctors_schedulers_id'), table_name='doctors_schedulers')
    op.drop_table('doctors_schedulers')
    op.drop_index(op.f('ix_payments_systems_id'), table_name='payments_systems')
    op.drop_table('payments_systems')
    # ### end Alembic commands ###
