"""users_documents_requests has been added!

Revision ID: 38673d7e828d
Revises: 4ccaa9887450
Create Date: 2024-04-13 20:47:57.187506

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlalchemy_utils


# revision identifiers, used by Alembic.
revision: str = '38673d7e828d'
down_revision: Union[str, None] = '4ccaa9887450'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users_documents_requests',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False, comment='Идентификатор пользователя'),
    sa.Column('user_service_cart_client_id', sa.String(), nullable=True, comment='Идентификатор услуги пользователя в системе клиента'),
    sa.Column('doc_client_id', sa.String(), nullable=True, comment='Идентификатор документа в системе клиента'),
    sa.Column('doc_params', sa.String(), nullable=True, comment='Параметры документа в виде json-строки'),
    sa.Column('is_requested', sa.Boolean(), nullable=True, comment='Флаг запрошен/незапрошен'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    comment='Таблица "Запросы документов пользователями"'
    )
    op.create_index(op.f('ix_users_documents_requests_id'), 'users_documents_requests', ['id'], unique=False)
    op.alter_column('users_services_carts', 'service_status',
               existing_type=sa.INTEGER(),
               comment='Статус услуги: 0 / 3 - назначена, 1 - выполнена, 2 - отменена',
               existing_comment='Статус услуги: 0 / 3 - назначена, 1 - выполнена, 2 - отменена, для service_group.client_id == 86137 : 100 - запрос на получение документа отправлен,',
               existing_nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('users_services_carts', 'service_status',
               existing_type=sa.INTEGER(),
               comment='Статус услуги: 0 / 3 - назначена, 1 - выполнена, 2 - отменена, для service_group.client_id == 86137 : 100 - запрос на получение документа отправлен,',
               existing_comment='Статус услуги: 0 / 3 - назначена, 1 - выполнена, 2 - отменена',
               existing_nullable=True)
    op.drop_index(op.f('ix_users_documents_requests_id'), table_name='users_documents_requests')
    op.drop_table('users_documents_requests')
    # ### end Alembic commands ###
