"""ltree to string has been done_4!

Revision ID: 3ed6ccf58301
Revises: d9d849924fb3
Create Date: 2023-11-11 23:13:27.481247

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlalchemy_utils


# revision identifiers, used by Alembic.
revision: str = '3ed6ccf58301'
down_revision: Union[str, None] = 'd9d849924fb3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('nodes', 'path')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('nodes', sa.Column('path', sqlalchemy_utils.types.ltree.LtreeType(), autoincrement=False, nullable=False))
    # ### end Alembic commands ###
