"""comment has been changed

Revision ID: 415a848dac8a
Revises: b1f7fd81416f
Create Date: 2024-01-23 11:49:48.940338

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlalchemy_utils


# revision identifiers, used by Alembic.
revision: str = '415a848dac8a'
down_revision: Union[str, None] = 'b1f7fd81416f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('users_payments', 'linked_user_payment_id',
               existing_type=sa.INTEGER(),
               comment='Идентификатор платежа пользователя для целей возврата',
               existing_comment='Идентификатор пользователя',
               existing_nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('users_payments', 'linked_user_payment_id',
               existing_type=sa.INTEGER(),
               comment='Идентификатор пользователя',
               existing_comment='Идентификатор платежа пользователя для целей возврата',
               existing_nullable=True)
    # ### end Alembic commands ###
