"""field quantity has been added!

Revision ID: 419e1a7795d3
Revises: a75f5544e180
Create Date: 2024-02-28 17:46:53.165817

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlalchemy_utils


# revision identifiers, used by Alembic.
revision: str = '419e1a7795d3'
down_revision: Union[str, None] = 'a75f5544e180'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('subscribes_services_packs', sa.Column('quantity', sa.Integer(), nullable=True, comment='Количество'))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('subscribes_services_packs', 'quantity')
    # ### end Alembic commands ###
