"""The mis_sort_field has been added into the relationship_degreeses table!

Revision ID: 4815760282b2
Revises: 64c1a7f00416
Create Date: 2024-05-18 18:42:32.459103

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlalchemy_utils


# revision identifiers, used by Alembic.
revision: str = '4815760282b2'
down_revision: Union[str, None] = '64c1a7f00416'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('relationship_degreeses', sa.Column('mis_sort_field', sa.Integer(), nullable=True, comment='Поле для сортировки на стороне МИС'))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('relationship_degreeses', 'mis_sort_field')
    # ### end Alembic commands ###
