"""The new table default_objects has been added

Revision ID: 488764cb5e97
Revises: 516fa2222920
Create Date: 2024-01-19 12:41:45.076216

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlalchemy_utils


# revision identifiers, used by Alembic.
revision: str = '488764cb5e97'
down_revision: Union[str, None] = '516fa2222920'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('default_objects',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True, comment='Идентификатор пользователя'),
    sa.Column('default_patient_id', sa.Integer(), nullable=True, comment='Идентификатор пациента по умолчанию'),
    sa.Column('default_medical_center_id', sa.Integer(), nullable=False, comment='Идентификатор медицинского центра по умолчанию'),
    sa.Column('default_doctor_mcenters_id', sa.Integer(), nullable=False, comment='Идентификатор доктора по умолчанию'),
    sa.ForeignKeyConstraint(['default_doctor_mcenters_id'], ['doctors_medical_centers.id'], ),
    sa.ForeignKeyConstraint(['default_medical_center_id'], ['medical_centers.id'], ),
    sa.ForeignKeyConstraint(['default_patient_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    comment='Таблица "Объекты по умолчанию"'
    )
    op.create_index(op.f('ix_default_objects_id'), 'default_objects', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_default_objects_id'), table_name='default_objects')
    op.drop_table('default_objects')
    # ### end Alembic commands ###
