"""client_id of users became BigInteger

Revision ID: 4aa319cfa87a
Revises: e34050ca8c80
Create Date: 2023-12-20 13:48:03.959233

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlalchemy_utils


# revision identifiers, used by Alembic.
revision: str = '4aa319cfa87a'
down_revision: Union[str, None] = 'e34050ca8c80'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('users', 'client_id',
               existing_type=sa.INTEGER(),
               type_=sa.BigInteger(),
               existing_comment='Идентификатор карточки пользователя в системе клиента',
               existing_nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('users', 'client_id',
               existing_type=sa.BigInteger(),
               type_=sa.INTEGER(),
               existing_comment='Идентификатор карточки пользователя в системе клиента',
               existing_nullable=True)
    # ### end Alembic commands ###
