"""Added fielda to medcenters table and comments to users table

Revision ID: 4c7397c43189
Revises: 16c086bffd99
Create Date: 2023-10-19 11:13:31.527842

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlalchemy_utils
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '4c7397c43189'
down_revision: Union[str, None] = '16c086bffd99'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('medical_centers', sa.Column('logo', sa.String(length=200), nullable=True, comment='Ссылка на логотип медцентра'))
    op.add_column('medical_centers', sa.Column('website_url', sa.String(length=200), nullable=True, comment='Ссылка на веб-сайт медцентра'))
    op.add_column('medical_centers', sa.Column('phone_fax', sa.String(length=25), nullable=False, comment='Основной телефон-факс медцентра'))
    op.add_column('medical_centers', sa.Column('dms_phone', sa.String(length=25), nullable=True, comment='Телефон для клиентов страховых компаний, имеющих полис ДМС'))
    op.add_column('medical_centers', sa.Column('work_time', sa.String(length=200), nullable=False, comment='Время работы медцентра'))
    op.add_column('medical_centers', sa.Column('collection_tests_time', sa.String(length=200), nullable=True, comment='Время забора анализов'))
    op.add_column('medical_centers', sa.Column('vaccination_time', sa.String(length=200), nullable=True, comment='Время забора анализов'))
    op.alter_column('users', 'client_user_id',
               existing_type=sa.INTEGER(),
               comment='Идентификатор пользователя в системе клиента',
               existing_nullable=True)
    op.alter_column('users', 'client_card_id',
               existing_type=sa.INTEGER(),
               comment='Идентификатор карточки пользователя в системе клиента',
               existing_nullable=True)
    op.alter_column('users', 'client_personal_area_id',
               existing_type=sa.INTEGER(),
               comment='Идентификатор личного кабинета в системе клиента',
               existing_nullable=True)
    op.alter_column('users', 'first_name',
               existing_type=sa.VARCHAR(length=100),
               comment='Имя пользователя',
               existing_nullable=True)
    op.alter_column('users', 'last_name',
               existing_type=sa.VARCHAR(length=100),
               comment='Фамилия пользователя',
               existing_nullable=True)
    op.alter_column('users', 'patronymic',
               existing_type=sa.VARCHAR(length=100),
               comment='Отчество пользователя (если есть)',
               existing_nullable=True)
    op.alter_column('users', 'birth_date',
               existing_type=sa.DATE(),
               comment='Дата рождения пользователя',
               existing_nullable=True)
    op.alter_column('users', 'gender',
               existing_type=sa.VARCHAR(length=1),
               comment='Пол пользователя',
               existing_nullable=True)
    op.alter_column('users', 'email',
               existing_type=sa.VARCHAR(length=100),
               comment='Электронная почта пользователя',
               existing_nullable=True)
    op.alter_column('users', 'phone_number',
               existing_type=sa.VARCHAR(length=25),
               comment='Номер телефона пользователя',
               existing_nullable=False)
    op.alter_column('users', 'additional_phone_number',
               existing_type=sa.VARCHAR(length=25),
               comment='Дополнительный номер телефона пользователя',
               existing_nullable=True)
    op.alter_column('users', 'password',
               existing_type=sa.VARCHAR(length=200),
               comment='Пароль для авторизации',
               existing_nullable=True)
    op.alter_column('users', 'is_active',
               existing_type=sa.BOOLEAN(),
               comment='Флаг активный/не активный',
               existing_nullable=True)
    op.alter_column('users', 'is_verified',
               existing_type=sa.BOOLEAN(),
               comment='Флаг телефон верифицирован/не верефицирован',
               existing_nullable=True)
    op.alter_column('users', 'created',
               existing_type=postgresql.TIMESTAMP(),
               comment='Дата создания записи пользователя',
               existing_nullable=True)
    op.alter_column('users', 'last_login',
               existing_type=postgresql.TIMESTAMP(),
               comment='Дата последнего входа пользователя в систему',
               existing_nullable=True)
    op.alter_column('users', 'last_visit',
               existing_type=postgresql.TIMESTAMP(),
               comment='Дата последнего визита пользователя в медцентр',
               existing_nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('users', 'last_visit',
               existing_type=postgresql.TIMESTAMP(),
               comment=None,
               existing_comment='Дата последнего визита пользователя в медцентр',
               existing_nullable=True)
    op.alter_column('users', 'last_login',
               existing_type=postgresql.TIMESTAMP(),
               comment=None,
               existing_comment='Дата последнего входа пользователя в систему',
               existing_nullable=True)
    op.alter_column('users', 'created',
               existing_type=postgresql.TIMESTAMP(),
               comment=None,
               existing_comment='Дата создания записи пользователя',
               existing_nullable=True)
    op.alter_column('users', 'is_verified',
               existing_type=sa.BOOLEAN(),
               comment=None,
               existing_comment='Флаг телефон верифицирован/не верефицирован',
               existing_nullable=True)
    op.alter_column('users', 'is_active',
               existing_type=sa.BOOLEAN(),
               comment=None,
               existing_comment='Флаг активный/не активный',
               existing_nullable=True)
    op.alter_column('users', 'password',
               existing_type=sa.VARCHAR(length=200),
               comment=None,
               existing_comment='Пароль для авторизации',
               existing_nullable=True)
    op.alter_column('users', 'additional_phone_number',
               existing_type=sa.VARCHAR(length=25),
               comment=None,
               existing_comment='Дополнительный номер телефона пользователя',
               existing_nullable=True)
    op.alter_column('users', 'phone_number',
               existing_type=sa.VARCHAR(length=25),
               comment=None,
               existing_comment='Номер телефона пользователя',
               existing_nullable=False)
    op.alter_column('users', 'email',
               existing_type=sa.VARCHAR(length=100),
               comment=None,
               existing_comment='Электронная почта пользователя',
               existing_nullable=True)
    op.alter_column('users', 'gender',
               existing_type=sa.VARCHAR(length=1),
               comment=None,
               existing_comment='Пол пользователя',
               existing_nullable=True)
    op.alter_column('users', 'birth_date',
               existing_type=sa.DATE(),
               comment=None,
               existing_comment='Дата рождения пользователя',
               existing_nullable=True)
    op.alter_column('users', 'patronymic',
               existing_type=sa.VARCHAR(length=100),
               comment=None,
               existing_comment='Отчество пользователя (если есть)',
               existing_nullable=True)
    op.alter_column('users', 'last_name',
               existing_type=sa.VARCHAR(length=100),
               comment=None,
               existing_comment='Фамилия пользователя',
               existing_nullable=True)
    op.alter_column('users', 'first_name',
               existing_type=sa.VARCHAR(length=100),
               comment=None,
               existing_comment='Имя пользователя',
               existing_nullable=True)
    op.alter_column('users', 'client_personal_area_id',
               existing_type=sa.INTEGER(),
               comment=None,
               existing_comment='Идентификатор личного кабинета в системе клиента',
               existing_nullable=True)
    op.alter_column('users', 'client_card_id',
               existing_type=sa.INTEGER(),
               comment=None,
               existing_comment='Идентификатор карточки пользователя в системе клиента',
               existing_nullable=True)
    op.alter_column('users', 'client_user_id',
               existing_type=sa.INTEGER(),
               comment=None,
               existing_comment='Идентификатор пользователя в системе клиента',
               existing_nullable=True)
    op.drop_column('medical_centers', 'vaccination_time')
    op.drop_column('medical_centers', 'collection_tests_time')
    op.drop_column('medical_centers', 'work_time')
    op.drop_column('medical_centers', 'dms_phone')
    op.drop_column('medical_centers', 'phone_fax')
    op.drop_column('medical_centers', 'website_url')
    op.drop_column('medical_centers', 'logo')
    # ### end Alembic commands ###
