"""Fixed typos_3!

Revision ID: 4c9b18e45661
Revises: a0940c183480
Create Date: 2023-11-21 16:28:34.619348

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlalchemy_utils


# revision identifiers, used by Alembic.
revision: str = '4c9b18e45661'
down_revision: Union[str, None] = 'a0940c183480'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('doctors_replacements', 'client_doctor_replacement_id',
               existing_type=sa.INTEGER(),
               nullable=True,
               existing_comment='Идентификатор записи подмены в системе клиента')
    op.alter_column('packs_types', 'client_pack_type_id',
               existing_type=sa.INTEGER(),
               nullable=True,
               existing_comment='Идентификатор типа пакета в системе клиента')
    op.alter_column('polices', 'client_police_id',
               existing_type=sa.INTEGER(),
               nullable=True,
               existing_comment='Идентификатор полиса в системе клиента')
    op.alter_column('shifrs', 'client_shifr_id',
               existing_type=sa.INTEGER(),
               nullable=True,
               existing_comment='Идентификатор шифра в системе клиента')
    op.alter_column('subscribes_doctors', 'client_suscribe_doctor_id',
               existing_type=sa.INTEGER(),
               nullable=True,
               existing_comment='Идентификатор доктра на абонементе в системе клиента')
    op.alter_column('subscribes_services_packs', 'client_subscribe_service_pack_id',
               existing_type=sa.INTEGER(),
               nullable=True,
               existing_comment='Идентификатор групп услуг аьонементов в системе клиента')
    op.alter_column('subscribes_spacks_records', 'client_subscribes_spacks_records_id',
               existing_type=sa.INTEGER(),
               nullable=True,
               existing_comment='Идентификатор записи пакета услуги абонемента в системе клиента')
    op.alter_column('users_subscribes', 'client_subscribe_id',
               existing_type=sa.INTEGER(),
               nullable=True,
               existing_comment='Идентификатор абонемента пользователя в системе клиента')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('users_subscribes', 'client_subscribe_id',
               existing_type=sa.INTEGER(),
               nullable=False,
               existing_comment='Идентификатор абонемента пользователя в системе клиента')
    op.alter_column('subscribes_spacks_records', 'client_subscribes_spacks_records_id',
               existing_type=sa.INTEGER(),
               nullable=False,
               existing_comment='Идентификатор записи пакета услуги абонемента в системе клиента')
    op.alter_column('subscribes_services_packs', 'client_subscribe_service_pack_id',
               existing_type=sa.INTEGER(),
               nullable=False,
               existing_comment='Идентификатор групп услуг аьонементов в системе клиента')
    op.alter_column('subscribes_doctors', 'client_suscribe_doctor_id',
               existing_type=sa.INTEGER(),
               nullable=False,
               existing_comment='Идентификатор доктра на абонементе в системе клиента')
    op.alter_column('shifrs', 'client_shifr_id',
               existing_type=sa.INTEGER(),
               nullable=False,
               existing_comment='Идентификатор шифра в системе клиента')
    op.alter_column('polices', 'client_police_id',
               existing_type=sa.INTEGER(),
               nullable=False,
               existing_comment='Идентификатор полиса в системе клиента')
    op.alter_column('packs_types', 'client_pack_type_id',
               existing_type=sa.INTEGER(),
               nullable=False,
               existing_comment='Идентификатор типа пакета в системе клиента')
    op.alter_column('doctors_replacements', 'client_doctor_replacement_id',
               existing_type=sa.INTEGER(),
               nullable=False,
               existing_comment='Идентификатор записи подмены в системе клиента')
    # ### end Alembic commands ###
