"""initpro_payments_receipts has been changed!

Revision ID: 4edaf3ccf611
Revises: 95af4aa31770
Create Date: 2024-04-05 13:29:55.607477

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlalchemy_utils


# revision identifiers, used by Alembic.
revision: str = '4edaf3ccf611'
down_revision: Union[str, None] = '95af4aa31770'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('initpro_payments_receipts', sa.Column('payment_id', sa.Integer(), nullable=False, comment='Идентификатор платежа в таблице users_payment'))
    op.add_column('initpro_payments_receipts', sa.Column('initpro_payment_object', sa.String(length=15), nullable=False, comment='Признак предмета расчёта в системе Инитпро'))
    op.drop_column('initpro_payments_receipts', 'paykeeper_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('initpro_payments_receipts', sa.Column('paykeeper_id', sa.INTEGER(), autoincrement=False, nullable=False, comment='Идентификатор подтвержденного в системе PayKeeper платежа'))
    op.drop_column('initpro_payments_receipts', 'initpro_payment_object')
    op.drop_column('initpro_payments_receipts', 'payment_id')
    # ### end Alembic commands ###
