"""changing nullable in the mcenters_price_names has been done!

Revision ID: 516fa2222920
Revises: 6a2144947e36
Create Date: 2024-01-19 10:21:21.030466

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlalchemy_utils


# revision identifiers, used by Alembic.
revision: str = '516fa2222920'
down_revision: Union[str, None] = '6a2144947e36'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('mcenters_price_names', 'medical_center_id',
               existing_type=sa.INTEGER(),
               nullable=True,
               existing_comment='Идентификатор медицинского центра')
    op.alter_column('mcenters_price_names', 'service_type_id',
               existing_type=sa.INTEGER(),
               nullable=True,
               existing_comment='Идентификатор типа услуги')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('mcenters_price_names', 'service_type_id',
               existing_type=sa.INTEGER(),
               nullable=False,
               existing_comment='Идентификатор типа услуги')
    op.alter_column('mcenters_price_names', 'medical_center_id',
               existing_type=sa.INTEGER(),
               nullable=False,
               existing_comment='Идентификатор медицинского центра')
    # ### end Alembic commands ###
