"""New fields have been added to services and document_requests!

Revision ID: 58a3a9d6133f
Revises: 4815760282b2
Create Date: 2024-05-21 00:32:23.364489

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlalchemy_utils


# revision identifiers, used by Alembic.
revision: str = '58a3a9d6133f'
down_revision: Union[str, None] = '4815760282b2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('services', sa.Column('is_plan_checking', sa.Boolean(), nullable=True, comment='Флаг проверять планируемые/не проверять планируемые'))
    op.add_column('services', sa.Column('checking_interval', sa.Integer(), nullable=True, comment='Интервал проверки +- checking_interval дней'))
    op.add_column('users_documents_requests', sa.Column('status_description', sa.String(), nullable=True, comment='Пояснение к статусу'))
    op.alter_column('users_documents_requests', 'status',
               existing_type=sa.INTEGER(),
               comment='Статус запроса: 0 - Новый / 1 - Отправлено оповещение сотруднику / 2 - Ожидает выдачи в МЦ / 3 - Выдан / 99 - Ошибка от МИС',
               existing_comment='Статус запроса: 0 - Новый / 1 - Отправлено оповещение сотруднику / 2 - Ожидает выдачи в МЦ / 3 - Выдан',
               existing_nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('users_documents_requests', 'status',
               existing_type=sa.INTEGER(),
               comment='Статус запроса: 0 - Новый / 1 - Отправлено оповещение сотруднику / 2 - Ожидает выдачи в МЦ / 3 - Выдан',
               existing_comment='Статус запроса: 0 - Новый / 1 - Отправлено оповещение сотруднику / 2 - Ожидает выдачи в МЦ / 3 - Выдан / 99 - Ошибка от МИС',
               existing_nullable=True)
    op.drop_column('users_documents_requests', 'status_description')
    op.drop_column('services', 'checking_interval')
    op.drop_column('services', 'is_plan_checking')
    # ### end Alembic commands ###
