"""The new table users_default_objects has been added_1

Revision ID: 59822a93fdd8
Revises: 02e44fd28f7c
Create Date: 2024-01-19 15:25:33.076318

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlalchemy_utils


# revision identifiers, used by Alembic.
revision: str = '59822a93fdd8'
down_revision: Union[str, None] = '02e44fd28f7c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('users_default_objects', 'user_id',
               existing_type=sa.INTEGER(),
               nullable=False,
               existing_comment='Идентификатор пользователя')
    op.alter_column('users_default_objects', 'default_patient_id',
               existing_type=sa.INTEGER(),
               nullable=False,
               existing_comment='Идентификатор пациента по умолчанию')
    op.alter_column('users_default_objects', 'default_medical_center_id',
               existing_type=sa.INTEGER(),
               nullable=True,
               existing_comment='Идентификатор медицинского центра по умолчанию')
    op.alter_column('users_default_objects', 'default_doctor_mcenters_id',
               existing_type=sa.INTEGER(),
               nullable=True,
               existing_comment='Идентификатор доктора по умолчанию')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('users_default_objects', 'default_doctor_mcenters_id',
               existing_type=sa.INTEGER(),
               nullable=False,
               existing_comment='Идентификатор доктора по умолчанию')
    op.alter_column('users_default_objects', 'default_medical_center_id',
               existing_type=sa.INTEGER(),
               nullable=False,
               existing_comment='Идентификатор медицинского центра по умолчанию')
    op.alter_column('users_default_objects', 'default_patient_id',
               existing_type=sa.INTEGER(),
               nullable=True,
               existing_comment='Идентификатор пациента по умолчанию')
    op.alter_column('users_default_objects', 'user_id',
               existing_type=sa.INTEGER(),
               nullable=True,
               existing_comment='Идентификатор пользователя')
    # ### end Alembic commands ###
