"""Renamed a field!

Revision ID: 5ac97af58dd4
Revises: b107c66d8a08
Create Date: 2023-12-04 10:29:02.431601

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlalchemy_utils


# revision identifiers, used by Alembic.
revision: str = '5ac97af58dd4'
down_revision: Union[str, None] = 'b107c66d8a08'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('address_mis_kladr_id', sa.Integer(), nullable=True, comment='Идентификатор адреса пользователя'))
    op.drop_column('users', 'client_address_mis_kladr_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('client_address_mis_kladr_id', sa.INTEGER(), autoincrement=False, nullable=True, comment='Идентификатор адреса пользователя в системе клиента'))
    op.drop_column('users', 'address_mis_kladr_id')
    # ### end Alembic commands ###
