"""ltree to string has been done_6!

Revision ID: 5c3e0127ad51
Revises: 21c502e8121a
Create Date: 2023-11-11 23:15:51.650757

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlalchemy_utils


# revision identifiers, used by Alembic.
revision: str = '5c3e0127ad51'
down_revision: Union[str, None] = '21c502e8121a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(op.f('ix_nodes_path'), 'nodes', ['path'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_nodes_path'), table_name='nodes')
    # ### end Alembic commands ###
