"""price_id has been added into users_services_carts!

Revision ID: 62f2acf50671
Revises: dae92e85f87f
Create Date: 2024-01-24 16:30:51.867136

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlalchemy_utils


# revision identifiers, used by Alembic.
revision: str = '62f2acf50671'
down_revision: Union[str, None] = 'dae92e85f87f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users_services_carts', sa.Column('price_id', sa.Integer(), nullable=False))
    op.create_foreign_key(None, 'users_services_carts', 'prices', ['price_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'users_services_carts', type_='foreignkey')
    op.drop_column('users_services_carts', 'price_id')
    # ### end Alembic commands ###
