"""corrected some tables

Revision ID: 6412f4dec8e1
Revises: b4709eb30263
Create Date: 2023-12-26 13:32:55.126803

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlalchemy_utils


# revision identifiers, used by Alembic.
revision: str = '6412f4dec8e1'
down_revision: Union[str, None] = 'b4709eb30263'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('access_tickets', 'status')
    op.add_column('services_mspecialities', sa.Column('client_id', sa.BigInteger(), nullable=True, comment='Идентификатор услуги в системе Клиента'))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('services_mspecialities', 'client_id')
    op.add_column('access_tickets', sa.Column('status', sa.BOOLEAN(), autoincrement=False, nullable=True, comment='Статус номерка'))
    # ### end Alembic commands ###
