"""Added client_id field to users_relatives

Revision ID: 645845f17640
Revises: 6412f4dec8e1
Create Date: 2023-12-27 15:37:08.050129

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlalchemy_utils


# revision identifiers, used by Alembic.
revision: str = '645845f17640'
down_revision: Union[str, None] = '6412f4dec8e1'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users_relatives', sa.Column('client_id', sa.BigInteger(), nullable=True, comment='Идентификатор степени родства в системе клиента'))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users_relatives', 'client_id')
    # ### end Alembic commands ###
