"""Removed not needed tables!

Revision ID: 64cfe853b6aa
Revises: 940ac4b55ed4
Create Date: 2023-11-16 14:56:28.656074

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlalchemy_utils


# revision identifiers, used by Alembic.
revision: str = '64cfe853b6aa'
down_revision: Union[str, None] = '940ac4b55ed4'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_prices_id', table_name='prices')
    op.drop_table('prices')
    op.drop_index('ix_services_mspecialities_id', table_name='services_mspecialities')
    op.drop_table('services_mspecialities')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('services_mspecialities',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('service_id', sa.INTEGER(), autoincrement=False, nullable=False, comment='Идентификатор услуги'),
    sa.Column('mspeciality_id', sa.INTEGER(), autoincrement=False, nullable=False, comment='Идентификатор медицинской специальности'),
    sa.Column('is_active', sa.BOOLEAN(), autoincrement=False, nullable=True, comment='Флаг активна/не активна'),
    sa.ForeignKeyConstraint(['mspeciality_id'], ['medical_specialities.id'], name='services_mspecialities_mspeciality_id_fkey'),
    sa.ForeignKeyConstraint(['service_id'], ['services.id'], name='services_mspecialities_service_id_fkey'),
    sa.PrimaryKeyConstraint('id', name='services_mspecialities_pkey'),
    comment='Таблица связи услуг с медицинскими специальностями'
    )
    op.create_index('ix_services_mspecialities_id', 'services_mspecialities', ['id'], unique=False)
    op.create_table('prices',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('client_price_id', sa.INTEGER(), autoincrement=False, nullable=True, comment='Идентификатор записи в прайс-листе в системе Клиента'),
    sa.Column('service_id', sa.INTEGER(), autoincrement=False, nullable=True, comment='Идентификатор услуги'),
    sa.Column('medical_center_id', sa.INTEGER(), autoincrement=False, nullable=True, comment='Идентификатор медицинского центра'),
    sa.Column('price', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=False, comment='Цена услуги'),
    sa.ForeignKeyConstraint(['medical_center_id'], ['medical_centers.id'], name='prices_medical_center_id_fkey'),
    sa.ForeignKeyConstraint(['service_id'], ['services.id'], name='prices_service_id_fkey'),
    sa.PrimaryKeyConstraint('id', name='prices_pkey'),
    comment='Таблица-справочник "Прайс-лист"'
    )
    op.create_index('ix_prices_id', 'prices', ['id'], unique=False)
    # ### end Alembic commands ###
