"""users_used_advances has been added!

Revision ID: 675b40d61baa
Revises: 0f9cb5c12c95
Create Date: 2024-01-31 17:16:28.064149

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlalchemy_utils


# revision identifiers, used by Alembic.
revision: str = '675b40d61baa'
down_revision: Union[str, None] = '0f9cb5c12c95'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users_used_advances',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('client_id', sa.BigInteger(), nullable=True, comment='Идентификатор записи в системе клиента'),
    sa.Column('user_id', sa.Integer(), nullable=False, comment='Идентификатор пользователя'),
    sa.Column('payment_advance_id', sa.Integer(), nullable=False, comment='Идентификатор авансового платежа пользовтеля'),
    sa.Column('payment_spend_id', sa.Integer(), nullable=False, comment='Идентификатор платежа пользовтеля, в котором используется аванс'),
    sa.Column('amount', sa.Float(), nullable=False, comment='Сумма использования аванса'),
    sa.ForeignKeyConstraint(['payment_advance_id'], ['users_payments.id'], ),
    sa.ForeignKeyConstraint(['payment_spend_id'], ['users_payments.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    comment='Таблица "Использование пользователем внесенного ранее аванса"'
    )
    op.create_index(op.f('ix_users_used_advances_id'), 'users_used_advances', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_users_used_advances_id'), table_name='users_used_advances')
    op.drop_table('users_used_advances')
    # ### end Alembic commands ###
