"""Added mcenters_orice_names table

Revision ID: 6a2144947e36
Revises: 9becea4c3402
Create Date: 2024-01-17 14:56:45.712766

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlalchemy_utils


# revision identifiers, used by Alembic.
revision: str = '6a2144947e36'
down_revision: Union[str, None] = '9becea4c3402'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('mcenters_price_names',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('client_id', sa.BigInteger(), nullable=True, comment='Идентификатор услуги доктора в медцентре в системе клиента'),
    sa.Column('medical_center_id', sa.Integer(), nullable=False, comment='Идентификатор медицинского центра'),
    sa.Column('price_name_id', sa.Integer(), nullable=False, comment='Идентификатор наименования прайса'),
    sa.Column('service_type_id', sa.Integer(), nullable=False, comment='Идентификатор типа услуги'),
    sa.Column('is_active', sa.Boolean(), nullable=True, comment='Флаг активно/неактивно'),
    sa.ForeignKeyConstraint(['medical_center_id'], ['medical_centers.id'], ),
    sa.ForeignKeyConstraint(['price_name_id'], ['prices_names.id'], ),
    sa.ForeignKeyConstraint(['service_type_id'], ['services_types.id'], ),
    sa.PrimaryKeyConstraint('id'),
    comment='Таблица "Услуги наименование прайсов в медцентрах"'
    )
    op.create_index(op.f('ix_mcenters_price_names_id'), 'mcenters_price_names', ['id'], unique=False)
    op.alter_column('users_relatives', 'relationship_degree_id',
               existing_type=sa.INTEGER(),
               comment='Идентификатор родственной связи',
               existing_comment='Идентификатор родственника пользователя',
               existing_nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('users_relatives', 'relationship_degree_id',
               existing_type=sa.INTEGER(),
               comment='Идентификатор родственника пользователя',
               existing_comment='Идентификатор родственной связи',
               existing_nullable=False)
    op.drop_index(op.f('ix_mcenters_price_names_id'), table_name='mcenters_price_names')
    op.drop_table('mcenters_price_names')
    # ### end Alembic commands ###
