"""cascade deleting has been added!

Revision ID: 6de8cef1a9ec
Revises: fda80d1edf96
Create Date: 2024-03-10 19:17:18.990133

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlalchemy_utils


# revision identifiers, used by Alembic.
revision: str = '6de8cef1a9ec'
down_revision: Union[str, None] = 'fda80d1edf96'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('paykeeper_payments_data_user_payment_id_fkey', 'paykeeper_payments_data', type_='foreignkey')
    op.create_foreign_key(None, 'paykeeper_payments_data', 'users_payments', ['user_payment_id'], ['id'], ondelete='CASCADE')
    op.drop_constraint('users_purchases_user_payment_id_fkey', 'users_purchases', type_='foreignkey')
    op.create_foreign_key(None, 'users_purchases', 'users_payments', ['user_payment_id'], ['id'], ondelete='CASCADE')
    op.drop_constraint('users_services_carts_user_purchase_id_fkey', 'users_services_carts', type_='foreignkey')
    op.create_foreign_key(None, 'users_services_carts', 'users_purchases', ['user_purchase_id'], ['id'], ondelete='SET NULL')
    op.drop_constraint('users_used_advances_payment_advance_id_fkey', 'users_used_advances', type_='foreignkey')
    op.create_foreign_key(None, 'users_used_advances', 'users_payments', ['payment_advance_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'users_used_advances', type_='foreignkey')
    op.create_foreign_key('users_used_advances_payment_advance_id_fkey', 'users_used_advances', 'users_payments', ['payment_advance_id'], ['id'])
    op.drop_constraint(None, 'users_services_carts', type_='foreignkey')
    op.create_foreign_key('users_services_carts_user_purchase_id_fkey', 'users_services_carts', 'users_purchases', ['user_purchase_id'], ['id'])
    op.drop_constraint(None, 'users_purchases', type_='foreignkey')
    op.create_foreign_key('users_purchases_user_payment_id_fkey', 'users_purchases', 'users_payments', ['user_payment_id'], ['id'])
    op.drop_constraint(None, 'paykeeper_payments_data', type_='foreignkey')
    op.create_foreign_key('paykeeper_payments_data_user_payment_id_fkey', 'paykeeper_payments_data', 'users_payments', ['user_payment_id'], ['id'])
    # ### end Alembic commands ###
