"""users_documents_requests has been added_1!

Revision ID: 6f8eca55a6a8
Revises: 38673d7e828d
Create Date: 2024-04-13 20:57:20.873288

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlalchemy_utils


# revision identifiers, used by Alembic.
revision: str = '6f8eca55a6a8'
down_revision: Union[str, None] = '38673d7e828d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users_documents_requests', 'is_requested')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users_documents_requests', sa.Column('is_requested', sa.BOOLEAN(), autoincrement=False, nullable=True, comment='Флаг запрошен/незапрошен'))
    # ### end Alembic commands ###
