"""typos shift has been fixed to shifr!

Revision ID: 706f1223fa63
Revises: 9ce8d5e7637e
Create Date: 2024-04-03 11:07:41.526255

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlalchemy_utils


# revision identifiers, used by Alembic.
revision: str = '706f1223fa63'
down_revision: Union[str, None] = '9ce8d5e7637e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('shifrs_discounts', sa.Column('shifr_discount_period_id', sa.Integer(), nullable=True, comment='идентификатор периода скидок шифра'))
    op.drop_constraint('shifrs_discounts_shift_discount_period_id_fkey', 'shifrs_discounts', type_='foreignkey')
    op.create_foreign_key(None, 'shifrs_discounts', 'shifrs_discounts_periods', ['shifr_discount_period_id'], ['id'])
    op.drop_column('shifrs_discounts', 'shift_discount_period_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('shifrs_discounts', sa.Column('shift_discount_period_id', sa.INTEGER(), autoincrement=False, nullable=True, comment='идентификатор периода скидок шифра'))
    op.drop_constraint(None, 'shifrs_discounts', type_='foreignkey')
    op.create_foreign_key('shifrs_discounts_shift_discount_period_id_fkey', 'shifrs_discounts', 'shifrs_discounts_periods', ['shift_discount_period_id'], ['id'])
    op.drop_column('shifrs_discounts', 'shifr_discount_period_id')
    # ### end Alembic commands ###
