"""Added documents tables. It's ok!

Revision ID: 725b639c9007
Revises: 7df204bf50f0
Create Date: 2023-10-13 18:02:20.048918

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlalchemy_utils


# revision identifiers, used by Alembic.
revision: str = '725b639c9007'
down_revision: Union[str, None] = '7df204bf50f0'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('documents_types',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('client_document_type_id', sa.Integer(), nullable=True, comment='Идентификатор типа документа в системе Клиента'),
    sa.Column('name', sa.String(length=200), nullable=False, comment='Наименование документа'),
    sa.Column('description', sa.Text(), nullable=True, comment='Описание документа'),
    sa.Column('document_params', sa.JSON(), nullable=True, comment='Обязательные параметры документа при его запросе'),
    sa.Column('is_online_allowed', sa.Boolean(), nullable=True, comment='Флаг разрешен/неразрешен онлайн просмотр документа'),
    sa.Column('is_active', sa.Boolean(), nullable=True, comment='Флаг активен/не активен'),
    sa.PrimaryKeyConstraint('id'),
    comment='Таблица "Типы документов"'
    )
    op.create_index(op.f('ix_documents_types_id'), 'documents_types', ['id'], unique=False)
    op.create_table('users_documents',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False, comment='Идентификатор пользователя'),
    sa.Column('document_type_id', sa.Integer(), nullable=False, comment='Идентификатор типа документа'),
    sa.Column('request_date', sa.DateTime(), nullable=False, comment='Дата запроса документа'),
    sa.Column('is_needed_paper_original', sa.Boolean(), nullable=True, comment='Флаг нужен/не нужен бумажный оригинал'),
    sa.Column('status', sa.Integer(), nullable=False, comment='Статус документа'),
    sa.Column('document_url', sa.String(length=200), nullable=True, comment='Ссылка для скачивания документа'),
    sa.Column('description', sa.Text(), nullable=True, comment='Дополнительная информация к документу'),
    sa.ForeignKeyConstraint(['document_type_id'], ['documents_types.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    comment='Таблица "Документы пользователя"'
    )
    op.create_index(op.f('ix_users_documents_id'), 'users_documents', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_users_documents_id'), table_name='users_documents')
    op.drop_table('users_documents')
    op.drop_index(op.f('ix_documents_types_id'), table_name='documents_types')
    op.drop_table('documents_types')
    # ### end Alembic commands ###
