"""medical card number has been added to UserTable!

Revision ID: 744151c08da5
Revises: e225870bdc51
Create Date: 2024-05-03 01:46:08.892263

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlalchemy_utils


# revision identifiers, used by Alembic.
revision: str = '744151c08da5'
down_revision: Union[str, None] = 'e225870bdc51'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('medical_card_number', sa.BigInteger(), nullable=True, comment='Номер медицинмкой карты'))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'medical_card_number')
    # ### end Alembic commands ###
