"""The index of tickt_datetime has been removed from the access_tickets table!

Revision ID: 744f270675fe
Revises: 8fba5532b81a
Create Date: 2024-03-29 11:51:47.674435

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlalchemy_utils


# revision identifiers, used by Alembic.
revision: str = '744f270675fe'
down_revision: Union[str, None] = '8fba5532b81a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_access_tickets_ticket_datetime', table_name='access_tickets')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index('ix_access_tickets_ticket_datetime', 'access_tickets', ['ticket_datetime'], unique=False)
    # ### end Alembic commands ###
