"""Unique final!

Revision ID: 77675fc81d1e
Revises: 58a3a9d6133f
Create Date: 2024-05-21 01:23:30.838725

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlalchemy_utils


# revision identifiers, used by Alembic.
revision: str = '77675fc81d1e'
down_revision: Union[str, None] = '58a3a9d6133f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_access_tickets_client_id', table_name='access_tickets')
    op.create_index(op.f('ix_access_tickets_client_id'), 'access_tickets', ['client_id'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_access_tickets_client_id'), table_name='access_tickets')
    op.create_index('ix_access_tickets_client_id', 'access_tickets', ['client_id'], unique=False)
    # ### end Alembic commands ###
