"""ServiceGroupTable has been added!

Revision ID: 77c11d7ae2ef
Revises: ef98618a7657
Create Date: 2023-11-12 13:13:43.879674

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlalchemy_utils


# revision identifiers, used by Alembic.
revision: str = '77c11d7ae2ef'
down_revision: Union[str, None] = 'ef98618a7657'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('services_groups',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('path', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_services_groups_path'), 'services_groups', ['path'], unique=False)
    op.add_column('services', sa.Column('service_group_id', sa.Integer(), nullable=True, comment='Идентификатор группы услуги'))
    op.drop_constraint('services_node_id_fkey', 'services', type_='foreignkey')
    op.create_foreign_key(None, 'services', 'services_groups', ['service_group_id'], ['id'])
    op.drop_column('services', 'node_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('services', sa.Column('node_id', sa.INTEGER(), autoincrement=False, nullable=True, comment='Идентификатор группы услуги'))
    op.drop_constraint(None, 'services', type_='foreignkey')
    op.create_foreign_key('services_node_id_fkey', 'services', 'nodes', ['node_id'], ['id'])
    op.drop_column('services', 'service_group_id')
    op.drop_index(op.f('ix_services_groups_path'), table_name='services_groups')
    op.drop_table('services_groups')
    # ### end Alembic commands ###
