"""UserServiceCartTable has been changed

Revision ID: 7c4a18c21eda
Revises: a469bc220629
Create Date: 2024-03-04 22:34:45.530314

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlalchemy_utils


# revision identifiers, used by Alembic.
revision: str = '7c4a18c21eda'
down_revision: Union[str, None] = 'a469bc220629'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
