"""Changing of access_tickets table has benn added!

Revision ID: 7c882a9c2185
Revises: 6de8cef1a9ec
Create Date: 2024-03-25 15:13:52.653612

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlalchemy_utils


# revision identifiers, used by Alembic.
revision: str = '7c882a9c2185'
down_revision: Union[str, None] = '6de8cef1a9ec'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('access_tickets', 'ticket_room',
               existing_type=sa.VARCHAR(length=5),
               type_=sa.String(length=24),
               existing_comment='Кабинет номерка',
               existing_nullable=True)
    op.drop_constraint('access_tickets_doctor_mcenters_id_fkey', 'access_tickets', type_='foreignkey')
    op.drop_constraint('access_tickets_user_id_fkey', 'access_tickets', type_='foreignkey')
    op.create_foreign_key(None, 'access_tickets', 'doctors_medical_centers', ['doctor_mcenters_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key(None, 'access_tickets', 'users', ['user_id'], ['id'], ondelete='SET NULL')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'access_tickets', type_='foreignkey')
    op.drop_constraint(None, 'access_tickets', type_='foreignkey')
    op.create_foreign_key('access_tickets_user_id_fkey', 'access_tickets', 'users', ['user_id'], ['id'])
    op.create_foreign_key('access_tickets_doctor_mcenters_id_fkey', 'access_tickets', 'doctors_medical_centers', ['doctor_mcenters_id'], ['id'])
    op.alter_column('access_tickets', 'ticket_room',
               existing_type=sa.String(length=24),
               type_=sa.VARCHAR(length=5),
               existing_comment='Кабинет номерка',
               existing_nullable=True)
    # ### end Alembic commands ###
