"""users_documents_requests has been added_2!

Revision ID: 7d1e3c427310
Revises: 6f8eca55a6a8
Create Date: 2024-04-13 20:58:46.487801

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlalchemy_utils


# revision identifiers, used by Alembic.
revision: str = '7d1e3c427310'
down_revision: Union[str, None] = '6f8eca55a6a8'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users_documents_requests', sa.Column('is_requested', sa.Boolean(), nullable=True, comment='Флаг запрошен/незапрошен'))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users_documents_requests', 'is_requested')
    # ### end Alembic commands ###
