"""DoctorMspeciality was added. It's ok!

Revision ID: 7df204bf50f0
Revises: 3100c4fa4c9b
Create Date: 2023-10-09 15:54:42.091306

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlalchemy_utils


# revision identifiers, used by Alembic.
revision: str = '7df204bf50f0'
down_revision: Union[str, None] = '3100c4fa4c9b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('docrors_mspecialities',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('doctor_id', sa.Integer(), nullable=False, comment='Идентификатор доктора'),
    sa.Column('mspeciality_id', sa.Integer(), nullable=False, comment='Идентификатор медицинской специальности'),
    sa.Column('is_active', sa.Boolean(), nullable=True, comment='Флаг активна/не активна'),
    sa.ForeignKeyConstraint(['doctor_id'], ['doctors.id'], ),
    sa.ForeignKeyConstraint(['mspeciality_id'], ['medical_specialities.id'], ),
    sa.PrimaryKeyConstraint('id'),
    comment='Таблица-справочник "Специальности врачей"'
    )
    op.create_index(op.f('ix_docrors_mspecialities_id'), 'docrors_mspecialities', ['id'], unique=False)
    op.drop_constraint('doctors_doctor_mspeciality_id_fkey', 'doctors', type_='foreignkey')
    op.drop_column('doctors', 'doctor_mspeciality_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('doctors', sa.Column('doctor_mspeciality_id', sa.INTEGER(), autoincrement=False, nullable=False))
    op.create_foreign_key('doctors_doctor_mspeciality_id_fkey', 'doctors', 'medical_specialities', ['doctor_mspeciality_id'], ['id'])
    op.drop_index(op.f('ix_docrors_mspecialities_id'), table_name='docrors_mspecialities')
    op.drop_table('docrors_mspecialities')
    # ### end Alembic commands ###
