"""temporary_payments table has been added!

Revision ID: 7ebe4df98687
Revises: 7c882a9c2185
Create Date: 2024-03-25 15:19:43.001965

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlalchemy_utils


# revision identifiers, used by Alembic.
revision: str = '7ebe4df98687'
down_revision: Union[str, None] = '7c882a9c2185'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('temporary_payments',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('payment_id', sa.Integer(), nullable=False, comment='Идентификатор временного платежа'),
    sa.Column('payment_time', sa.DateTime(), nullable=False, comment='Дата и время инициации платежа'),
    sa.PrimaryKeyConstraint('id'),
    comment='Таблица "Временные платежи"'
    )
    op.create_index(op.f('ix_temporary_payments_id'), 'temporary_payments', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_temporary_payments_id'), table_name='temporary_payments')
    op.drop_table('temporary_payments')
    # ### end Alembic commands ###
