"""changing has been added to the initpro_payments_receipts!

Revision ID: 7ef18c0d7113
Revises: d8a7dd10587e
Create Date: 2024-04-07 13:22:15.005566

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlalchemy_utils


# revision identifiers, used by Alembic.
revision: str = '7ef18c0d7113'
down_revision: Union[str, None] = 'd8a7dd10587e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('initpro_payments_receipts', sa.Column('group_code', sa.String(), nullable=True, comment='Параметр group_code в системе Инитпро'))
    op.add_column('initpro_payments_receipts', sa.Column('daemon_code', sa.String(), nullable=True, comment='Параметр daemon_code в системе Инитпро'))
    op.add_column('initpro_payments_receipts', sa.Column('device_code', sa.String(), nullable=True, comment='Параметр device_code в системе Инитпро'))
    op.add_column('initpro_payments_receipts', sa.Column('warnings', sa.String(), nullable=True, comment='Параметр warnings в системе Инитпро'))
    op.add_column('initpro_payments_receipts', sa.Column('external_id', sa.String(), nullable=True, comment='Параметр external_id в системе Инитпро'))
    op.add_column('initpro_payments_receipts', sa.Column('callback_url', sa.String(), nullable=True, comment='Параметр callback_ur в системе Инитпро'))
    op.drop_column('initpro_payments_receipts', 'payload_daemon_code')
    op.drop_column('initpro_payments_receipts', 'payload_callback_url')
    op.drop_column('initpro_payments_receipts', 'payload_warnings')
    op.drop_column('initpro_payments_receipts', 'payload_device_code')
    op.drop_column('initpro_payments_receipts', 'payload_external_id')
    op.drop_column('initpro_payments_receipts', 'payload_group_code')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('initpro_payments_receipts', sa.Column('payload_group_code', sa.VARCHAR(), autoincrement=False, nullable=True, comment='Параметр group_code в системе Инитпро'))
    op.add_column('initpro_payments_receipts', sa.Column('payload_external_id', sa.VARCHAR(), autoincrement=False, nullable=True, comment='Параметр external_id в системе Инитпро'))
    op.add_column('initpro_payments_receipts', sa.Column('payload_device_code', sa.VARCHAR(), autoincrement=False, nullable=True, comment='Параметр device_code в системе Инитпро'))
    op.add_column('initpro_payments_receipts', sa.Column('payload_warnings', sa.VARCHAR(), autoincrement=False, nullable=True, comment='Параметр warnings в системе Инитпро'))
    op.add_column('initpro_payments_receipts', sa.Column('payload_callback_url', sa.VARCHAR(), autoincrement=False, nullable=True, comment='Параметр callback_ur в системе Инитпро'))
    op.add_column('initpro_payments_receipts', sa.Column('payload_daemon_code', sa.VARCHAR(), autoincrement=False, nullable=True, comment='Параметр daemon_code в системе Инитпро'))
    op.drop_column('initpro_payments_receipts', 'callback_url')
    op.drop_column('initpro_payments_receipts', 'external_id')
    op.drop_column('initpro_payments_receipts', 'warnings')
    op.drop_column('initpro_payments_receipts', 'device_code')
    op.drop_column('initpro_payments_receipts', 'daemon_code')
    op.drop_column('initpro_payments_receipts', 'group_code')
    # ### end Alembic commands ###
