"""admin client_id to unique_1!

Revision ID: 816fb0a8585e
Revises: e1ad4591c399
Create Date: 2024-05-15 23:52:12.213141

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlalchemy_utils


# revision identifiers, used by Alembic.
revision: str = '816fb0a8585e'
down_revision: Union[str, None] = 'e1ad4591c399'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_users_admin_client_id', table_name='users_admin')
    op.create_index(op.f('ix_users_admin_client_id'), 'users_admin', ['client_id'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_users_admin_client_id'), table_name='users_admin')
    op.create_index('ix_users_admin_client_id', 'users_admin', ['client_id'], unique=False)
    # ### end Alembic commands ###
