"""payments_type has been moved from the initpro_payments_receipts!

Revision ID: 83cca31d1080
Revises: 4edaf3ccf611
Create Date: 2024-04-06 15:15:57.377148

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlalchemy_utils


# revision identifiers, used by Alembic.
revision: str = '83cca31d1080'
down_revision: Union[str, None] = '4edaf3ccf611'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('initpro_payments_receipts', 'status',
               existing_type=sa.VARCHAR(length=20),
               comment='Статус регистрации документа в системе Инитпро: None, "wait", "done"',
               existing_comment='Статус регистрации документа в системе Инитпро',
               existing_nullable=True)
    op.drop_column('initpro_payments_receipts', 'initpro_payment_type')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('initpro_payments_receipts', sa.Column('initpro_payment_type', sa.VARCHAR(length=1), autoincrement=False, nullable=False, comment='Вид оплаты в системе Инитпро'))
    op.alter_column('initpro_payments_receipts', 'status',
               existing_type=sa.VARCHAR(length=20),
               comment='Статус регистрации документа в системе Инитпро',
               existing_comment='Статус регистрации документа в системе Инитпро: None, "wait", "done"',
               existing_nullable=True)
    # ### end Alembic commands ###
