"""added lpu link to users_payments and added show_in_lk to medical_centers

Revision ID: 88115ae54f9e
Revises: c17dbf9e2b62
Create Date: 2024-02-20 10:56:12.916711

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlalchemy_utils


# revision identifiers, used by Alembic.
revision: str = '88115ae54f9e'
down_revision: Union[str, None] = 'c17dbf9e2b62'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('medical_centers', sa.Column('show_in_lk', sa.Boolean(), nullable=True, comment='Флаг показывать в ЛК/не показывать в ЛК'))
    op.alter_column('medical_centers', 'lpu_id',
               existing_type=sa.INTEGER(),
               comment='Идентификатор лпу',
               existing_comment='Идентификатор города',
               existing_nullable=True)
    op.alter_column('users_payments', 'lpu_id',
               existing_type=sa.INTEGER(),
               comment='Идентификатор лпу',
               existing_comment='Идентификатор lpu',
               existing_nullable=True)
    op.create_foreign_key(None, 'users_payments', 'lpus', ['lpu_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'users_payments', type_='foreignkey')
    op.alter_column('users_payments', 'lpu_id',
               existing_type=sa.INTEGER(),
               comment='Идентификатор lpu',
               existing_comment='Идентификатор лпу',
               existing_nullable=True)
    op.alter_column('medical_centers', 'lpu_id',
               existing_type=sa.INTEGER(),
               comment='Идентификатор города',
               existing_comment='Идентификатор лпу',
               existing_nullable=True)
    op.drop_column('medical_centers', 'show_in_lk')
    # ### end Alembic commands ###
