"""For medical_department_id - nullable=True

Revision ID: 885de9f2efa4
Revises: 25f2d676599b
Create Date: 2023-10-25 19:08:07.506812

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlalchemy_utils


# revision identifiers, used by Alembic.
revision: str = '885de9f2efa4'
down_revision: Union[str, None] = '25f2d676599b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('prices', 'medical_department_id',
               existing_type=sa.INTEGER(),
               nullable=True,
               existing_comment='Идентификатор департамента')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('prices', 'medical_department_id',
               existing_type=sa.INTEGER(),
               nullable=False,
               existing_comment='Идентификатор департамента')
    # ### end Alembic commands ###
