"""The index of tickt_datetime has been added to the access_tickets table!

Revision ID: 8fba5532b81a
Revises: fdf8b8cd6e0b
Create Date: 2024-03-29 11:27:25.606607

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlalchemy_utils


# revision identifiers, used by Alembic.
revision: str = '8fba5532b81a'
down_revision: Union[str, None] = 'fdf8b8cd6e0b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(op.f('ix_access_tickets_ticket_datetime'), 'access_tickets', ['ticket_datetime'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_access_tickets_ticket_datetime'), table_name='access_tickets')
    # ### end Alembic commands ###
