"""Fixed typosin the table name

Revision ID: 90a2aefa0aa0
Revises: 725b639c9007
Create Date: 2023-10-16 09:43:25.911041

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlalchemy_utils


# revision identifiers, used by Alembic.
revision: str = '90a2aefa0aa0'
down_revision: Union[str, None] = '725b639c9007'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users_subscriptions_items',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_subscription_id', sa.Integer(), nullable=False, comment='Идентификатор подписки пользователя'),
    sa.Column('service_id', sa.Integer(), nullable=False, comment='Идентификатор услуги'),
    sa.Column('price', sa.Float(), nullable=False, comment='Цена услуги'),
    sa.Column('discount', sa.Integer(), nullable=True, comment='Скидка на услугу'),
    sa.Column('amount', sa.Float(), nullable=False, comment='Итоговая стоимость услуги'),
    sa.Column('is_paid', sa.Boolean(), nullable=True, comment='Флаг оплачена/не оплачена'),
    sa.Column('is_got', sa.Boolean(), nullable=True, comment='Флаг получена/не получена'),
    sa.Column('is_active', sa.Boolean(), nullable=True, comment='Флаг активности услуги - активная/не активная'),
    sa.ForeignKeyConstraint(['service_id'], ['services.id'], ),
    sa.ForeignKeyConstraint(['user_subscription_id'], ['users_subscriptions.id'], ),
    sa.PrimaryKeyConstraint('id'),
    comment='Таблица "Услуги в абонементе пользователя (состав абонемента пользователя)"'
    )
    op.create_index(op.f('ix_users_subscriptions_items_id'), 'users_subscriptions_items', ['id'], unique=False)
    op.drop_index('ix_users_suscriptions_items_id', table_name='users_suscriptions_items')
    op.drop_table('users_suscriptions_items')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users_suscriptions_items',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('user_subscription_id', sa.INTEGER(), autoincrement=False, nullable=False, comment='Идентификатор подписки пользователя'),
    sa.Column('service_id', sa.INTEGER(), autoincrement=False, nullable=False, comment='Идентификатор услуги'),
    sa.Column('price', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=False, comment='Цена услуги'),
    sa.Column('discount', sa.INTEGER(), autoincrement=False, nullable=True, comment='Скидка на услугу'),
    sa.Column('amount', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=False, comment='Итоговая стоимость услуги'),
    sa.Column('is_paid', sa.BOOLEAN(), autoincrement=False, nullable=True, comment='Флаг оплачена/не оплачена'),
    sa.Column('is_got', sa.BOOLEAN(), autoincrement=False, nullable=True, comment='Флаг получена/не получена'),
    sa.Column('is_active', sa.BOOLEAN(), autoincrement=False, nullable=True, comment='Флаг активности услуги - активная/не активная'),
    sa.ForeignKeyConstraint(['service_id'], ['services.id'], name='users_suscriptions_items_service_id_fkey'),
    sa.ForeignKeyConstraint(['user_subscription_id'], ['users_subscriptions.id'], name='users_suscriptions_items_user_subscription_id_fkey'),
    sa.PrimaryKeyConstraint('id', name='users_suscriptions_items_pkey'),
    comment='Таблица "Услуги в абонементе пользователя (состав абонемента пользователя)"'
    )
    op.create_index('ix_users_suscriptions_items_id', 'users_suscriptions_items', ['id'], unique=False)
    op.drop_index(op.f('ix_users_subscriptions_items_id'), table_name='users_subscriptions_items')
    op.drop_table('users_subscriptions_items')
    # ### end Alembic commands ###
