"""the osn field has been added to medical_centers!


Revision ID: 95af4aa31770
Revises: 0177e7593595
Create Date: 2024-04-04 09:38:30.496715

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlalchemy_utils


# revision identifiers, used by Alembic.
revision: str = '95af4aa31770'
down_revision: Union[str, None] = '0177e7593595'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('medical_centers', sa.Column('sno', sa.Integer(), nullable=True, comment='Код системы налогообложения'))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('medical_centers', 'sno')
    # ### end Alembic commands ###
