"""new fields have been added into the users_documents_requests!

Revision ID: 95e927a600a8
Revises: 23f2caba2395
Create Date: 2024-04-16 11:36:59.515541

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlalchemy_utils


# revision identifiers, used by Alembic.
revision: str = '95e927a600a8'
down_revision: Union[str, None] = '23f2caba2395'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users_documents_requests', sa.Column('client_id', sa.BigInteger(), nullable=True, comment='Идентификатор запроса в системе клиента'))
    op.add_column('users_documents_requests', sa.Column('doc_name', sa.String(), nullable=True, comment='Название документа'))
    op.add_column('users_documents_requests', sa.Column('medical_center_id', sa.Integer(), nullable=True, comment='Идентификатор медицинского центра по умолчанию'))
    op.add_column('users_documents_requests', sa.Column('obtaining_method', sa.Integer(), nullable=True, comment='Метод получения: 0 - В МЦ / 1 - По эл. почте.'))
    op.add_column('users_documents_requests', sa.Column('status', sa.Integer(), nullable=True, comment='Статус запроса: 0 - Новый / 1 - Отправлено оповещение сотруднику / 2 - Ожидает выдачи в МЦ / 3 - Выдан'))
    op.create_index(op.f('ix_users_documents_requests_client_id'), 'users_documents_requests', ['client_id'], unique=False)
    op.create_foreign_key(None, 'users_documents_requests', 'medical_centers', ['medical_center_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'users_documents_requests', type_='foreignkey')
    op.drop_index(op.f('ix_users_documents_requests_client_id'), table_name='users_documents_requests')
    op.drop_column('users_documents_requests', 'status')
    op.drop_column('users_documents_requests', 'obtaining_method')
    op.drop_column('users_documents_requests', 'medical_center_id')
    op.drop_column('users_documents_requests', 'doc_name')
    op.drop_column('users_documents_requests', 'client_id')
    # ### end Alembic commands ###
