"""operatin_type field has been added to initpro-payment_receipts!

Revision ID: 969bb0a0e61a
Revises: 02eaa0d19ec3
Create Date: 2024-04-07 20:28:31.326361

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlalchemy_utils


# revision identifiers, used by Alembic.
revision: str = '969bb0a0e61a'
down_revision: Union[str, None] = '02eaa0d19ec3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('initpro_payments_receipts', sa.Column('operation_type', sa.String(), nullable=True, comment='Тип операции в системе Инитпро'))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('initpro_payments_receipts', 'operation_type')
    # ### end Alembic commands ###
