"""Unique final!

Revision ID: 97bc41fae781
Revises: 77675fc81d1e
Create Date: 2024-05-28 10:08:36.878815

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlalchemy_utils


# revision identifiers, used by Alembic.
revision: str = '97bc41fae781'
down_revision: Union[str, None] = '77675fc81d1e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_policies_client_id', table_name='policies')
    op.create_index(op.f('ix_policies_client_id'), 'policies', ['client_id'], unique=True)
    op.drop_index('ix_users_client_id', table_name='users')
    op.create_index(op.f('ix_users_client_id'), 'users', ['client_id'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_users_client_id'), table_name='users')
    op.create_index('ix_users_client_id', 'users', ['client_id'], unique=False)
    op.drop_index(op.f('ix_policies_client_id'), table_name='policies')
    op.create_index('ix_policies_client_id', 'policies', ['client_id'], unique=False)
    # ### end Alembic commands ###
