"""Field renaming has been done!

Revision ID: 99f7e8908d02
Revises: 02897418f110
Create Date: 2023-11-17 18:21:15.559863

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlalchemy_utils


# revision identifiers, used by Alembic.
revision: str = '99f7e8908d02'
down_revision: Union[str, None] = '02897418f110'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('staff_types', sa.Column('client_staff_type_id', sa.Integer(), nullable=True, comment='Идентификатор типа персонала в системе клиента'))
    op.drop_column('staff_types', 'client_dcategory_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('staff_types', sa.Column('client_dcategory_id', sa.INTEGER(), autoincrement=False, nullable=True, comment='Идентификатор типа персонала в системе клиента'))
    op.drop_column('staff_types', 'client_staff_type_id')
    # ### end Alembic commands ###
