"""ltree to string nas been done_1!

Revision ID: 9a2b2634e54b
Revises: 16da279b3897
Create Date: 2023-11-11 22:21:33.097197

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlalchemy_utils


# revision identifiers, used by Alembic.
revision: str = '9a2b2634e54b'
down_revision: Union[str, None] = '16da279b3897'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('nodes', 'path',
               existing_type=sqlalchemy_utils.types.ltree.LtreeType(),
               type_=sa.String(),
               existing_nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('nodes', 'path',
               existing_type=sa.String(),
               type_=sqlalchemy_utils.types.ltree.LtreeType(),
               existing_nullable=False)
    # ### end Alembic commands ###
