"""The doctors_mcenters_services has been added!

Revision ID: 9becea4c3402
Revises: 645845f17640
Create Date: 2023-12-28 10:37:43.848722

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlalchemy_utils


# revision identifiers, used by Alembic.
revision: str = '9becea4c3402'
down_revision: Union[str, None] = '645845f17640'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('doctors_mcenters_services',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('client_id', sa.BigInteger(), nullable=True, comment='Идентификатор услуги доктора в медцентре в системе клиента'),
    sa.Column('service_id', sa.Integer(), nullable=False, comment='Идентификатор услуги'),
    sa.Column('doctor_mcenters_id', sa.Integer(), nullable=False, comment='Идентификатор доктора в медцентре'),
    sa.Column('is_active', sa.Boolean(), nullable=True, comment='Флаг активно/неактивно'),
    sa.ForeignKeyConstraint(['doctor_mcenters_id'], ['doctors_medical_centers.id'], ),
    sa.ForeignKeyConstraint(['service_id'], ['services.id'], ),
    sa.PrimaryKeyConstraint('id'),
    comment='Таблица "Услуги докторов в медицинских центрах"'
    )
    op.create_index(op.f('ix_doctors_mcenters_services_id'), 'doctors_mcenters_services', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_doctors_mcenters_services_id'), table_name='doctors_mcenters_services')
    op.drop_table('doctors_mcenters_services')
    # ### end Alembic commands ###
