"""Removed not needed tables!

Revision ID: 9bf6f782b5c1
Revises: 2c034c923941
Create Date: 2023-11-16 15:13:04.959829

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlalchemy_utils


# revision identifiers, used by Alembic.
revision: str = '9bf6f782b5c1'
down_revision: Union[str, None] = '2c034c923941'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_relationship_degreeses_id', table_name='relationship_degreeses')
    op.drop_table('relationship_degreeses')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('relationship_degreeses',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('client_relationship_degrees_id', sa.INTEGER(), autoincrement=False, nullable=True, comment='Идентификатор степени родства в системе клиента'),
    sa.Column('name', sa.VARCHAR(length=10), autoincrement=False, nullable=False, comment='Наименование степени родства: отец, мать, сын, дочь, опекун, подопечный, другой'),
    sa.PrimaryKeyConstraint('id', name='relationship_degreeses_pkey'),
    comment='Таблица "Степени родства"'
    )
    op.create_index('ix_relationship_degreeses_id', 'relationship_degreeses', ['id'], unique=False)
    # ### end Alembic commands ###
