"""Fixed typos_7!

Revision ID: 9d2731301df7
Revises: 0176a8b5efb9
Create Date: 2023-11-22 13:39:34.825396

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlalchemy_utils


# revision identifiers, used by Alembic.
revision: str = '9d2731301df7'
down_revision: Union[str, None] = '0176a8b5efb9'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('packs_types', 'name',
               existing_type=sa.VARCHAR(length=200),
               comment='Наименование типа пакета услуг',
               existing_comment='Наименование',
               existing_nullable=False)
    op.create_unique_constraint(None, 'packs_types', ['name'])
    op.create_table_comment(
        'packs_types',
        'Таблица "Типы пакетов услуг в абонементе"',
        existing_comment='Таблица "Типы пакетов"',
        schema=None
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table_comment(
        'packs_types',
        'Таблица "Типы пакетов"',
        existing_comment='Таблица "Типы пакетов услуг в абонементе"',
        schema=None
    )
    op.drop_constraint(None, 'packs_types', type_='unique')
    op.alter_column('packs_types', 'name',
               existing_type=sa.VARCHAR(length=200),
               comment='Наименование',
               existing_comment='Наименование типа пакета услуг',
               existing_nullable=False)
    # ### end Alembic commands ###
