"""photo field was increased to 200

Revision ID: 9ed36975a9cf
Revises: 885de9f2efa4
Create Date: 2023-10-25 20:28:59.884026

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlalchemy_utils


# revision identifiers, used by Alembic.
revision: str = '9ed36975a9cf'
down_revision: Union[str, None] = '885de9f2efa4'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('doctors', 'photo',
               existing_type=sa.VARCHAR(length=100),
               type_=sa.String(length=200),
               existing_comment='Фотография доктора',
               existing_nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('doctors', 'photo',
               existing_type=sa.String(length=200),
               type_=sa.VARCHAR(length=100),
               existing_comment='Фотография доктора',
               existing_nullable=True)
    # ### end Alembic commands ###
