"""Removed not needed tables!

Revision ID: 9f87ec3a9497
Revises: 12595e5ad882
Create Date: 2023-11-16 15:06:40.441499

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlalchemy_utils


# revision identifiers, used by Alembic.
revision: str = '9f87ec3a9497'
down_revision: Union[str, None] = '12595e5ad882'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_services_directions_id', table_name='services_directions')
    op.drop_table('services_directions')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('services_directions',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('client_sdirection_id', sa.INTEGER(), autoincrement=False, nullable=True, comment='Идентификатор направления услуг в системе клиента'),
    sa.Column('name', sa.VARCHAR(length=100), autoincrement=False, nullable=False, comment='Наименование направления услуги'),
    sa.Column('description', sa.TEXT(), autoincrement=False, nullable=True, comment='Описание направления услуги'),
    sa.Column('is_active', sa.BOOLEAN(), autoincrement=False, nullable=True, comment='Флаг активно/неактивно'),
    sa.PrimaryKeyConstraint('id', name='services_directions_pkey'),
    sa.UniqueConstraint('name', name='services_directions_name_key'),
    comment='Таблица-спреавочник "Направления услуг"'
    )
    op.create_index('ix_services_directions_id', 'services_directions', ['id'], unique=False)
    # ### end Alembic commands ###
