"""typos has been fixed!

Revision ID: a75f5544e180
Revises: 6a9a4772933c
Create Date: 2024-02-25 17:58:11.883057

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlalchemy_utils


# revision identifiers, used by Alembic.
revision: str = 'a75f5544e180'
down_revision: Union[str, None] = '6a9a4772933c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('policies', sa.Column('discount_coefficient', sa.Float(), nullable=True, comment='Коэффициент на скидку'))
    op.drop_column('policies', 'discoumt_coefficient')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('policies', sa.Column('discoumt_coefficient', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True, comment='Коэффициент на скидку'))
    op.drop_column('policies', 'discount_coefficient')
    # ### end Alembic commands ###
