"""Added index to access_tickets.ticket_datetine!

Revision ID: ae9f62a80164
Revises: de239574e1fd
Create Date: 2024-04-01 12:25:23.817449

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlalchemy_utils


# revision identifiers, used by Alembic.
revision: str = 'ae9f62a80164'
down_revision: Union[str, None] = 'de239574e1fd'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index('idx_date', 'access_tickets', [sa.text("date_trunc('day', ticket_datetime)")], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('idx_date', table_name='access_tickets')
    # ### end Alembic commands ###
