"""price_id has been added into users_services_carts!

Revision ID: b190fb38d63d
Revises: 62f2acf50671
Create Date: 2024-01-24 16:32:14.752887

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlalchemy_utils


# revision identifiers, used by Alembic.
revision: str = 'b190fb38d63d'
down_revision: Union[str, None] = '62f2acf50671'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('users_services_carts', 'price_id',
               existing_type=sa.INTEGER(),
               comment='Идентификатор прайсовой стоимости услуги',
               existing_nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('users_services_carts', 'price_id',
               existing_type=sa.INTEGER(),
               comment=None,
               existing_comment='Идентификатор прайсовой стоимости услуги',
               existing_nullable=False)
    # ### end Alembic commands ###
