"""The new table users_default_objects has been added_2

Revision ID: b1f7fd81416f
Revises: 59822a93fdd8
Create Date: 2024-01-19 17:22:58.175586

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlalchemy_utils


# revision identifiers, used by Alembic.
revision: str = 'b1f7fd81416f'
down_revision: Union[str, None] = '59822a93fdd8'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(None, 'users_default_objects', ['user_id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'users_default_objects', type_='unique')
    # ### end Alembic commands ###
