"""access_tickets has been modificated

Revision ID: b4709eb30263
Revises: bff8c411e4f2
Create Date: 2023-12-22 13:26:02.601595

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlalchemy_utils


# revision identifiers, used by Alembic.
revision: str = 'b4709eb30263'
down_revision: Union[str, None] = 'bff8c411e4f2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('access_tickets', 'user_id',
               existing_type=sa.INTEGER(),
               nullable=True,
               existing_comment='Идентификатор пользователя')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('access_tickets', 'user_id',
               existing_type=sa.INTEGER(),
               nullable=False,
               existing_comment='Идентификатор пользователя')
    # ### end Alembic commands ###
