"""users_services_carte has been changed!

Revision ID: b673a0d79a26
Revises: 04c8c8379d4d
Create Date: 2024-01-23 17:34:51.767701

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlalchemy_utils


# revision identifiers, used by Alembic.
revision: str = 'b673a0d79a26'
down_revision: Union[str, None] = '04c8c8379d4d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users_services_carts', sa.Column('doctor_mcenter_id', sa.Integer(), nullable=True, comment='Идентификатор доктора, выбранного в услуге'))
    op.add_column('users_services_carts', sa.Column('doctor_mcenter_exec_id', sa.Integer(), nullable=True, comment='Идентификатор доктора, выполнявшего услугу'))
    op.add_column('users_services_carts', sa.Column('doctor_mcenter_send_id', sa.Integer(), nullable=True, comment='Идентификатор доктора, назначившего услугу'))
    op.add_column('users_services_carts', sa.Column('doctor_mcenter_nurse_id', sa.Integer(), nullable=True, comment='Идентификатор медсестры, выполнявшей услугу'))
    op.add_column('users_services_carts', sa.Column('doctor_mcenter_paramedic_id', sa.Integer(), nullable=True, comment='Идентификатор доктора - парамедика, выполнявшего услугу'))
    op.drop_constraint('users_services_carts_doctor_paramedic_id_fkey', 'users_services_carts', type_='foreignkey')
    op.drop_constraint('users_services_carts_doctor_exec_id_fkey', 'users_services_carts', type_='foreignkey')
    op.drop_constraint('users_services_carts_doctor_nurse_id_fkey', 'users_services_carts', type_='foreignkey')
    op.drop_constraint('users_services_carts_doctor_send_id_fkey', 'users_services_carts', type_='foreignkey')
    op.drop_constraint('users_services_carts_doctor_id_fkey', 'users_services_carts', type_='foreignkey')
    op.create_foreign_key(None, 'users_services_carts', 'doctors_medical_centers', ['doctor_mcenter_send_id'], ['id'])
    op.create_foreign_key(None, 'users_services_carts', 'doctors_medical_centers', ['doctor_mcenter_nurse_id'], ['id'])
    op.create_foreign_key(None, 'users_services_carts', 'doctors_medical_centers', ['doctor_mcenter_paramedic_id'], ['id'])
    op.create_foreign_key(None, 'users_services_carts', 'doctors_medical_centers', ['doctor_mcenter_exec_id'], ['id'])
    op.create_foreign_key(None, 'users_services_carts', 'doctors_medical_centers', ['doctor_mcenter_id'], ['id'])
    op.drop_column('users_services_carts', 'doctor_nurse_id')
    op.drop_column('users_services_carts', 'doctor_exec_id')
    op.drop_column('users_services_carts', 'doctor_paramedic_id')
    op.drop_column('users_services_carts', 'doctor_id')
    op.drop_column('users_services_carts', 'doctor_send_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users_services_carts', sa.Column('doctor_send_id', sa.INTEGER(), autoincrement=False, nullable=True, comment='Идентификатор доктора, назначившего услугу'))
    op.add_column('users_services_carts', sa.Column('doctor_id', sa.INTEGER(), autoincrement=False, nullable=True, comment='Идентификатор доктора, выбранного в услуге'))
    op.add_column('users_services_carts', sa.Column('doctor_paramedic_id', sa.INTEGER(), autoincrement=False, nullable=True, comment='Идентификатор доктора - парамедика, выполнявшего услугу'))
    op.add_column('users_services_carts', sa.Column('doctor_exec_id', sa.INTEGER(), autoincrement=False, nullable=True, comment='Идентификатор доктора, выполнявшего услугу'))
    op.add_column('users_services_carts', sa.Column('doctor_nurse_id', sa.INTEGER(), autoincrement=False, nullable=True, comment='Идентификатор медсестры, выполнявшей услугу'))
    op.drop_constraint(None, 'users_services_carts', type_='foreignkey')
    op.drop_constraint(None, 'users_services_carts', type_='foreignkey')
    op.drop_constraint(None, 'users_services_carts', type_='foreignkey')
    op.drop_constraint(None, 'users_services_carts', type_='foreignkey')
    op.drop_constraint(None, 'users_services_carts', type_='foreignkey')
    op.create_foreign_key('users_services_carts_doctor_id_fkey', 'users_services_carts', 'doctors_medical_centers', ['doctor_id'], ['id'])
    op.create_foreign_key('users_services_carts_doctor_send_id_fkey', 'users_services_carts', 'doctors_medical_centers', ['doctor_send_id'], ['id'])
    op.create_foreign_key('users_services_carts_doctor_nurse_id_fkey', 'users_services_carts', 'doctors_medical_centers', ['doctor_nurse_id'], ['id'])
    op.create_foreign_key('users_services_carts_doctor_exec_id_fkey', 'users_services_carts', 'doctors_medical_centers', ['doctor_exec_id'], ['id'])
    op.create_foreign_key('users_services_carts_doctor_paramedic_id_fkey', 'users_services_carts', 'doctors_medical_centers', ['doctor_paramedic_id'], ['id'])
    op.drop_column('users_services_carts', 'doctor_mcenter_paramedic_id')
    op.drop_column('users_services_carts', 'doctor_mcenter_nurse_id')
    op.drop_column('users_services_carts', 'doctor_mcenter_send_id')
    op.drop_column('users_services_carts', 'doctor_mcenter_exec_id')
    op.drop_column('users_services_carts', 'doctor_mcenter_id')
    # ### end Alembic commands ###
