"""paykeeper_payments_data has been added_1!

Revision ID: ba9d2c68f223
Revises: fa1a42696358
Create Date: 2024-02-15 13:47:31.500649

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlalchemy_utils


# revision identifiers, used by Alembic.
revision: str = 'ba9d2c68f223'
down_revision: Union[str, None] = 'fa1a42696358'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(None, 'paykeeper_payments_data', ['user_payment_id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'paykeeper_payments_data', type_='unique')
    # ### end Alembic commands ###
