"""Comments have been added to user_relatives

Revision ID: bde51d0babeb
Revises: bc45fd0e7236
Create Date: 2023-10-31 13:29:24.060708

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlalchemy_utils


# revision identifiers, used by Alembic.
revision: str = 'bde51d0babeb'
down_revision: Union[str, None] = 'bc45fd0e7236'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('relationship_degreeses', 'client_relationship_degrees_id',
               existing_type=sa.INTEGER(),
               comment='Идентификатор степени родства в системе клиента',
               existing_nullable=True)
    op.alter_column('relationship_degreeses', 'name',
               existing_type=sa.VARCHAR(length=10),
               comment='Наименование степени родства: отец, мать, сын, дочь, опекун, подопечный, другой',
               existing_nullable=False)
    op.create_table_comment(
        'relationship_degreeses',
        'Таблица "Степени родства"',
        existing_comment=None,
        schema=None
    )
    op.alter_column('user_relatives', 'user_id',
               existing_type=sa.INTEGER(),
               comment='идентификатор потльзователя',
               existing_nullable=False)
    op.alter_column('user_relatives', 'user_relative_id',
               existing_type=sa.INTEGER(),
               comment='Идентификатор родственника пользователя',
               existing_nullable=False)
    op.alter_column('user_relatives', 'relationship_degree_id',
               existing_type=sa.INTEGER(),
               comment='Идентификатор степени родства',
               existing_nullable=False)
    op.alter_column('user_relatives', 'is_legal_agent',
               existing_type=sa.BOOLEAN(),
               comment='Флаг является законным представителем / не является законным представителем',
               existing_nullable=True)
    op.create_table_comment(
        'user_relatives',
        'Таблица "Родственники пользователя"',
        existing_comment=None,
        schema=None
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table_comment(
        'user_relatives',
        existing_comment='Таблица "Родственники пользователя"',
        schema=None
    )
    op.alter_column('user_relatives', 'is_legal_agent',
               existing_type=sa.BOOLEAN(),
               comment=None,
               existing_comment='Флаг является законным представителем / не является законным представителем',
               existing_nullable=True)
    op.alter_column('user_relatives', 'relationship_degree_id',
               existing_type=sa.INTEGER(),
               comment=None,
               existing_comment='Идентификатор степени родства',
               existing_nullable=False)
    op.alter_column('user_relatives', 'user_relative_id',
               existing_type=sa.INTEGER(),
               comment=None,
               existing_comment='Идентификатор родственника пользователя',
               existing_nullable=False)
    op.alter_column('user_relatives', 'user_id',
               existing_type=sa.INTEGER(),
               comment=None,
               existing_comment='идентификатор потльзователя',
               existing_nullable=False)
    op.drop_table_comment(
        'relationship_degreeses',
        existing_comment='Таблица "Степени родства"',
        schema=None
    )
    op.alter_column('relationship_degreeses', 'name',
               existing_type=sa.VARCHAR(length=10),
               comment=None,
               existing_comment='Наименование степени родства: отец, мать, сын, дочь, опекун, подопечный, другой',
               existing_nullable=False)
    op.alter_column('relationship_degreeses', 'client_relationship_degrees_id',
               existing_type=sa.INTEGER(),
               comment=None,
               existing_comment='Идентификатор степени родства в системе клиента',
               existing_nullable=True)
    # ### end Alembic commands ###
