"""changing for subscribes have been added_2!

Revision ID: bf61bb1d0b30
Revises: 3b7caef654f7
Create Date: 2024-02-21 15:37:48.771106

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlalchemy_utils


# revision identifiers, used by Alembic.
revision: str = 'bf61bb1d0b30'
down_revision: Union[str, None] = '3b7caef654f7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
