"""Accounts' tables go to BigInteger for client_id_1!

Revision ID: bff8c411e4f2
Revises: 12f3bd25925b
Create Date: 2023-12-21 10:46:03.751358

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlalchemy_utils


# revision identifiers, used by Alembic.
revision: str = 'bff8c411e4f2'
down_revision: Union[str, None] = '12f3bd25925b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('access_tickets', 'client_id',
               existing_type=sa.INTEGER(),
               type_=sa.BigInteger(),
               existing_comment='Идентификатор номерка в системе клиента',
               existing_nullable=True)
    op.alter_column('complex_services', 'client_id',
               existing_type=sa.INTEGER(),
               type_=sa.BigInteger(),
               existing_comment='Идентификатор услуги в системе Клиента',
               existing_nullable=True)
    op.alter_column('doctor_statuses_types', 'client_id',
               existing_type=sa.INTEGER(),
               type_=sa.BigInteger(),
               existing_comment='Идентификатор типа статуса в системе клиента',
               existing_nullable=True)
    op.alter_column('doctors', 'client_id',
               existing_type=sa.INTEGER(),
               type_=sa.BigInteger(),
               existing_comment='Идентификатор доктора в системе клиента',
               existing_nullable=True)
    op.alter_column('doctors_categories', 'client_id',
               existing_type=sa.INTEGER(),
               type_=sa.BigInteger(),
               existing_comment='Идентификатор категории в системе клиента',
               existing_nullable=True)
    op.alter_column('doctors_medical_centers', 'client_id',
               existing_type=sa.INTEGER(),
               type_=sa.BigInteger(),
               existing_comment='Идентификатор доктора в медцентре в системе клиента',
               existing_nullable=True)
    op.alter_column('doctors_patients_types', 'client_id',
               existing_type=sa.INTEGER(),
               type_=sa.BigInteger(),
               existing_comment='Идентификатор типа пауцента для данного доктора в системе клиента',
               existing_nullable=True)
    op.alter_column('doctors_replacements', 'client_id',
               existing_type=sa.INTEGER(),
               type_=sa.BigInteger(),
               existing_comment='Идентификатор записи подмены в системе клиента',
               existing_nullable=True)
    op.alter_column('financial_types', 'client_id',
               existing_type=sa.INTEGER(),
               type_=sa.BigInteger(),
               existing_comment='Идентификатор финансового типа в системе клиента',
               existing_nullable=True)
    op.alter_column('medical_positions', 'client_id',
               existing_type=sa.INTEGER(),
               type_=sa.BigInteger(),
               existing_comment='Идентификатор должности в системе клиента',
               existing_nullable=True)
    op.alter_column('medical_specialities', 'client_id',
               existing_type=sa.INTEGER(),
               type_=sa.BigInteger(),
               existing_comment='Идентификатор специальности в системе клиента',
               existing_nullable=True)
    op.alter_column('packs_types', 'client_id',
               existing_type=sa.INTEGER(),
               type_=sa.BigInteger(),
               existing_comment='Идентификатор типа пакета в системе клиента',
               existing_nullable=True)
    op.alter_column('patients_types', 'client_id',
               existing_type=sa.INTEGER(),
               type_=sa.BigInteger(),
               existing_comment='Идентификатор типа пациента в системе клиента',
               existing_nullable=True)
    op.alter_column('payments_types', 'client_id',
               existing_type=sa.INTEGER(),
               type_=sa.BigInteger(),
               existing_comment='Идентификатор типа платежа в системе клиента',
               existing_nullable=True)
    op.alter_column('policies', 'client_id',
               existing_type=sa.INTEGER(),
               type_=sa.BigInteger(),
               existing_comment='Идентификатор полиса в системе клиента',
               existing_nullable=True)
    op.alter_column('prices', 'client_id',
               existing_type=sa.INTEGER(),
               type_=sa.BigInteger(),
               existing_comment='Идентификатор прайса в системе клиента',
               existing_nullable=True)
    op.alter_column('prices_names', 'client_id',
               existing_type=sa.INTEGER(),
               type_=sa.BigInteger(),
               existing_comment='Идентификатор имени прайса в системе клиента',
               existing_nullable=True)
    op.alter_column('prices_periods', 'client_id',
               existing_type=sa.INTEGER(),
               type_=sa.BigInteger(),
               existing_comment='Идентификатор периода действия в системе клиента',
               existing_nullable=True)
    op.alter_column('refuses_reasons', 'client_id',
               existing_type=sa.INTEGER(),
               type_=sa.BigInteger(),
               existing_comment='Идентификатор причины отказа в системе клиента',
               existing_nullable=True)
    op.alter_column('services', 'client_id',
               existing_type=sa.INTEGER(),
               type_=sa.BigInteger(),
               existing_comment='Идентификатор услуги в системе Клиента',
               existing_nullable=True)
    op.alter_column('services_groups', 'client_id',
               existing_type=sa.INTEGER(),
               type_=sa.BigInteger(),
               existing_comment='Идентификатор узла прейкуранта в системе клиента',
               existing_nullable=True)
    op.alter_column('services_types', 'client_id',
               existing_type=sa.INTEGER(),
               type_=sa.BigInteger(),
               existing_comment='Идентификатор типа услуги на стороне клиента',
               existing_nullable=True)
    op.alter_column('shifrs', 'client_id',
               existing_type=sa.INTEGER(),
               type_=sa.BigInteger(),
               existing_comment='Идентификатор шифра в системе клиента',
               existing_nullable=True)
    op.alter_column('shifrs_discounts', 'client_id',
               existing_type=sa.INTEGER(),
               type_=sa.BigInteger(),
               existing_comment='идентификатор скидки шифра в системе клиента',
               existing_nullable=True)
    op.alter_column('shifrs_discounts_periods', 'client_id',
               existing_type=sa.INTEGER(),
               type_=sa.BigInteger(),
               existing_comment='Идентификатор периода скидок шифра в системе клиента',
               existing_nullable=True)
    op.alter_column('staff_types', 'client_id',
               existing_type=sa.INTEGER(),
               type_=sa.BigInteger(),
               existing_comment='Идентификатор типа персонала в системе клиента',
               existing_nullable=True)
    op.alter_column('subscribes_doctors', 'client_id',
               existing_type=sa.INTEGER(),
               type_=sa.BigInteger(),
               existing_comment='Идентификатор доктра на абонементе в системе клиента',
               existing_nullable=True)
    op.alter_column('subscribes_services_packs', 'client_id',
               existing_type=sa.INTEGER(),
               type_=sa.BigInteger(),
               existing_comment='Идентификатор групп услуг аьонементов в системе клиента',
               existing_nullable=True)
    op.alter_column('subscribes_spacks_records', 'client_id',
               existing_type=sa.INTEGER(),
               type_=sa.BigInteger(),
               existing_comment='Идентификатор записи пакета услуги абонемента в системе клиента',
               existing_nullable=True)
    op.alter_column('users_admin', 'client_id',
               existing_type=sa.INTEGER(),
               type_=sa.BigInteger(),
               existing_comment='Идентификатор записи в таблице администрирования в системе клиента',
               existing_nullable=True)
    op.alter_column('users_payments', 'client_id',
               existing_type=sa.INTEGER(),
               type_=sa.BigInteger(),
               existing_comment='Идентификатор платежа пользователя в системе клиента',
               existing_nullable=True)
    op.alter_column('users_payments', 'user_id',
               existing_type=sa.INTEGER(),
               type_=sa.BigInteger(),
               existing_comment='Идентификатор пользователя',
               existing_nullable=False)
    op.alter_column('users_purchases', 'client_id',
               existing_type=sa.INTEGER(),
               type_=sa.BigInteger(),
               existing_comment='Идентификатор покупки пользователя в системе клиента',
               existing_nullable=True)
    op.alter_column('users_purchases_returns', 'client_id',
               existing_type=sa.INTEGER(),
               type_=sa.BigInteger(),
               existing_comment='Идентификатор возврата покупки пользователя в системе клиента',
               existing_nullable=True)
    op.alter_column('users_services_carts', 'client_id',
               existing_type=sa.INTEGER(),
               type_=sa.BigInteger(),
               existing_comment='Идентификатор записи в корзине в системе клиента',
               existing_nullable=True)
    op.alter_column('users_services_plans', 'client_id',
               existing_type=sa.INTEGER(),
               type_=sa.BigInteger(),
               existing_comment='Идентификатор запланированной услуги в системе клиента',
               existing_nullable=True)
    op.alter_column('users_subscribes', 'client_id',
               existing_type=sa.INTEGER(),
               type_=sa.BigInteger(),
               existing_comment='Идентификатор абонемента пользователя в системе клиента',
               existing_nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('users_subscribes', 'client_id',
               existing_type=sa.BigInteger(),
               type_=sa.INTEGER(),
               existing_comment='Идентификатор абонемента пользователя в системе клиента',
               existing_nullable=True)
    op.alter_column('users_services_plans', 'client_id',
               existing_type=sa.BigInteger(),
               type_=sa.INTEGER(),
               existing_comment='Идентификатор запланированной услуги в системе клиента',
               existing_nullable=True)
    op.alter_column('users_services_carts', 'client_id',
               existing_type=sa.BigInteger(),
               type_=sa.INTEGER(),
               existing_comment='Идентификатор записи в корзине в системе клиента',
               existing_nullable=True)
    op.alter_column('users_purchases_returns', 'client_id',
               existing_type=sa.BigInteger(),
               type_=sa.INTEGER(),
               existing_comment='Идентификатор возврата покупки пользователя в системе клиента',
               existing_nullable=True)
    op.alter_column('users_purchases', 'client_id',
               existing_type=sa.BigInteger(),
               type_=sa.INTEGER(),
               existing_comment='Идентификатор покупки пользователя в системе клиента',
               existing_nullable=True)
    op.alter_column('users_payments', 'user_id',
               existing_type=sa.BigInteger(),
               type_=sa.INTEGER(),
               existing_comment='Идентификатор пользователя',
               existing_nullable=False)
    op.alter_column('users_payments', 'client_id',
               existing_type=sa.BigInteger(),
               type_=sa.INTEGER(),
               existing_comment='Идентификатор платежа пользователя в системе клиента',
               existing_nullable=True)
    op.alter_column('users_admin', 'client_id',
               existing_type=sa.BigInteger(),
               type_=sa.INTEGER(),
               existing_comment='Идентификатор записи в таблице администрирования в системе клиента',
               existing_nullable=True)
    op.alter_column('subscribes_spacks_records', 'client_id',
               existing_type=sa.BigInteger(),
               type_=sa.INTEGER(),
               existing_comment='Идентификатор записи пакета услуги абонемента в системе клиента',
               existing_nullable=True)
    op.alter_column('subscribes_services_packs', 'client_id',
               existing_type=sa.BigInteger(),
               type_=sa.INTEGER(),
               existing_comment='Идентификатор групп услуг аьонементов в системе клиента',
               existing_nullable=True)
    op.alter_column('subscribes_doctors', 'client_id',
               existing_type=sa.BigInteger(),
               type_=sa.INTEGER(),
               existing_comment='Идентификатор доктра на абонементе в системе клиента',
               existing_nullable=True)
    op.alter_column('staff_types', 'client_id',
               existing_type=sa.BigInteger(),
               type_=sa.INTEGER(),
               existing_comment='Идентификатор типа персонала в системе клиента',
               existing_nullable=True)
    op.alter_column('shifrs_discounts_periods', 'client_id',
               existing_type=sa.BigInteger(),
               type_=sa.INTEGER(),
               existing_comment='Идентификатор периода скидок шифра в системе клиента',
               existing_nullable=True)
    op.alter_column('shifrs_discounts', 'client_id',
               existing_type=sa.BigInteger(),
               type_=sa.INTEGER(),
               existing_comment='идентификатор скидки шифра в системе клиента',
               existing_nullable=True)
    op.alter_column('shifrs', 'client_id',
               existing_type=sa.BigInteger(),
               type_=sa.INTEGER(),
               existing_comment='Идентификатор шифра в системе клиента',
               existing_nullable=True)
    op.alter_column('services_types', 'client_id',
               existing_type=sa.BigInteger(),
               type_=sa.INTEGER(),
               existing_comment='Идентификатор типа услуги на стороне клиента',
               existing_nullable=True)
    op.alter_column('services_groups', 'client_id',
               existing_type=sa.BigInteger(),
               type_=sa.INTEGER(),
               existing_comment='Идентификатор узла прейкуранта в системе клиента',
               existing_nullable=True)
    op.alter_column('services', 'client_id',
               existing_type=sa.BigInteger(),
               type_=sa.INTEGER(),
               existing_comment='Идентификатор услуги в системе Клиента',
               existing_nullable=True)
    op.alter_column('refuses_reasons', 'client_id',
               existing_type=sa.BigInteger(),
               type_=sa.INTEGER(),
               existing_comment='Идентификатор причины отказа в системе клиента',
               existing_nullable=True)
    op.alter_column('prices_periods', 'client_id',
               existing_type=sa.BigInteger(),
               type_=sa.INTEGER(),
               existing_comment='Идентификатор периода действия в системе клиента',
               existing_nullable=True)
    op.alter_column('prices_names', 'client_id',
               existing_type=sa.BigInteger(),
               type_=sa.INTEGER(),
               existing_comment='Идентификатор имени прайса в системе клиента',
               existing_nullable=True)
    op.alter_column('prices', 'client_id',
               existing_type=sa.BigInteger(),
               type_=sa.INTEGER(),
               existing_comment='Идентификатор прайса в системе клиента',
               existing_nullable=True)
    op.alter_column('policies', 'client_id',
               existing_type=sa.BigInteger(),
               type_=sa.INTEGER(),
               existing_comment='Идентификатор полиса в системе клиента',
               existing_nullable=True)
    op.alter_column('payments_types', 'client_id',
               existing_type=sa.BigInteger(),
               type_=sa.INTEGER(),
               existing_comment='Идентификатор типа платежа в системе клиента',
               existing_nullable=True)
    op.alter_column('patients_types', 'client_id',
               existing_type=sa.BigInteger(),
               type_=sa.INTEGER(),
               existing_comment='Идентификатор типа пациента в системе клиента',
               existing_nullable=True)
    op.alter_column('packs_types', 'client_id',
               existing_type=sa.BigInteger(),
               type_=sa.INTEGER(),
               existing_comment='Идентификатор типа пакета в системе клиента',
               existing_nullable=True)
    op.alter_column('medical_specialities', 'client_id',
               existing_type=sa.BigInteger(),
               type_=sa.INTEGER(),
               existing_comment='Идентификатор специальности в системе клиента',
               existing_nullable=True)
    op.alter_column('medical_positions', 'client_id',
               existing_type=sa.BigInteger(),
               type_=sa.INTEGER(),
               existing_comment='Идентификатор должности в системе клиента',
               existing_nullable=True)
    op.alter_column('financial_types', 'client_id',
               existing_type=sa.BigInteger(),
               type_=sa.INTEGER(),
               existing_comment='Идентификатор финансового типа в системе клиента',
               existing_nullable=True)
    op.alter_column('doctors_replacements', 'client_id',
               existing_type=sa.BigInteger(),
               type_=sa.INTEGER(),
               existing_comment='Идентификатор записи подмены в системе клиента',
               existing_nullable=True)
    op.alter_column('doctors_patients_types', 'client_id',
               existing_type=sa.BigInteger(),
               type_=sa.INTEGER(),
               existing_comment='Идентификатор типа пауцента для данного доктора в системе клиента',
               existing_nullable=True)
    op.alter_column('doctors_medical_centers', 'client_id',
               existing_type=sa.BigInteger(),
               type_=sa.INTEGER(),
               existing_comment='Идентификатор доктора в медцентре в системе клиента',
               existing_nullable=True)
    op.alter_column('doctors_categories', 'client_id',
               existing_type=sa.BigInteger(),
               type_=sa.INTEGER(),
               existing_comment='Идентификатор категории в системе клиента',
               existing_nullable=True)
    op.alter_column('doctors', 'client_id',
               existing_type=sa.BigInteger(),
               type_=sa.INTEGER(),
               existing_comment='Идентификатор доктора в системе клиента',
               existing_nullable=True)
    op.alter_column('doctor_statuses_types', 'client_id',
               existing_type=sa.BigInteger(),
               type_=sa.INTEGER(),
               existing_comment='Идентификатор типа статуса в системе клиента',
               existing_nullable=True)
    op.alter_column('complex_services', 'client_id',
               existing_type=sa.BigInteger(),
               type_=sa.INTEGER(),
               existing_comment='Идентификатор услуги в системе Клиента',
               existing_nullable=True)
    op.alter_column('access_tickets', 'client_id',
               existing_type=sa.BigInteger(),
               type_=sa.INTEGER(),
               existing_comment='Идентификатор номерка в системе клиента',
               existing_nullable=True)
    # ### end Alembic commands ###
