"""Added new tables

Revision ID: c00f01c40a08
Revises: fd0fe77f5c45
Create Date: 2023-11-20 17:19:35.025007

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlalchemy_utils


# revision identifiers, used by Alembic.
revision: str = 'c00f01c40a08'
down_revision: Union[str, None] = 'fd0fe77f5c45'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('shifrs_discounts_periods',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('client_shifr_discount_period_id', sa.Integer(), nullable=True, comment='Идентификатор периода скидок шифра в системе клиента'),
    sa.Column('start_date', sa.DateTime(), nullable=False, comment='Начальная дата периода'),
    sa.Column('end_date', sa.DateTime(), nullable=False, comment='Конечная дата периода'),
    sa.PrimaryKeyConstraint('id'),
    comment='Таблица "Периоды действия скидок шифров"'
    )
    op.create_index(op.f('ix_shifrs_discounts_periods_id'), 'shifrs_discounts_periods', ['id'], unique=False)
    op.create_table('shifrs_discounts',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('client_shifr_discount_id', sa.Integer(), nullable=True, comment='идентификатор скидки шифра в системе клиента'),
    sa.Column('shift_discount_period_id', sa.Integer(), nullable=True, comment='идентификатор периода скидок шифра'),
    sa.Column('service_group_id', sa.Integer(), nullable=False, comment='Идентификатор группы прейскуранта, если тэг = 2'),
    sa.Column('service_id', sa.Integer(), nullable=False, comment='Идентификатор услуги, если тэг = 1'),
    sa.Column('shifr_id', sa.Integer(), nullable=True, comment='Идентификатор шифра'),
    sa.Column('comment', sa.Text(), nullable=True, comment='Комментарий'),
    sa.Column('discount_coefficient_a', sa.Float(), nullable=True, comment='Коэффициент скидки для амбулаторий'),
    sa.Column('discount_coefficient_s', sa.Float(), nullable=True, comment='Коэффициент скидки для стационара'),
    sa.ForeignKeyConstraint(['service_group_id'], ['services_groups.id'], ),
    sa.ForeignKeyConstraint(['service_id'], ['services.id'], ),
    sa.ForeignKeyConstraint(['shifr_id'], ['shifrs.id'], ),
    sa.ForeignKeyConstraint(['shift_discount_period_id'], ['shifrs_discounts_periods.id'], ),
    sa.PrimaryKeyConstraint('id'),
    comment='Таблица "Скидки шифров"'
    )
    op.create_index(op.f('ix_shifrs_discounts_id'), 'shifrs_discounts', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_shifrs_discounts_id'), table_name='shifrs_discounts')
    op.drop_table('shifrs_discounts')
    op.drop_index(op.f('ix_shifrs_discounts_periods_id'), table_name='shifrs_discounts_periods')
    op.drop_table('shifrs_discounts_periods')
    # ### end Alembic commands ###
