"""users_documents_requests has been added_3!

Revision ID: c1558005e4a3
Revises: 7d1e3c427310
Create Date: 2024-04-13 21:06:33.550921

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlalchemy_utils


# revision identifiers, used by Alembic.
revision: str = 'c1558005e4a3'
down_revision: Union[str, None] = '7d1e3c427310'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users_documents_requests', sa.Column('requesr_date', sa.DateTime(), nullable=True, comment='Дата запроса документа'))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users_documents_requests', 'requesr_date')
    # ### end Alembic commands ###
