"""string to ltree has been done_2!

Revision ID: c19bac568382
Revises: 4cb64ff1dc54
Create Date: 2023-11-11 23:06:06.775932

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlalchemy_utils


# revision identifiers, used by Alembic.
revision: str = 'c19bac568382'
down_revision: Union[str, None] = '4cb64ff1dc54'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('nodes', sa.Column('path', sqlalchemy_utils.types.ltree.LtreeType(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('nodes', 'path')
    # ### end Alembic commands ###
