"""Initialisation is ok

Revision ID: c1e4dd44fa9a
Revises: 
Create Date: 2023-09-14 17:09:41.564568

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlalchemy_utils


# revision identifiers, used by Alembic.
revision: str = 'c1e4dd44fa9a'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('admin_users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('email', sa.String(length=100), nullable=False),
    sa.Column('mobile', sa.String(length=25), nullable=False),
    sa.Column('password', sa.String(length=50), nullable=False),
    sa.Column('first_name', sa.String(length=100), nullable=True),
    sa.Column('last_name', sa.String(length=100), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('is_verified', sa.Boolean(), nullable=True),
    sa.Column('is_superuser', sa.Boolean(), nullable=True),
    sa.Column('created', sa.DateTime(timezone=True), nullable=True),
    sa.Column('birth_date', sa.Date(), nullable=True),
    sa.Column('gender', sa.String(length=1), nullable=True),
    sa.Column('last_login', sa.DateTime(), nullable=True),
    sa.Column('last_visit', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_admin_users_id'), 'admin_users', ['id'], unique=False)
    op.create_table('cities',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('client_city_id', sa.Integer(), nullable=True),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_cities_id'), 'cities', ['id'], unique=False)
    op.create_table('medical_departments',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('client_department_id', sa.Integer(), nullable=True),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_medical_departments_id'), 'medical_departments', ['id'], unique=False)
    op.create_table('medical_specialities',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('client_doctor_speciality_id', sa.Integer(), nullable=True),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_medical_specialities_id'), 'medical_specialities', ['id'], unique=False)
    op.create_table('relationship_degreeses',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('client_relationship_degrees_id', sa.Integer(), nullable=True),
    sa.Column('name', sa.String(length=10), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_relationship_degreeses_id'), 'relationship_degreeses', ['id'], unique=False)
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('client_user_id', sa.Integer(), nullable=True),
    sa.Column('client_card_id', sa.Integer(), nullable=True),
    sa.Column('client_personal_area_id', sa.Integer(), nullable=True),
    sa.Column('first_name', sa.String(length=100), nullable=True),
    sa.Column('last_name', sa.String(length=100), nullable=True),
    sa.Column('patronymic', sa.String(length=100), nullable=True),
    sa.Column('birth_date', sa.Date(), nullable=True),
    sa.Column('gender', sa.String(length=1), nullable=True),
    sa.Column('email', sa.String(length=100), nullable=True),
    sa.Column('phone_number', sa.String(length=25), nullable=False),
    sa.Column('additional_phone_number', sa.String(length=25), nullable=True),
    sa.Column('password', sa.String(length=50), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('is_verified', sa.Boolean(), nullable=True),
    sa.Column('created', sa.DateTime(), nullable=True),
    sa.Column('last_login', sa.DateTime(), nullable=True),
    sa.Column('last_visit', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('phone_number')
    )
    op.create_index(op.f('ix_users_id'), 'users', ['id'], unique=False)
    op.create_table('medical_centers',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('client_mcenter_id', sa.Integer(), nullable=True),
    sa.Column('city_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('address', sa.String(length=200), nullable=False),
    sa.Column('longitude', sa.Float(), nullable=True),
    sa.Column('latitude', sa.Float(), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('inn', sa.String(length=20), nullable=False),
    sa.Column('bank_bic', sa.String(length=20), nullable=False),
    sa.Column('settlement_account', sa.String(length=40), nullable=False),
    sa.Column('correspondent_account', sa.String(length=40), nullable=False),
    sa.Column('kpp', sa.String(length=40), nullable=False),
    sa.ForeignKeyConstraint(['city_id'], ['cities.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_medical_centers_id'), 'medical_centers', ['id'], unique=False)
    op.create_table('user_relatives',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('user_relative_id', sa.Integer(), nullable=False),
    sa.Column('relationship_degree_id', sa.Integer(), nullable=False),
    sa.Column('is_legal_agent', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['relationship_degree_id'], ['relationship_degreeses.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['user_relative_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_user_relatives_id'), 'user_relatives', ['id'], unique=False)
    op.create_table('doctors',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('client_doctor_id', sa.Integer(), nullable=True),
    sa.Column('medical_center_id', sa.Integer(), nullable=False),
    sa.Column('medical_department_id', sa.Integer(), nullable=False),
    sa.Column('doctor_mspeciality_id', sa.Integer(), nullable=False),
    sa.Column('fio', sa.String(length=300), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('photo', sa.String(length=100), nullable=True),
    sa.ForeignKeyConstraint(['doctor_mspeciality_id'], ['medical_specialities.id'], ),
    sa.ForeignKeyConstraint(['medical_center_id'], ['medical_centers.id'], ),
    sa.ForeignKeyConstraint(['medical_department_id'], ['medical_departments.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_doctors_id'), 'doctors', ['id'], unique=False)
    op.create_table('mcenters_mdepartments',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('medical_center_id', sa.Integer(), nullable=False),
    sa.Column('medical_department_id', sa.Integer(), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['medical_center_id'], ['medical_centers.id'], ),
    sa.ForeignKeyConstraint(['medical_department_id'], ['medical_departments.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_mcenters_mdepartments_id'), 'mcenters_mdepartments', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_mcenters_mdepartments_id'), table_name='mcenters_mdepartments')
    op.drop_table('mcenters_mdepartments')
    op.drop_index(op.f('ix_doctors_id'), table_name='doctors')
    op.drop_table('doctors')
    op.drop_index(op.f('ix_user_relatives_id'), table_name='user_relatives')
    op.drop_table('user_relatives')
    op.drop_index(op.f('ix_medical_centers_id'), table_name='medical_centers')
    op.drop_table('medical_centers')
    op.drop_index(op.f('ix_users_id'), table_name='users')
    op.drop_table('users')
    op.drop_index(op.f('ix_relationship_degreeses_id'), table_name='relationship_degreeses')
    op.drop_table('relationship_degreeses')
    op.drop_index(op.f('ix_medical_specialities_id'), table_name='medical_specialities')
    op.drop_table('medical_specialities')
    op.drop_index(op.f('ix_medical_departments_id'), table_name='medical_departments')
    op.drop_table('medical_departments')
    op.drop_index(op.f('ix_cities_id'), table_name='cities')
    op.drop_table('cities')
    op.drop_index(op.f('ix_admin_users_id'), table_name='admin_users')
    op.drop_table('admin_users')
    # ### end Alembic commands ###
