"""changing for subscribes have been added_3!

Revision ID: ceb10bf0e4ba
Revises: bf61bb1d0b30
Create Date: 2024-02-21 15:50:51.291974

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlalchemy_utils


# revision identifiers, used by Alembic.
revision: str = 'ceb10bf0e4ba'
down_revision: Union[str, None] = 'bf61bb1d0b30'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
