"""string to ltree has been done!

Revision ID: cee8956e3b10
Revises: b16de6948932
Create Date: 2023-11-11 23:03:53.034279

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlalchemy_utils


# revision identifiers, used by Alembic.
revision: str = 'cee8956e3b10'
down_revision: Union[str, None] = 'b16de6948932'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_nodes_path', table_name='nodes')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index('ix_nodes_path', 'nodes', ['path'], unique=False)
    # ### end Alembic commands ###
