"""payments_type has been added to the initpro_payments_receipts!

Revision ID: d11fb63132fc
Revises: 83cca31d1080
Create Date: 2024-04-06 15:17:43.220094

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlalchemy_utils


# revision identifiers, used by Alembic.
revision: str = 'd11fb63132fc'
down_revision: Union[str, None] = '83cca31d1080'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('initpro_payments_receipts', sa.Column('initpro_payment_type', sa.Integer(), nullable=False, comment='Вид оплаты в системе Инитпро'))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('initpro_payments_receipts', 'initpro_payment_type')
    # ### end Alembic commands ###
