"""Stanislav modifications have been added!

Revision ID: d38edaf29b97
Revises: 2f690ea196ea
Create Date: 2023-12-07 12:17:33.083502

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlalchemy_utils


# revision identifiers, used by Alembic.
revision: str = 'd38edaf29b97'
down_revision: Union[str, None] = '2f690ea196ea'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('doctors_private_phone_key', 'doctors', type_='unique')
    op.drop_constraint('medical_positions_view_name_key', 'medical_positions', type_='unique')
    op.drop_constraint('medical_specialities_view_name_key', 'medical_specialities', type_='unique')
    op.create_table_comment(
        'prices_names',
        'Таблица "Наименования прайсов"',
        existing_comment='Таблица "Наименвоания прайсов"',
        schema=None
    )
    op.add_column('relationship_degreeses', sa.Column('description', sa.Text(), nullable=True, comment='Описание'))
    op.add_column('relationship_degreeses', sa.Column('is_active', sa.Boolean(), nullable=True, comment='Флаг активно/неактивно'))
    op.alter_column('services', 'name_for_staff',
               existing_type=sa.VARCHAR(length=200),
               type_=sa.String(length=512),
               existing_comment='Наименование услуги для персонала',
               existing_nullable=False)
    op.alter_column('services', 'name_for_mz',
               existing_type=sa.VARCHAR(length=200),
               type_=sa.String(length=512),
               existing_comment='Наименование услуги для минздрава',
               existing_nullable=False)
    op.alter_column('services', 'name_for_lk',
               existing_type=sa.VARCHAR(length=200),
               type_=sa.String(length=512),
               existing_comment='Наименование услуги для личного кабинета',
               existing_nullable=False)
    op.alter_column('services', 'minimal_age',
               existing_type=sa.INTEGER(),
               nullable=True,
               existing_comment='Минимальный возраст пациента')
    op.alter_column('services', 'maximal_age',
               existing_type=sa.INTEGER(),
               nullable=True,
               existing_comment='Максимальный возраст пациента')
    op.drop_column('shifrs', 'status')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('shifrs', sa.Column('status', sa.INTEGER(), autoincrement=False, nullable=False, comment='Статус шифра'))
    op.alter_column('services', 'maximal_age',
               existing_type=sa.INTEGER(),
               nullable=False,
               existing_comment='Максимальный возраст пациента')
    op.alter_column('services', 'minimal_age',
               existing_type=sa.INTEGER(),
               nullable=False,
               existing_comment='Минимальный возраст пациента')
    op.alter_column('services', 'name_for_lk',
               existing_type=sa.String(length=512),
               type_=sa.VARCHAR(length=200),
               existing_comment='Наименование услуги для личного кабинета',
               existing_nullable=False)
    op.alter_column('services', 'name_for_mz',
               existing_type=sa.String(length=512),
               type_=sa.VARCHAR(length=200),
               existing_comment='Наименование услуги для минздрава',
               existing_nullable=False)
    op.alter_column('services', 'name_for_staff',
               existing_type=sa.String(length=512),
               type_=sa.VARCHAR(length=200),
               existing_comment='Наименование услуги для персонала',
               existing_nullable=False)
    op.drop_column('relationship_degreeses', 'is_active')
    op.drop_column('relationship_degreeses', 'description')
    op.create_table_comment(
        'prices_names',
        'Таблица "Наименвоания прайсов"',
        existing_comment='Таблица "Наименования прайсов"',
        schema=None
    )
    op.create_unique_constraint('medical_specialities_view_name_key', 'medical_specialities', ['view_name'])
    op.create_unique_constraint('medical_positions_view_name_key', 'medical_positions', ['view_name'])
    op.create_unique_constraint('doctors_private_phone_key', 'doctors', ['private_phone'])
    # ### end Alembic commands ###
