"""AddressMisKladrTable has been added!

Revision ID: d5ce15638706
Revises: 5ac97af58dd4
Create Date: 2023-12-04 15:23:55.349432

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlalchemy_utils


# revision identifiers, used by Alembic.
revision: str = 'd5ce15638706'
down_revision: Union[str, None] = '5ac97af58dd4'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('address_mis_kladr',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('client_address_mis_kladr_id', sa.Integer(), nullable=True, comment='Идентификатор записи в таблице ADDRS в системе клиента'),
    sa.Column('client_user_id', sa.Integer(), nullable=True, comment='Идентификатор пользователя в системе клиента'),
    sa.Column('tag', sa.Integer(), nullable=True, comment='1 - прописка; 2 - проживание'),
    sa.Column('luid', sa.Integer(), nullable=True, comment='Тип адреса (LU.TAG = 1)'),
    sa.Column('region', sa.String(length=128), nullable=True, comment='Субъект РФ или страна'),
    sa.Column('region_code', sa.String(length=32), nullable=True, comment='Код субъекта РФ или страны'),
    sa.Column('area', sa.String(length=128), nullable=True, comment='Область'),
    sa.Column('area_code', sa.String(length=32), nullable=True, comment='Код области'),
    sa.Column('city', sa.String(length=128), nullable=True, comment='Город'),
    sa.Column('city_code', sa.String(length=32), nullable=True, comment='Код города'),
    sa.Column('town', sa.String(length=128), nullable=True, comment='Населенный пункт (не город)'),
    sa.Column('town_code', sa.String(length=32), nullable=True, comment='Код населенного пункта'),
    sa.Column('street', sa.String(length=128), nullable=True, comment='Улица'),
    sa.Column('street_code', sa.String(length=32), nullable=True, comment='Код улицы'),
    sa.Column('house', sa.String(length=100), nullable=True, comment='Дом'),
    sa.Column('corp', sa.String(length=20), nullable=True, comment='Корпус'),
    sa.Column('flat', sa.String(length=10), nullable=True, comment='Квартира'),
    sa.Column('note', sa.String(length=256), nullable=True, comment='Комментарий к адресу'),
    sa.Column('status', sa.Integer(), nullable=True, comment='Статус: 0 - архивный, 1 - активный'),
    sa.Column('lives_lu_id', sa.Integer(), nullable=True, comment='Место проживания (городской или сельский житела)'),
    sa.Column('house_code', sa.String(length=32), nullable=True, comment='Код дома'),
    sa.PrimaryKeyConstraint('id'),
    comment='Таблица-справочник "ADDRS"'
    )
    op.create_index(op.f('ix_address_mis_kladr_id'), 'address_mis_kladr', ['id'], unique=False)
    op.create_foreign_key(None, 'users', 'address_mis_kladr', ['address_mis_kladr_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'users', type_='foreignkey')
    op.drop_index(op.f('ix_address_mis_kladr_id'), table_name='address_mis_kladr')
    op.drop_table('address_mis_kladr')
    # ### end Alembic commands ###
