"""Two new tables have been added

Revision ID: d67b19f3fefa
Revises: ba9d2c68f223
Create Date: 2024-02-16 19:27:43.516147

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlalchemy_utils


# revision identifiers, used by Alembic.
revision: str = 'd67b19f3fefa'
down_revision: Union[str, None] = 'ba9d2c68f223'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('lpus',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('client_id', sa.BigInteger(), nullable=True, comment='Идентификатор записи в системе клиента'),
    sa.Column('name', sa.String(length=200), nullable=False, comment='Наименование ЛПУ'),
    sa.Column('description', sa.Text(), nullable=True, comment='Описание ЛПУ'),
    sa.Column('start_date', sa.DateTime(), nullable=True, comment='Дата и время начала использования'),
    sa.Column('end_date', sa.DateTime(), nullable=True, comment='Дата и время окончания использования'),
    sa.Column('is_active', sa.Boolean(), nullable=True, comment='Флаг активно/неактивно'),
    sa.PrimaryKeyConstraint('id'),
    comment='Таблица "Лечебныо-профилактические учреждения"'
    )
    op.create_index(op.f('ix_lpus_id'), 'lpus', ['id'], unique=False)
    op.create_table('policies_payments_plans',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('client_id', sa.BigInteger(), nullable=True, comment='Идентификатор записи в системе клиента'),
    sa.Column('policy_id', sa.Integer(), nullable=False, comment='Идентификатор полиса'),
    sa.Column('planed_date', sa.DateTime(), nullable=False, comment='Дата оплаты по плану'),
    sa.Column('amount', sa.Float(), nullable=False, comment='Планируемая сумма оплаты'),
    sa.ForeignKeyConstraint(['policy_id'], ['policies.id'], ),
    sa.PrimaryKeyConstraint('id'),
    comment='Таблица "График платежей по полису"'
    )
    op.create_index(op.f('ix_policies_payments_plans_id'), 'policies_payments_plans', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_policies_payments_plans_id'), table_name='policies_payments_plans')
    op.drop_table('policies_payments_plans')
    op.drop_index(op.f('ix_lpus_id'), table_name='lpus')
    op.drop_table('lpus')
    # ### end Alembic commands ###
