"""the lpu_client_id field has been added to initpro_payments_receipts!

Revision ID: d8a7dd10587e
Revises: d11fb63132fc
Create Date: 2024-04-07 12:14:16.668328

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlalchemy_utils


# revision identifiers, used by Alembic.
revision: str = 'd8a7dd10587e'
down_revision: Union[str, None] = 'd11fb63132fc'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('initpro_payments_receipts', sa.Column('lpu_client_id', sa.BigInteger(), nullable=True, comment='Идентификатор lpu в системе клиента'))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('initpro_payments_receipts', 'lpu_client_id')
    # ### end Alembic commands ###
