"""price_id has been changed to nullable=True!

Revision ID: d9c12c87c0c6
Revises: 969bb0a0e61a
Create Date: 2024-04-12 11:01:55.599334

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlalchemy_utils


# revision identifiers, used by Alembic.
revision: str = 'd9c12c87c0c6'
down_revision: Union[str, None] = '969bb0a0e61a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('users_services_carts', 'price_id',
               existing_type=sa.INTEGER(),
               nullable=True,
               existing_comment='Идентификатор прайсовой стоимости услуги')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('users_services_carts', 'price_id',
               existing_type=sa.INTEGER(),
               nullable=False,
               existing_comment='Идентификатор прайсовой стоимости услуги')
    # ### end Alembic commands ###
