"""ltree to string has been done_3!

Revision ID: d9d849924fb3
Revises: d2534ccb1114
Create Date: 2023-11-11 23:12:04.541894

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlalchemy_utils


# revision identifiers, used by Alembic.
revision: str = 'd9d849924fb3'
down_revision: Union[str, None] = 'd2534ccb1114'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_nodes_path', table_name='nodes')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index('ix_nodes_path', 'nodes', ['path'], unique=False)
    # ### end Alembic commands ###
