"""users_purchases has been changed!

Revision ID: dae92e85f87f
Revises: b673a0d79a26
Create Date: 2024-01-24 14:19:51.691475

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlalchemy_utils


# revision identifiers, used by Alembic.
revision: str = 'dae92e85f87f'
down_revision: Union[str, None] = 'b673a0d79a26'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users_purchases', sa.Column('doctor_mcenter_exec_id', sa.Integer(), nullable=True, comment='Идентификатор доктора, выполнившего услугу'))
    op.add_column('users_purchases', sa.Column('doctor_mcenter_nurse_id', sa.Integer(), nullable=True, comment='Идентификатор медсестры, выполнившей услугу'))
    op.drop_constraint('users_purchases_doctor_exec_id_fkey', 'users_purchases', type_='foreignkey')
    op.drop_constraint('users_purchases_doctor_nurse_id_fkey', 'users_purchases', type_='foreignkey')
    op.create_foreign_key(None, 'users_purchases', 'doctors_medical_centers', ['doctor_mcenter_exec_id'], ['id'])
    op.create_foreign_key(None, 'users_purchases', 'doctors_medical_centers', ['doctor_mcenter_nurse_id'], ['id'])
    op.drop_column('users_purchases', 'doctor_nurse_id')
    op.drop_column('users_purchases', 'doctor_exec_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users_purchases', sa.Column('doctor_exec_id', sa.INTEGER(), autoincrement=False, nullable=True, comment='Идентификатор доктора, выполнившего услугу'))
    op.add_column('users_purchases', sa.Column('doctor_nurse_id', sa.INTEGER(), autoincrement=False, nullable=True, comment='Идентификатор медсестры, выполнившей услугу'))
    op.drop_constraint(None, 'users_purchases', type_='foreignkey')
    op.drop_constraint(None, 'users_purchases', type_='foreignkey')
    op.create_foreign_key('users_purchases_doctor_nurse_id_fkey', 'users_purchases', 'doctors_medical_centers', ['doctor_nurse_id'], ['id'])
    op.create_foreign_key('users_purchases_doctor_exec_id_fkey', 'users_purchases', 'doctors_medical_centers', ['doctor_exec_id'], ['id'])
    op.drop_column('users_purchases', 'doctor_mcenter_nurse_id')
    op.drop_column('users_purchases', 'doctor_mcenter_exec_id')
    # ### end Alembic commands ###
