"""Added index to all client_id fields!

Revision ID: de239574e1fd
Revises: 744f270675fe
Create Date: 2024-04-01 10:29:08.947283

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlalchemy_utils


# revision identifiers, used by Alembic.
revision: str = 'de239574e1fd'
down_revision: Union[str, None] = '744f270675fe'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(op.f('ix_address_mis_kladr_client_id'), 'address_mis_kladr', ['client_id'], unique=False)
    op.create_index(op.f('ix_cities_client_id'), 'cities', ['client_id'], unique=False)
    op.create_index(op.f('ix_complex_services_client_id'), 'complex_services', ['client_id'], unique=False)
    op.create_index(op.f('ix_doctor_statuses_types_client_id'), 'doctor_statuses_types', ['client_id'], unique=False)
    op.create_index(op.f('ix_doctors_client_id'), 'doctors', ['client_id'], unique=False)
    op.create_index(op.f('ix_doctors_categories_client_id'), 'doctors_categories', ['client_id'], unique=False)
    op.create_index(op.f('ix_doctors_mcenters_services_client_id'), 'doctors_mcenters_services', ['client_id'], unique=False)
    op.create_index(op.f('ix_doctors_medical_centers_client_id'), 'doctors_medical_centers', ['client_id'], unique=False)
    op.create_index(op.f('ix_doctors_patients_types_client_id'), 'doctors_patients_types', ['client_id'], unique=False)
    op.create_index(op.f('ix_doctors_replacements_client_id'), 'doctors_replacements', ['client_id'], unique=False)
    op.create_index(op.f('ix_financial_types_client_id'), 'financial_types', ['client_id'], unique=False)
    op.create_index(op.f('ix_information_ways_client_id'), 'information_ways', ['client_id'], unique=False)
    op.create_index(op.f('ix_lpus_client_id'), 'lpus', ['client_id'], unique=False)
    op.create_index(op.f('ix_mcenters_price_names_client_id'), 'mcenters_price_names', ['client_id'], unique=False)
    op.create_index(op.f('ix_medical_centers_client_id'), 'medical_centers', ['client_id'], unique=False)
    op.create_index(op.f('ix_medical_positions_client_id'), 'medical_positions', ['client_id'], unique=False)
    op.create_index(op.f('ix_medical_specialities_client_id'), 'medical_specialities', ['client_id'], unique=False)
    op.create_index(op.f('ix_notifications_ways_client_id'), 'notifications_ways', ['client_id'], unique=False)
    op.create_index(op.f('ix_packs_types_client_id'), 'packs_types', ['client_id'], unique=False)
    op.create_index(op.f('ix_patients_types_client_id'), 'patients_types', ['client_id'], unique=False)
    op.create_index(op.f('ix_payments_types_client_id'), 'payments_types', ['client_id'], unique=False)
    op.create_index(op.f('ix_policies_client_id'), 'policies', ['client_id'], unique=False)
    op.create_index(op.f('ix_policies_payments_plans_client_id'), 'policies_payments_plans', ['client_id'], unique=False)
    op.create_index(op.f('ix_prices_client_id'), 'prices', ['client_id'], unique=False)
    op.create_index(op.f('ix_prices_names_client_id'), 'prices_names', ['client_id'], unique=False)
    op.create_index(op.f('ix_prices_periods_client_id'), 'prices_periods', ['client_id'], unique=False)
    op.create_index(op.f('ix_refuses_reasons_client_id'), 'refuses_reasons', ['client_id'], unique=False)
    op.create_index(op.f('ix_relationship_degreeses_client_id'), 'relationship_degreeses', ['client_id'], unique=False)
    op.create_index(op.f('ix_services_client_id'), 'services', ['client_id'], unique=False)
    op.create_index(op.f('ix_services_groups_client_id'), 'services_groups', ['client_id'], unique=False)
    op.create_index(op.f('ix_services_mspecialities_client_id'), 'services_mspecialities', ['client_id'], unique=False)
    op.create_index(op.f('ix_services_types_client_id'), 'services_types', ['client_id'], unique=False)
    op.create_index(op.f('ix_shifrs_client_id'), 'shifrs', ['client_id'], unique=False)
    op.create_index(op.f('ix_shifrs_discounts_client_id'), 'shifrs_discounts', ['client_id'], unique=False)
    op.create_index(op.f('ix_shifrs_discounts_periods_client_id'), 'shifrs_discounts_periods', ['client_id'], unique=False)
    op.create_index(op.f('ix_staff_types_client_id'), 'staff_types', ['client_id'], unique=False)
    op.create_index(op.f('ix_subscribe_roles_client_id'), 'subscribe_roles', ['client_id'], unique=False)
    op.create_index(op.f('ix_subscribes_doctors_client_id'), 'subscribes_doctors', ['client_id'], unique=False)
    op.create_index(op.f('ix_subscribes_services_packs_client_id'), 'subscribes_services_packs', ['client_id'], unique=False)
    op.create_index(op.f('ix_subscribes_spacks_records_client_id'), 'subscribes_spacks_records', ['client_id'], unique=False)
    op.create_index(op.f('ix_users_client_id'), 'users', ['client_id'], unique=False)
    op.create_index(op.f('ix_users_notifications_ways_client_id'), 'users_notifications_ways', ['client_id'], unique=False)
    op.create_index(op.f('ix_users_payments_client_id'), 'users_payments', ['client_id'], unique=False)
    op.create_index(op.f('ix_users_purchases_client_id'), 'users_purchases', ['client_id'], unique=False)
    op.create_index(op.f('ix_users_purchases_returns_client_id'), 'users_purchases_returns', ['client_id'], unique=False)
    op.create_index(op.f('ix_users_relatives_client_id'), 'users_relatives', ['client_id'], unique=False)
    op.create_index(op.f('ix_users_services_carts_client_id'), 'users_services_carts', ['client_id'], unique=False)
    op.create_index(op.f('ix_users_services_plans_client_id'), 'users_services_plans', ['client_id'], unique=False)
    op.create_index(op.f('ix_users_subscribes_client_id'), 'users_subscribes', ['client_id'], unique=False)
    op.create_index(op.f('ix_users_used_advances_client_id'), 'users_used_advances', ['client_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_users_used_advances_client_id'), table_name='users_used_advances')
    op.drop_index(op.f('ix_users_subscribes_client_id'), table_name='users_subscribes')
    op.drop_index(op.f('ix_users_services_plans_client_id'), table_name='users_services_plans')
    op.drop_index(op.f('ix_users_services_carts_client_id'), table_name='users_services_carts')
    op.drop_index(op.f('ix_users_relatives_client_id'), table_name='users_relatives')
    op.drop_index(op.f('ix_users_purchases_returns_client_id'), table_name='users_purchases_returns')
    op.drop_index(op.f('ix_users_purchases_client_id'), table_name='users_purchases')
    op.drop_index(op.f('ix_users_payments_client_id'), table_name='users_payments')
    op.drop_index(op.f('ix_users_notifications_ways_client_id'), table_name='users_notifications_ways')
    op.drop_index(op.f('ix_users_client_id'), table_name='users')
    op.drop_index(op.f('ix_subscribes_spacks_records_client_id'), table_name='subscribes_spacks_records')
    op.drop_index(op.f('ix_subscribes_services_packs_client_id'), table_name='subscribes_services_packs')
    op.drop_index(op.f('ix_subscribes_doctors_client_id'), table_name='subscribes_doctors')
    op.drop_index(op.f('ix_subscribe_roles_client_id'), table_name='subscribe_roles')
    op.drop_index(op.f('ix_staff_types_client_id'), table_name='staff_types')
    op.drop_index(op.f('ix_shifrs_discounts_periods_client_id'), table_name='shifrs_discounts_periods')
    op.drop_index(op.f('ix_shifrs_discounts_client_id'), table_name='shifrs_discounts')
    op.drop_index(op.f('ix_shifrs_client_id'), table_name='shifrs')
    op.drop_index(op.f('ix_services_types_client_id'), table_name='services_types')
    op.drop_index(op.f('ix_services_mspecialities_client_id'), table_name='services_mspecialities')
    op.drop_index(op.f('ix_services_groups_client_id'), table_name='services_groups')
    op.drop_index(op.f('ix_services_client_id'), table_name='services')
    op.drop_index(op.f('ix_relationship_degreeses_client_id'), table_name='relationship_degreeses')
    op.drop_index(op.f('ix_refuses_reasons_client_id'), table_name='refuses_reasons')
    op.drop_index(op.f('ix_prices_periods_client_id'), table_name='prices_periods')
    op.drop_index(op.f('ix_prices_names_client_id'), table_name='prices_names')
    op.drop_index(op.f('ix_prices_client_id'), table_name='prices')
    op.drop_index(op.f('ix_policies_payments_plans_client_id'), table_name='policies_payments_plans')
    op.drop_index(op.f('ix_policies_client_id'), table_name='policies')
    op.drop_index(op.f('ix_payments_types_client_id'), table_name='payments_types')
    op.drop_index(op.f('ix_patients_types_client_id'), table_name='patients_types')
    op.drop_index(op.f('ix_packs_types_client_id'), table_name='packs_types')
    op.drop_index(op.f('ix_notifications_ways_client_id'), table_name='notifications_ways')
    op.drop_index(op.f('ix_medical_specialities_client_id'), table_name='medical_specialities')
    op.drop_index(op.f('ix_medical_positions_client_id'), table_name='medical_positions')
    op.drop_index(op.f('ix_medical_centers_client_id'), table_name='medical_centers')
    op.drop_index(op.f('ix_mcenters_price_names_client_id'), table_name='mcenters_price_names')
    op.drop_index(op.f('ix_lpus_client_id'), table_name='lpus')
    op.drop_index(op.f('ix_information_ways_client_id'), table_name='information_ways')
    op.drop_index(op.f('ix_financial_types_client_id'), table_name='financial_types')
    op.drop_index(op.f('ix_doctors_replacements_client_id'), table_name='doctors_replacements')
    op.drop_index(op.f('ix_doctors_patients_types_client_id'), table_name='doctors_patients_types')
    op.drop_index(op.f('ix_doctors_medical_centers_client_id'), table_name='doctors_medical_centers')
    op.drop_index(op.f('ix_doctors_mcenters_services_client_id'), table_name='doctors_mcenters_services')
    op.drop_index(op.f('ix_doctors_categories_client_id'), table_name='doctors_categories')
    op.drop_index(op.f('ix_doctors_client_id'), table_name='doctors')
    op.drop_index(op.f('ix_doctor_statuses_types_client_id'), table_name='doctor_statuses_types')
    op.drop_index(op.f('ix_complex_services_client_id'), table_name='complex_services')
    op.drop_index(op.f('ix_cities_client_id'), table_name='cities')
    op.drop_index(op.f('ix_address_mis_kladr_client_id'), table_name='address_mis_kladr')
    # ### end Alembic commands ###
