"""Edited users_purchases!

Revision ID: df96808e55af
Revises: fff86357ff26
Create Date: 2023-11-30 17:41:44.608363

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlalchemy_utils
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'df96808e55af'
down_revision: Union[str, None] = 'fff86357ff26'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('users_purchases', 'policy_id',
               existing_type=sa.INTEGER(),
               nullable=True,
               existing_comment='Идентификатор полиса')
    op.alter_column('users_purchases', 'user_payment_id',
               existing_type=sa.INTEGER(),
               nullable=True,
               existing_comment='Идентификатор платежа пользовталя, СДЕЛАТЬ ForeignKey')
    op.alter_column('users_purchases', 'payment_date',
               existing_type=postgresql.TIMESTAMP(),
               nullable=True,
               existing_comment='Дата и время платежа')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('users_purchases', 'payment_date',
               existing_type=postgresql.TIMESTAMP(),
               nullable=False,
               existing_comment='Дата и время платежа')
    op.alter_column('users_purchases', 'user_payment_id',
               existing_type=sa.INTEGER(),
               nullable=False,
               existing_comment='Идентификатор платежа пользовталя, СДЕЛАТЬ ForeignKey')
    op.alter_column('users_purchases', 'policy_id',
               existing_type=sa.INTEGER(),
               nullable=False,
               existing_comment='Идентификатор полиса')
    # ### end Alembic commands ###
