"""date index has been changed!

Revision ID: e09241fcfa20
Revises: ae9f62a80164
Create Date: 2024-04-01 13:59:18.892869

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlalchemy_utils


# revision identifiers, used by Alembic.
revision: str = 'e09241fcfa20'
down_revision: Union[str, None] = 'ae9f62a80164'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('idx_date', table_name='access_tickets')
    op.create_index('idx_date', 'access_tickets', [sa.text('date(ticket_datetime)')], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('idx_date', table_name='access_tickets')
    op.create_index('idx_date', 'access_tickets', [sa.text("date_trunc('day'::text, ticket_datetime)")], unique=False)
    # ### end Alembic commands ###
