"""admin client_id to unique!

Revision ID: e1ad4591c399
Revises: f2c64f76a97e
Create Date: 2024-05-15 23:47:10.277419

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlalchemy_utils


# revision identifiers, used by Alembic.
revision: str = 'e1ad4591c399'
down_revision: Union[str, None] = 'f2c64f76a97e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(op.f('ix_users_admin_client_id'), 'users_admin', ['client_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_users_admin_client_id'), table_name='users_admin')
    # ### end Alembic commands ###
