"""as_dict has been added to User and MedicalCenter

Revision ID: e1e0da4bb80b
Revises: e21777a5b911
Create Date: 2024-03-07 22:07:15.344755

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlalchemy_utils


# revision identifiers, used by Alembic.
revision: str = 'e1e0da4bb80b'
down_revision: Union[str, None] = 'e21777a5b911'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
