"""some comment has been changed!

Revision ID: e21777a5b911
Revises: 7c4a18c21eda
Create Date: 2024-03-07 02:55:27.780886

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlalchemy_utils


# revision identifiers, used by Alembic.
revision: str = 'e21777a5b911'
down_revision: Union[str, None] = '7c4a18c21eda'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('paykeeper_payments_data', 'orderid',
               existing_type=sa.VARCHAR(),
               comment='Номер заказа в системе магазина (наш payment_id)',
               existing_comment='Номер заказа в системе магазина (наш payment_client_id)',
               existing_nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('paykeeper_payments_data', 'orderid',
               existing_type=sa.VARCHAR(),
               comment='Номер заказа в системе магазина (наш payment_client_id)',
               existing_comment='Номер заказа в системе магазина (наш payment_id)',
               existing_nullable=False)
    # ### end Alembic commands ###
