"""new fields have been added into the users_documents_requests_1!

Revision ID: e225870bdc51
Revises: 95e927a600a8
Create Date: 2024-04-16 12:31:39.108720

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlalchemy_utils
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'e225870bdc51'
down_revision: Union[str, None] = '95e927a600a8'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users_documents_requests', sa.Column('request_date', sa.DateTime(), nullable=True, comment='Дата запроса документа'))
    op.drop_column('users_documents_requests', 'requesr_date')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users_documents_requests', sa.Column('requesr_date', postgresql.TIMESTAMP(), autoincrement=False, nullable=True, comment='Дата запроса документа'))
    op.drop_column('users_documents_requests', 'request_date')
    # ### end Alembic commands ###
