"""date index has been changed_3!

Revision ID: e547fe207ab0
Revises: f6a6009a41c6
Create Date: 2024-04-01 16:54:30.181746

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlalchemy_utils


# revision identifiers, used by Alembic.
revision: str = 'e547fe207ab0'
down_revision: Union[str, None] = 'f6a6009a41c6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(op.f('ix_access_tickets_doctor_mcenters_id'), 'access_tickets', ['doctor_mcenters_id'], unique=False)
    op.create_index(op.f('ix_doctors_doctor_category_id'), 'doctors', ['doctor_category_id'], unique=False)
    op.create_index(op.f('ix_doctors_medical_centers_doctor_id'), 'doctors_medical_centers', ['doctor_id'], unique=False)
    op.create_index(op.f('ix_doctors_medical_centers_is_active'), 'doctors_medical_centers', ['is_active'], unique=False)
    op.create_index(op.f('ix_doctors_medical_centers_medical_center_id'), 'doctors_medical_centers', ['medical_center_id'], unique=False)
    op.create_index(op.f('ix_doctors_medical_centers_medical_position_id'), 'doctors_medical_centers', ['medical_position_id'], unique=False)
    op.create_index(op.f('ix_doctors_medical_centers_medical_speciality_id'), 'doctors_medical_centers', ['medical_speciality_id'], unique=False)
    op.create_index(op.f('ix_doctors_medical_centers_staff_type_id'), 'doctors_medical_centers', ['staff_type_id'], unique=False)
    op.create_index(op.f('ix_medical_centers_city_id'), 'medical_centers', ['city_id'], unique=False)
    op.create_index(op.f('ix_medical_centers_lpu_id'), 'medical_centers', ['lpu_id'], unique=False)
    op.create_index(op.f('ix_users_address_mis_kladr_id'), 'users', ['address_mis_kladr_id'], unique=False)
    op.create_index(op.f('ix_users_default_medical_center_id'), 'users', ['default_medical_center_id'], unique=False)
    op.create_index(op.f('ix_users_info_way_id'), 'users', ['info_way_id'], unique=False)
    op.create_index(op.f('ix_users_is_active'), 'users', ['is_active'], unique=False)
    op.create_index(op.f('ix_users_pref_notification_contact_id'), 'users', ['pref_notification_contact_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_users_pref_notification_contact_id'), table_name='users')
    op.drop_index(op.f('ix_users_is_active'), table_name='users')
    op.drop_index(op.f('ix_users_info_way_id'), table_name='users')
    op.drop_index(op.f('ix_users_default_medical_center_id'), table_name='users')
    op.drop_index(op.f('ix_users_address_mis_kladr_id'), table_name='users')
    op.drop_index(op.f('ix_medical_centers_lpu_id'), table_name='medical_centers')
    op.drop_index(op.f('ix_medical_centers_city_id'), table_name='medical_centers')
    op.drop_index(op.f('ix_doctors_medical_centers_staff_type_id'), table_name='doctors_medical_centers')
    op.drop_index(op.f('ix_doctors_medical_centers_medical_speciality_id'), table_name='doctors_medical_centers')
    op.drop_index(op.f('ix_doctors_medical_centers_medical_position_id'), table_name='doctors_medical_centers')
    op.drop_index(op.f('ix_doctors_medical_centers_medical_center_id'), table_name='doctors_medical_centers')
    op.drop_index(op.f('ix_doctors_medical_centers_is_active'), table_name='doctors_medical_centers')
    op.drop_index(op.f('ix_doctors_medical_centers_doctor_id'), table_name='doctors_medical_centers')
    op.drop_index(op.f('ix_doctors_doctor_category_id'), table_name='doctors')
    op.drop_index(op.f('ix_access_tickets_doctor_mcenters_id'), table_name='access_tickets')
    # ### end Alembic commands ###
