"""There was added main comment to users table

Revision ID: eb8f8a1ed501
Revises: 4c7397c43189
Create Date: 2023-10-19 11:19:45.085201

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlalchemy_utils


# revision identifiers, used by Alembic.
revision: str = 'eb8f8a1ed501'
down_revision: Union[str, None] = '4c7397c43189'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table_comment(
        'users',
        'Таблица "Пользователи"',
        existing_comment=None,
        schema=None
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table_comment(
        'users',
        existing_comment='Таблица "Пользователи"',
        schema=None
    )
    # ### end Alembic commands ###
