"""Parent_id has been added ok

Revision ID: ebdb45f328f2
Revises: efc3e3ede484
Create Date: 2023-11-10 16:27:10.304977

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlalchemy_utils


# revision identifiers, used by Alembic.
revision: str = 'ebdb45f328f2'
down_revision: Union[str, None] = 'efc3e3ede484'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('nodes', sa.Column('parent_id', sa.Integer(), nullable=True, comment='Идентификатор родителя'))
    op.create_foreign_key(None, 'nodes', 'nodes', ['parent_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'nodes', type_='foreignkey')
    op.drop_column('nodes', 'parent_id')
    # ### end Alembic commands ###
