"""Main process part 2 is ok

Revision ID: edd225745f41
Revises: c1e4dd44fa9a
Create Date: 2023-09-15 13:39:49.342106

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlalchemy_utils


# revision identifiers, used by Alembic.
revision: str = 'edd225745f41'
down_revision: Union[str, None] = 'c1e4dd44fa9a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('services_directions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('client_sdirection_id', sa.Integer(), nullable=True),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_index(op.f('ix_services_directions_id'), 'services_directions', ['id'], unique=False)
    op.create_table('services_types',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('client_stype_id', sa.Integer(), nullable=True),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_index(op.f('ix_services_types_id'), 'services_types', ['id'], unique=False)
    op.create_table('services',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('client_service_id', sa.Integer(), nullable=True),
    sa.Column('service_direction_id', sa.Integer(), nullable=False),
    sa.Column('service_type_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['service_direction_id'], ['services_directions.id'], ),
    sa.ForeignKeyConstraint(['service_type_id'], ['services_types.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_services_id'), 'services', ['id'], unique=False)
    op.create_table('prices',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('client_price_id', sa.Integer(), nullable=True),
    sa.Column('service_id', sa.Integer(), nullable=False),
    sa.Column('medical_center_id', sa.Integer(), nullable=False),
    sa.Column('medical_department_id', sa.Integer(), nullable=False),
    sa.Column('price', sa.Float(), nullable=False),
    sa.ForeignKeyConstraint(['medical_center_id'], ['medical_centers.id'], ),
    sa.ForeignKeyConstraint(['medical_department_id'], ['medical_departments.id'], ),
    sa.ForeignKeyConstraint(['service_id'], ['services.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_prices_id'), 'prices', ['id'], unique=False)
    op.create_table('doctors_services',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('doctor_id', sa.Integer(), nullable=False),
    sa.Column('service_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['doctor_id'], ['doctors.id'], ),
    sa.ForeignKeyConstraint(['service_id'], ['services.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_doctors_services_id'), 'doctors_services', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_doctors_services_id'), table_name='doctors_services')
    op.drop_table('doctors_services')
    op.drop_index(op.f('ix_prices_id'), table_name='prices')
    op.drop_table('prices')
    op.drop_index(op.f('ix_services_id'), table_name='services')
    op.drop_table('services')
    op.drop_index(op.f('ix_services_types_id'), table_name='services_types')
    op.drop_table('services_types')
    op.drop_index(op.f('ix_services_directions_id'), table_name='services_directions')
    op.drop_table('services_directions')
    # ### end Alembic commands ###
