"""node_id has been added to services!

Revision ID: ef98618a7657
Revises: 5c3e0127ad51
Create Date: 2023-11-12 13:03:59.171138

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlalchemy_utils


# revision identifiers, used by Alembic.
revision: str = 'ef98618a7657'
down_revision: Union[str, None] = '5c3e0127ad51'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('services', sa.Column('node_id', sa.Integer(), nullable=True, comment='Идентификатор группы услуги'))
    op.create_foreign_key(None, 'services', 'nodes', ['node_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'services', type_='foreignkey')
    op.drop_column('services', 'node_id')
    # ### end Alembic commands ###
