"""Node has been removed!

Revision ID: f15d80f477be
Revises: 77c11d7ae2ef
Create Date: 2023-11-12 13:20:22.049178

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlalchemy_utils


# revision identifiers, used by Alembic.
revision: str = 'f15d80f477be'
down_revision: Union[str, None] = '77c11d7ae2ef'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_nodes_path', table_name='nodes')
    op.drop_table('nodes')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('nodes',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('name', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('path', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('id', name='nodes_pkey')
    )
    op.create_index('ix_nodes_path', 'nodes', ['path'], unique=False)
    # ### end Alembic commands ###
