"""accounts client_id to unique!

Revision ID: f2c64f76a97e
Revises: 744151c08da5
Create Date: 2024-05-15 23:38:26.726991

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlalchemy_utils


# revision identifiers, used by Alembic.
revision: str = 'f2c64f76a97e'
down_revision: Union[str, None] = '744151c08da5'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_address_mis_kladr_client_id', table_name='address_mis_kladr')
    op.create_index(op.f('ix_address_mis_kladr_client_id'), 'address_mis_kladr', ['client_id'], unique=True)
    op.drop_index('ix_cities_client_id', table_name='cities')
    op.create_index(op.f('ix_cities_client_id'), 'cities', ['client_id'], unique=True)
    op.drop_index('ix_information_ways_client_id', table_name='information_ways')
    op.create_index(op.f('ix_information_ways_client_id'), 'information_ways', ['client_id'], unique=True)
    op.drop_index('ix_lpus_client_id', table_name='lpus')
    op.create_index(op.f('ix_lpus_client_id'), 'lpus', ['client_id'], unique=True)
    op.drop_index('ix_medical_centers_client_id', table_name='medical_centers')
    op.create_index(op.f('ix_medical_centers_client_id'), 'medical_centers', ['client_id'], unique=True)
    op.drop_index('ix_notifications_ways_client_id', table_name='notifications_ways')
    op.create_index(op.f('ix_notifications_ways_client_id'), 'notifications_ways', ['client_id'], unique=True)
    op.drop_index('ix_relationship_degreeses_client_id', table_name='relationship_degreeses')
    op.create_index(op.f('ix_relationship_degreeses_client_id'), 'relationship_degreeses', ['client_id'], unique=True)
    op.drop_index('ix_users_notifications_ways_client_id', table_name='users_notifications_ways')
    op.create_index(op.f('ix_users_notifications_ways_client_id'), 'users_notifications_ways', ['client_id'], unique=True)
    op.drop_index('ix_users_relatives_client_id', table_name='users_relatives')
    op.create_index(op.f('ix_users_relatives_client_id'), 'users_relatives', ['client_id'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_users_relatives_client_id'), table_name='users_relatives')
    op.create_index('ix_users_relatives_client_id', 'users_relatives', ['client_id'], unique=False)
    op.drop_index(op.f('ix_users_notifications_ways_client_id'), table_name='users_notifications_ways')
    op.create_index('ix_users_notifications_ways_client_id', 'users_notifications_ways', ['client_id'], unique=False)
    op.drop_index(op.f('ix_relationship_degreeses_client_id'), table_name='relationship_degreeses')
    op.create_index('ix_relationship_degreeses_client_id', 'relationship_degreeses', ['client_id'], unique=False)
    op.drop_index(op.f('ix_notifications_ways_client_id'), table_name='notifications_ways')
    op.create_index('ix_notifications_ways_client_id', 'notifications_ways', ['client_id'], unique=False)
    op.drop_index(op.f('ix_medical_centers_client_id'), table_name='medical_centers')
    op.create_index('ix_medical_centers_client_id', 'medical_centers', ['client_id'], unique=False)
    op.drop_index(op.f('ix_lpus_client_id'), table_name='lpus')
    op.create_index('ix_lpus_client_id', 'lpus', ['client_id'], unique=False)
    op.drop_index(op.f('ix_information_ways_client_id'), table_name='information_ways')
    op.create_index('ix_information_ways_client_id', 'information_ways', ['client_id'], unique=False)
    op.drop_index(op.f('ix_cities_client_id'), table_name='cities')
    op.create_index('ix_cities_client_id', 'cities', ['client_id'], unique=False)
    op.drop_index(op.f('ix_address_mis_kladr_client_id'), table_name='address_mis_kladr')
    op.create_index('ix_address_mis_kladr_client_id', 'address_mis_kladr', ['client_id'], unique=False)
    # ### end Alembic commands ###
