"""Removed not needed tables!

Revision ID: f519fed9125d
Revises: 9f87ec3a9497
Create Date: 2023-11-16 15:09:32.085541

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlalchemy_utils


# revision identifiers, used by Alembic.
revision: str = 'f519fed9125d'
down_revision: Union[str, None] = '9f87ec3a9497'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_payments_systems_id', table_name='payments_systems')
    op.drop_table('payments_systems')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('payments_systems',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('name', sa.VARCHAR(length=100), autoincrement=False, nullable=False, comment='Наименование платежной системы'),
    sa.Column('description', sa.TEXT(), autoincrement=False, nullable=True, comment='Описание платежной системы'),
    sa.Column('is_active', sa.BOOLEAN(), autoincrement=False, nullable=True, comment='Флаг активан/не активна'),
    sa.PrimaryKeyConstraint('id', name='payments_systems_pkey'),
    sa.UniqueConstraint('name', name='payments_systems_name_key'),
    comment='Таблица "Платёжные системы"'
    )
    op.create_index('ix_payments_systems_id', 'payments_systems', ['id'], unique=False)
    # ### end Alembic commands ###
