"""date index has been changed_2!

Revision ID: f6a6009a41c6
Revises: e09241fcfa20
Create Date: 2024-04-01 15:03:45.067453

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlalchemy_utils


# revision identifiers, used by Alembic.
revision: str = 'f6a6009a41c6'
down_revision: Union[str, None] = 'e09241fcfa20'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(op.f('ix_access_tickets_is_active'), 'access_tickets', ['is_active'], unique=False)
    op.create_index(op.f('ix_access_tickets_user_id'), 'access_tickets', ['user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_access_tickets_user_id'), table_name='access_tickets')
    op.drop_index(op.f('ix_access_tickets_is_active'), table_name='access_tickets')
    # ### end Alembic commands ###
