"""access_tickets_lists has been added!

Revision ID: f7fd01e45270
Revises: 669f6896aa21
Create Date: 2024-01-30 16:38:35.242566

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlalchemy_utils


# revision identifiers, used by Alembic.
revision: str = 'f7fd01e45270'
down_revision: Union[str, None] = '669f6896aa21'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('access_tickets_lists',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('main_access_ticket_client_id', sa.String(), nullable=False, comment='Идентификатор номерка (главного номерка), на который записываются услуги из группы'),
    sa.Column('access_ticket_client_id', sa.String(), nullable=False, comment='Идентификатор номерка, относящегося к главному'),
    sa.PrimaryKeyConstraint('id'),
    comment='Таблица "Группы номерков прилинкованных к главному номерку, на который записываются все услуги из группы"'
    )
    op.create_index(op.f('ix_access_tickets_lists_id'), 'access_tickets_lists', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_access_tickets_lists_id'), table_name='access_tickets_lists')
    op.drop_table('access_tickets_lists')
    # ### end Alembic commands ###
