"""paykeeper_payments_data has been added!

Revision ID: fa1a42696358
Revises: 23b080e6ef68
Create Date: 2024-02-15 13:44:30.372727

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlalchemy_utils


# revision identifiers, used by Alembic.
revision: str = 'fa1a42696358'
down_revision: Union[str, None] = '23b080e6ef68'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('paykeeper_payments_data',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_payment_id', sa.Integer(), nullable=False, comment='Идентификатор платежа пользовтеля в PG'),
    sa.Column('paykeeper_id', sa.String(), nullable=False, comment='Идентификатор платежа в личном кабинете системы PeyKeeper'),
    sa.Column('pay_amount', sa.Float(), nullable=True, comment='Сумма платежа'),
    sa.Column('refund_amount', sa.Float(), nullable=True, comment='Возвращенная часть платежа'),
    sa.Column('clientid', sa.String(), nullable=False, comment='Идентификатор клиента в системе магазина (информация о пользователе)'),
    sa.Column('orderid', sa.String(), nullable=False, comment='Номер заказа в системе магазина (наш payment_client_id)'),
    sa.Column('payment_system_id', sa.String(), nullable=True, comment='Идентификатор платежной системы'),
    sa.Column('unique_id', sa.String(), nullable=True, comment='Уникальный идентификатор транзакции'),
    sa.Column('status', sa.String(), nullable=True, comment='Статус платежа: ("obtained", "stuck", "success", "canceled", "failed", "pending",                            "refunding", "refunded", "partially_refunded")'),
    sa.Column('repeat_counter', sa.Integer(), nullable=True, comment='Количество отправленных запросов при проведении платежа в систему магазина'),
    sa.Column('pending_datetime', sa.DateTime(), nullable=True, comment='Дата/Время создания платежа'),
    sa.Column('obtain_datetime', sa.DateTime(), nullable=True, comment='Дата/Время создания платежа'),
    sa.Column('success_datetime', sa.DateTime(), nullable=True, comment='Дата/Время информирования магазина о проведенном платеже'),
    sa.ForeignKeyConstraint(['user_payment_id'], ['users_payments.id'], ),
    sa.PrimaryKeyConstraint('id'),
    comment='Таблица "Таблица данных системы Pay Keeper"'
    )
    op.create_index(op.f('ix_paykeeper_payments_data_id'), 'paykeeper_payments_data', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_paykeeper_payments_data_id'), table_name='paykeeper_payments_data')
    op.drop_table('paykeeper_payments_data')
    # ### end Alembic commands ###
