"""login_phone_number nullable=True

Revision ID: fbe7656ef925
Revises: d38edaf29b97
Create Date: 2023-12-12 15:36:37.104875

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlalchemy_utils


# revision identifiers, used by Alembic.
revision: str = 'fbe7656ef925'
down_revision: Union[str, None] = 'd38edaf29b97'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('users', 'login_phone_number',
               existing_type=sa.VARCHAR(length=25),
               nullable=True,
               existing_comment='Номер телефона пользователя, используемый в качестве логина')
    op.alter_column('users', 'is_verified',
               existing_type=sa.BOOLEAN(),
               comment='Флаг пользователь верефицирован/не верефицирован',
               existing_comment='Флаг телефон верифицирован/не верефицирован',
               existing_nullable=True)
    op.drop_constraint('users_login_phone_number_key', 'users', type_='unique')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint('users_login_phone_number_key', 'users', ['login_phone_number'])
    op.alter_column('users', 'is_verified',
               existing_type=sa.BOOLEAN(),
               comment='Флаг телефон верифицирован/не верефицирован',
               existing_comment='Флаг пользователь верефицирован/не верефицирован',
               existing_nullable=True)
    op.alter_column('users', 'login_phone_number',
               existing_type=sa.VARCHAR(length=25),
               nullable=False,
               existing_comment='Номер телефона пользователя, используемый в качестве логина')
    # ### end Alembic commands ###
