"""Fixed typos_4!

Revision ID: fc1cd35d5008
Revises: 4c9b18e45661
Create Date: 2023-11-21 16:34:34.554940

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlalchemy_utils
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'fc1cd35d5008'
down_revision: Union[str, None] = '4c9b18e45661'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('policies',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('client_polycy_id', sa.Integer(), nullable=True, comment='Идентификатор полиса в системе клиента'),
    sa.Column('user_id', sa.Integer(), nullable=False, comment='Идентификатор пользователя'),
    sa.Column('shifr_id', sa.Integer(), nullable=False, comment='Идентификатор шифра'),
    sa.Column('start_date', sa.DateTime(), nullable=False, comment='Начальная дата периода действия полиса'),
    sa.Column('end_date', sa.DateTime(), nullable=False, comment='Конечная дата периода действия полиса'),
    sa.Column('status', sa.Integer(), nullable=False, comment='Статус полиса'),
    sa.Column('series', sa.String(length=50), nullable=True, comment='Серия полиса'),
    sa.Column('number', sa.String(length=100), nullable=True, comment='Номер полиса'),
    sa.Column('contract_date', sa.DateTime(), nullable=False, comment='Дата выдачи полиса'),
    sa.Column('price', sa.Float(), nullable=True, comment='Цена полиса'),
    sa.Column('discount', sa.Float(), nullable=True, comment='Скидка на полис'),
    sa.Column('discoumt_coefficient', sa.Float(), nullable=True, comment='Коэффициент на скидку'),
    sa.Column('amount', sa.Float(), nullable=True, comment='Итоговая стоимость полиса'),
    sa.Column('current_paid', sa.Float(), nullable=True, comment='Текущая оплаченная сумма'),
    sa.Column('is_active', sa.Boolean(), nullable=True, comment='Флаг активна/не активна'),
    sa.ForeignKeyConstraint(['shifr_id'], ['shifrs.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    comment='Таблица "Полисы"'
    )
    op.create_index(op.f('ix_policies_id'), 'policies', ['id'], unique=False)
    op.drop_constraint('users_subscribes_police_id_fkey', 'users_subscribes', type_='foreignkey')
    op.drop_column('users_subscribes', 'police_id')
    op.drop_index('ix_polices_id', table_name='polices')
    op.drop_table('polices')
    op.add_column('users_subscribes', sa.Column('policy_id', sa.Integer(), nullable=False, comment='Идентификатор полиса'))
    op.create_foreign_key(None, 'users_subscribes', 'policies', ['policy_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users_subscribes', sa.Column('police_id', sa.INTEGER(), autoincrement=False, nullable=False, comment='Идентификатор полиса'))
    op.drop_constraint(None, 'users_subscribes', type_='foreignkey')
    op.create_foreign_key('users_subscribes_police_id_fkey', 'users_subscribes', 'polices', ['police_id'], ['id'])
    op.drop_column('users_subscribes', 'policy_id')
    op.create_table('polices',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('client_police_id', sa.INTEGER(), autoincrement=False, nullable=True, comment='Идентификатор полиса в системе клиента'),
    sa.Column('user_id', sa.INTEGER(), autoincrement=False, nullable=False, comment='Идентификатор пользователя'),
    sa.Column('shifr_id', sa.INTEGER(), autoincrement=False, nullable=False, comment='Идентификатор шифра'),
    sa.Column('start_date', postgresql.TIMESTAMP(), autoincrement=False, nullable=False, comment='Начальная дата периода действия полиса'),
    sa.Column('end_date', postgresql.TIMESTAMP(), autoincrement=False, nullable=False, comment='Конечная дата периода действия полиса'),
    sa.Column('status', sa.INTEGER(), autoincrement=False, nullable=False, comment='Статус полиса'),
    sa.Column('series', sa.VARCHAR(length=50), autoincrement=False, nullable=True, comment='Серия полиса'),
    sa.Column('number', sa.VARCHAR(length=100), autoincrement=False, nullable=True, comment='Номер полиса'),
    sa.Column('contract_date', postgresql.TIMESTAMP(), autoincrement=False, nullable=False, comment='Дата выдачи полиса'),
    sa.Column('price', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True, comment='Цена полиса'),
    sa.Column('discount', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True, comment='Скидка на полис'),
    sa.Column('discoumt_coefficient', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True, comment='Коэффициент на скидку'),
    sa.Column('amount', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True, comment='Итоговая стоимость полиса'),
    sa.Column('current_paid', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True, comment='Текущая оплаченная сумма'),
    sa.Column('is_active', sa.BOOLEAN(), autoincrement=False, nullable=True, comment='Флаг активна/не активна'),
    sa.ForeignKeyConstraint(['shifr_id'], ['shifrs.id'], name='polices_shifr_id_fkey'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name='polices_user_id_fkey'),
    sa.PrimaryKeyConstraint('id', name='polices_pkey'),
    comment='Таблица "Полисы"'
    )
    op.create_index('ix_polices_id', 'polices', ['id'], unique=False)
    op.drop_index(op.f('ix_policies_id'), table_name='policies')
    op.drop_table('policies')
    # ### end Alembic commands ###
