"""Cleared ServiceTable is ok!

Revision ID: fcc60905f490
Revises: fbc2dfa53a0a
Create Date: 2023-11-15 14:00:27.502691

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlalchemy_utils


# revision identifiers, used by Alembic.
revision: str = 'fcc60905f490'
down_revision: Union[str, None] = 'fbc2dfa53a0a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('prices', 'service_id',
               existing_type=sa.INTEGER(),
               nullable=True,
               existing_comment='Идентификатор услуги')
    op.alter_column('prices', 'medical_center_id',
               existing_type=sa.INTEGER(),
               nullable=True,
               existing_comment='Идентификатор медицинского центра')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('prices', 'medical_center_id',
               existing_type=sa.INTEGER(),
               nullable=False,
               existing_comment='Идентификатор медицинского центра')
    op.alter_column('prices', 'service_id',
               existing_type=sa.INTEGER(),
               nullable=False,
               existing_comment='Идентификатор услуги')
    # ### end Alembic commands ###
