"""The index on client_id of access_tickets has been added!

Revision ID: fdf8b8cd6e0b
Revises: 7ebe4df98687
Create Date: 2024-03-27 15:57:34.246536

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlalchemy_utils


# revision identifiers, used by Alembic.
revision: str = 'fdf8b8cd6e0b'
down_revision: Union[str, None] = '7ebe4df98687'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(op.f('ix_access_tickets_client_id'), 'access_tickets', ['client_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_access_tickets_client_id'), table_name='access_tickets')
    # ### end Alembic commands ###
