"""Added users_purchases table!

Revision ID: fff86357ff26
Revises: 9d2731301df7
Create Date: 2023-11-30 14:11:35.273729

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlalchemy_utils


# revision identifiers, used by Alembic.
revision: str = 'fff86357ff26'
down_revision: Union[str, None] = '9d2731301df7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users_purchases',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('client_user_purchase_id', sa.Integer(), nullable=True, comment='Идентификатор покупки пользователя в системе клиента'),
    sa.Column('user_id', sa.Integer(), nullable=False, comment='Идентификатор пользователя'),
    sa.Column('policy_id', sa.Integer(), nullable=False, comment='Идентификатор полиса'),
    sa.Column('shifr_id', sa.Integer(), nullable=True, comment='Идентификатор шифра'),
    sa.Column('user_payment_id', sa.Integer(), nullable=False, comment='Идентификатор платежа пользовталя, СДЕЛАТЬ ForeignKey'),
    sa.Column('doctor_exec_id', sa.Integer(), nullable=True, comment='Идентификатор доктора, выполнившего услугу'),
    sa.Column('doctor_nurse_id', sa.Integer(), nullable=True, comment='Идентификатор медсестры, выполнившей услугу'),
    sa.Column('payment_date', sa.DateTime(), nullable=False, comment='Дата и время платежа'),
    sa.Column('service_id', sa.Integer(), nullable=False, comment='Идентификатор услуги'),
    sa.Column('service_quantity', sa.Integer(), nullable=False, comment='Количество таких услуг'),
    sa.Column('price', sa.Float(), nullable=True, comment='Цена услуги'),
    sa.Column('discount', sa.Float(), nullable=True, comment='Скидка на цену услуги в %'),
    sa.Column('discount_koef', sa.Float(), nullable=True, comment='Коэффициент скидки'),
    sa.Column('amount', sa.Float(), nullable=True, comment='Итоговая стоимость услуги'),
    sa.ForeignKeyConstraint(['doctor_exec_id'], ['doctors_medical_centers.id'], ),
    sa.ForeignKeyConstraint(['doctor_nurse_id'], ['doctors_medical_centers.id'], ),
    sa.ForeignKeyConstraint(['policy_id'], ['policies.id'], ),
    sa.ForeignKeyConstraint(['service_id'], ['services.id'], ),
    sa.ForeignKeyConstraint(['shifr_id'], ['shifrs.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    comment='Таблица "Покупки пользователей"'
    )
    op.create_index(op.f('ix_users_purchases_id'), 'users_purchases', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_users_purchases_id'), table_name='users_purchases')
    op.drop_table('users_purchases')
    # ### end Alembic commands ###
